graph LR A[India's Transport Network] --> B(Roads) A --> C(Railways) A --> D(Airways) A --> E(Inland Waterways) E --> E1[Sagarmala Programme] E --> E2[National Inland Water Transport (NIWT)] B & C & D & E --> F[National Transport Policy 2020]