mindmap
  root((The President))
    Electoral College
      ::icon(fas fa-check)
      Elected MPs  LS & RS
      ::icon(fas fa-check)
      Elected MLAs  States
      ::icon(fas fa-check)
      Delhi/Puducherry MLAs
    Impeachment  61
      ::icon(fas fa-check)
      Violation of Constitution
      ::icon(fas fa-check)
      Initiated in either House
      ::icon(fas fa-check)
      2/3 of Total Membership
    Vetoes  111
      ::icon(fas fa-check)
      Absolute Veto  Ends bill
      ::icon(fas fa-check)
      Suspensive Veto  Return
      ::icon(fas fa-check)
      Pocket Veto  No action
    Pardons  72
      ::icon(fas fa-check)
      Pardon  Complete free
      ::icon(fas fa-check)
      Commutation  Lighten type
      ::icon(fas fa-check)
      Remission  Reduce time