mindmap
  root((Intro Econ))
    Sectors
      ::icon(fas fa-check)
      Primary: Raw Material
      ::icon(fas fa-check)
      Secondary: Factories
      ::icon(fas fa-check)
      Tertiary: Services
    National Income
      ::icon(fas fa-check)
      GDP: Inside borders
      ::icon(fas fa-check)
      GNP: Citizens only
      ::icon(fas fa-check)
      Real GDP: Inflation adjusted