mindmap
  root((Parliament))
    Rajya Sabha
      ::icon(fas fa-check)
      Max 250  12 Nominated
      ::icon(fas fa-check)
      Permanent body
      ::icon(fas fa-check)
      1/3 retire every 2 years
    Lok Sabha
      ::icon(fas fa-check)
      Max 550
      ::icon(fas fa-check)
      Normal term 5 years
      ::icon(fas fa-check)
      Directly elected by people
    Joint Sitting  108
      ::icon(fas fa-check)
      Summoned by President
      ::icon(fas fa-check)
      Presided by LS Speaker
      ::icon(fas fa-check)
      Not for Money/CA Bills
    Money Bills  110
      ::icon(fas fa-check)
      Lok Sabha only
      ::icon(fas fa-check)
      Certified by Speaker
      ::icon(fas fa-check)
      RS has max 14 days