mindmap
  root((Ratios & Percent))
    Proportions
      ::icon(fas fa-check)
      Extremes = Means product
      ::icon(fas fa-check)
      Mean: x = √ ab
      ::icon(fas fa-check)
      Third: x = b²/a
    Percentages
      ::icon(fas fa-check)
      Fraction to %  x100
      ::icon(fas fa-check)
      Change % = delta/original
    Profit & Loss
      ::icon(fas fa-check)
      Gain = SP - CP
      ::icon(fas fa-check)
      Loss = CP - SP
      ::icon(fas fa-check)
      Percentage based on CP
    Discounts
      ::icon(fas fa-check)
      Discount = MP - SP
      ::icon(fas fa-check)
      Discount % based on MP