// Automatically generated by scripts/generate_diagram_map.js
window.DIAGRAM_MAP = {
  "cell-structure": [
    {
      "src": "assets/diagrams/Biology/cell-biology-genetics/cell-structure.png",
      "title": "cell-structure"
    },
    {
      "src": "assets/diagrams/Biology/cell_biology_genetics/biology_cell_biology_genetics_cell_structure_cell_division_dna_and_rna.png",
      "title": "biology_cell_biology_genetics_cell_structure_cell_division_dna_and_rna"
    },
    {
      "src": "assets/diagrams/Biology/cell_biology_genetics/biology_cell_biology_genetics_cell_structure_cell_division_mitosis_meiosis_comparison.png",
      "title": "biology_cell_biology_genetics_cell_structure_cell_division_mitosis_meiosis_comparison"
    },
    {
      "src": "assets/diagrams/Biology/cell_biology_genetics/biology_cell_biology_genetics_cell_structure_cell_division_plant_animal_cell.png",
      "title": "biology_cell_biology_genetics_cell_structure_cell_division_plant_animal_cell"
    },
    {
      "src": "assets/diagrams/Biology/cell_biology_genetics/biology_cell_biology_genetics_cell_structure_cell_division_prokaryotic_eukaryotic_cells.png",
      "title": "biology_cell_biology_genetics_cell_structure_cell_division_prokaryotic_eukaryotic_cells"
    }
  ],
  "biology-ecology-basics": [
    {
      "src": "assets/diagrams/Biology/ecology-ecosystems/biology-ecology-basics.png",
      "title": "biology-ecology-basics"
    },
    {
      "src": "assets/diagrams/Biology/ecology_ecosystems/biology_ecology_ecosystems_ecology_basics_pyramids_ecological_food_pyramid.png",
      "title": "biology_ecology_ecosystems_ecology_basics_pyramids_ecological_food_pyramid"
    },
    {
      "src": "assets/diagrams/Biology/ecology_ecosystems/biology_ecology_ecosystems_ecology_basics_pyramids_food_chain_ecosystem.png",
      "title": "biology_ecology_ecosystems_ecology_basics_pyramids_food_chain_ecosystem"
    },
    {
      "src": "assets/diagrams/Biology/ecology_ecosystems/biology_ecology_ecosystems_ecology_basics_pyramids_food_web_ecosystem.png",
      "title": "biology_ecology_ecosystems_ecology_basics_pyramids_food_web_ecosystem"
    },
    {
      "src": "assets/diagrams/Biology/ecology_ecosystems/biology_ecology_ecosystems_ecology_basics_pyramids_nitrogen_cycle.png",
      "title": "biology_ecology_ecosystems_ecology_basics_pyramids_nitrogen_cycle"
    }
  ],
  "human-systems": [
    {
      "src": "assets/diagrams/Biology/human-physiology/human-systems.png",
      "title": "human-systems"
    },
    {
      "src": "assets/diagrams/Biology/human_physiology/biology_human_physiology_vital_human_systems_organs_central_nervous_system_neuron.png",
      "title": "biology_human_physiology_vital_human_systems_organs_central_nervous_system_neuron"
    },
    {
      "src": "assets/diagrams/Biology/human_physiology/biology_human_physiology_vital_human_systems_organs_endocrine_system_glands.png",
      "title": "biology_human_physiology_vital_human_systems_organs_endocrine_system_glands"
    },
    {
      "src": "assets/diagrams/Biology/human_physiology/biology_human_physiology_vital_human_systems_organs_human_blood_circulation.png",
      "title": "biology_human_physiology_vital_human_systems_organs_human_blood_circulation"
    },
    {
      "src": "assets/diagrams/Biology/human_physiology/biology_human_physiology_vital_human_systems_organs_human_digestive_system.png",
      "title": "biology_human_physiology_vital_human_systems_organs_human_digestive_system"
    }
  ],
  "plant-kingdom": [
    {
      "src": "assets/diagrams/Biology/plant-animal-kingdoms/xylem & phlom.png",
      "title": "xylem & phlom"
    },
    {
      "src": "assets/diagrams/Biology/plant_animal_kingdoms/biology_plant_animal_kingdoms_plant_kingdom_classification_plant_root_types.png",
      "title": "biology_plant_animal_kingdoms_plant_kingdom_classification_plant_root_types"
    },
    {
      "src": "assets/diagrams/Biology/plant_animal_kingdoms/biology_plant_animal_kingdoms_plant_kingdom_classification_stem_modifications.png",
      "title": "biology_plant_animal_kingdoms_plant_kingdom_classification_stem_modifications"
    },
    {
      "src": "assets/diagrams/Biology/plant_animal_kingdoms/biology_plant_animal_kingdoms_plant_kingdom_classification_xylem_phloem_transport.png",
      "title": "biology_plant_animal_kingdoms_plant_kingdom_classification_xylem_phloem_transport"
    }
  ],
  "plant-reproduction": [
    {
      "src": "assets/diagrams/Biology/plant-physiology-reproduction/plant-reproduction.png",
      "title": "plant-reproduction"
    },
    {
      "src": "assets/diagrams/Biology/plant_physiology_reproduction/biology_plant_physiology_reproduction_plant_reproduction_hormones_leaf_anatomy_structure.png",
      "title": "biology_plant_physiology_reproduction_plant_reproduction_hormones_leaf_anatomy_structure"
    },
    {
      "src": "assets/diagrams/Biology/plant_physiology_reproduction/biology_plant_physiology_reproduction_plant_reproduction_hormones_parts_of_flower.png",
      "title": "biology_plant_physiology_reproduction_plant_reproduction_hormones_parts_of_flower"
    },
    {
      "src": "assets/diagrams/Biology/plant_physiology_reproduction/biology_plant_physiology_reproduction_plant_reproduction_hormones_seed_germination_growth.png",
      "title": "biology_plant_physiology_reproduction_plant_reproduction_hormones_seed_germination_growth"
    }
  ],
  "acids-bases": [
    {
      "src": "assets/diagrams/Chemistry/acids-bases-salts/acids-bases.png",
      "title": "acids-bases"
    },
    {
      "src": "assets/diagrams/Chemistry/acids_bases_salts/chemistry_acids_bases_salts_acids_bases_ph_indicators_ph_scale_substances.png",
      "title": "chemistry_acids_bases_salts_acids_bases_ph_indicators_ph_scale_substances"
    }
  ],
  "chemistry-numericals": [
    {
      "src": "assets/diagrams/Chemistry/carbon-compounds-numericals/chemistry-numericals.png",
      "title": "chemistry-numericals"
    }
  ],
  "carbon-compounds": [
    {
      "src": "assets/diagrams/Chemistry/carbon_compounds_numericals/chemistry_carbon_compounds_numericals_mole_concept_concentration_terms_mole_concept_formulas.png",
      "title": "chemistry_carbon_compounds_numericals_mole_concept_concentration_terms_mole_concept_formulas"
    }
  ],
  "syl-numerical": [
    {
      "src": "assets/diagrams/Chemistry/chemical-bonding/syl-numerical.png",
      "title": "syl-numerical"
    },
    {
      "src": "assets/diagrams/Chemistry/chemical_bonding/chemistry_chemical_bonding_chemical_bonding_periodic_table_electronic_configuration_valency.png",
      "title": "chemistry_chemical_bonding_chemical_bonding_periodic_table_electronic_configuration_valency"
    },
    {
      "src": "assets/diagrams/Chemistry/chemical_bonding/chemistry_chemical_bonding_chemical_bonding_periodic_table_periodic_table.png",
      "title": "chemistry_chemical_bonding_chemical_bonding_periodic_table_periodic_table"
    },
    {
      "src": "assets/diagrams/Chemistry/chemical_bonding/chemistry_chemical_bonding_chemical_bonding_periodic_table_periodic_table_trends.png",
      "title": "chemistry_chemical_bonding_chemical_bonding_periodic_table_periodic_table_trends"
    },
    {
      "src": "assets/diagrams/Chemistry/chemical_bonding/chemistry_chemical_bonding_chemical_bonding_periodic_table_types_of_bonds.png",
      "title": "chemistry_chemical_bonding_chemical_bonding_periodic_table_types_of_bonds"
    }
  ],
  "chemistry-everyday-fertilisers": [
    {
      "src": "assets/diagrams/Chemistry/everyday-environmental-chemistry/chemistry-everyday-fertilisers.png",
      "title": "chemistry-everyday-fertilisers"
    }
  ],
  "environmental-chemistry": [
    {
      "src": "assets/diagrams/Chemistry/everyday-environmental-chemistry/environmental-chemistry.png",
      "title": "environmental-chemistry"
    },
    {
      "src": "assets/diagrams/Chemistry/everyday_environmental_chemistry/chemistry_everyday_environmental_chemistry_environmental_chemistry_pollution_greenhouse_effect_comparison.png",
      "title": "chemistry_everyday_environmental_chemistry_environmental_chemistry_pollution_greenhouse_effect_comparison"
    },
    {
      "src": "assets/diagrams/Chemistry/everyday_environmental_chemistry/chemistry_everyday_environmental_chemistry_everyday_chemistry_fertilisers_fuels_contact_process_sulphuric_acid.png",
      "title": "chemistry_everyday_environmental_chemistry_everyday_chemistry_fertilisers_fuels_contact_process_sulphuric_acid"
    },
    {
      "src": "assets/diagrams/Chemistry/everyday_environmental_chemistry/chemistry_everyday_environmental_chemistry_everyday_chemistry_fertilisers_fuels_haber_process_ammonia.png",
      "title": "chemistry_everyday_environmental_chemistry_everyday_chemistry_fertilisers_fuels_haber_process_ammonia"
    }
  ],
  "reactivity-series": [
    {
      "src": "assets/diagrams/Chemistry/metals-metallurgy/reactivity-series.png",
      "title": "reactivity-series"
    }
  ],
  "economic-impact-british": [
    {
      "src": "assets/diagrams/economics/consumer_behaviour_post_pandemic/pandemic_impact_timeline.png",
      "title": "pandemic_impact_timeline"
    },
    {
      "src": "assets/diagrams/History/5-modern-india-highest-priority/economic-impact-british.png",
      "title": "economic-impact-british"
    }
  ],
  "syl-geog": [
    {
      "src": "assets/diagrams/economics/human_development_index/hdi_component_improvements_for_india.png",
      "title": "hdi_component_improvements_for_india"
    },
    {
      "src": "assets/diagrams/geography/indian-geography/syl-geog.png",
      "title": "syl-geog"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_indian_monsoon_mechanism.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_indian_monsoon_mechanism"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_indian_mountain_passes.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_indian_mountain_passes"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_indian_rainfall_map.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_indian_rainfall_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_indian_soil_types.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_indian_soil_types"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_india_physical_map.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_india_physical_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_indian_geography_rivers_passes_soils_rivers_of_india.png",
      "title": "geography_indian_geography_indian_geography_rivers_passes_soils_rivers_of_india"
    }
  ],
  "india-forests-wetlands": [
    {
      "src": "assets/diagrams/economics/opportunity_cost/opportunity_cost_decision_tree.png",
      "title": "opportunity_cost_decision_tree"
    },
    {
      "src": "assets/diagrams/geography/indian-geography/india-forests-wetlands.png",
      "title": "india-forests-wetlands"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_forests_trees_wetlands_of_india_ramsar_sites_india.png",
      "title": "geography_indian_geography_forests_trees_wetlands_of_india_ramsar_sites_india"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_forests_trees_wetlands_of_india_ramsar_sites_india_map.png",
      "title": "geography_indian_geography_forests_trees_wetlands_of_india_ramsar_sites_india_map"
    }
  ],
  "data-interpretation": [
    {
      "src": "assets/diagrams/economics/survey_statistics/survey_response_bar_chart.jpg",
      "title": "survey_response_bar_chart"
    },
    {
      "src": "assets/diagrams/mathematics/statistics-probability/data-interpretation.png",
      "title": "data-interpretation"
    },
    {
      "src": "assets/diagrams/mathematics/statistics_probability/mathematics_statistics_probability_data_interpretation_tables_bar_pie_charts_statistical_data_visualizations.png",
      "title": "mathematics_statistics_probability_data_interpretation_tables_bar_pie_charts_statistical_data_visualizations"
    }
  ],
  "climatology-clouds": [
    {
      "src": "assets/diagrams/environment/earthquake_zones/seismic_hazard_zones_of_india.jpg",
      "title": "seismic_hazard_zones_of_india"
    },
    {
      "src": "assets/diagrams/geography/physical-world-geography/climatology-clouds.png",
      "title": "climatology-clouds"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_climatology_climatic_zones_clouds_climate_of_india.png",
      "title": "geography_physical_world_geography_climatology_climatic_zones_clouds_climate_of_india"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_climatology_climatic_zones_clouds_water_cycle_diagram.png",
      "title": "geography_physical_world_geography_climatology_climatic_zones_clouds_water_cycle_diagram"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_climatology_climatic_zones_clouds_world_climatic_zones.png",
      "title": "geography_physical_world_geography_climatology_climatic_zones_clouds_world_climatic_zones"
    }
  ],
  "india-national-parks": [
    {
      "src": "assets/diagrams/geography/indian-geography/india-national-parks.png",
      "title": "india-national-parks"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_national_parks_of_india_map_guide_indian_biosphere_reserves.png",
      "title": "geography_indian_geography_national_parks_of_india_map_guide_indian_biosphere_reserves"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_national_parks_of_india_map_guide_national_parks_india_map.png",
      "title": "geography_indian_geography_national_parks_of_india_map_guide_national_parks_india_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_national_parks_of_india_map_guide_tiger_reserves_india.png",
      "title": "geography_indian_geography_national_parks_of_india_map_guide_tiger_reserves_india"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_national_parks_of_india_map_guide_tiger_reserves_map.png",
      "title": "geography_indian_geography_national_parks_of_india_map_guide_tiger_reserves_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_national_parks_of_india_map_guide_wildlife_sanctuaries_india.png",
      "title": "geography_indian_geography_national_parks_of_india_map_guide_wildlife_sanctuaries_india"
    }
  ],
  "india-resources-farming": [
    {
      "src": "assets/diagrams/geography/indian-geography/india-resources-farming.png",
      "title": "india-resources-farming"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_mineral_resources_types_of_farming_indian_crops_map.png",
      "title": "geography_indian_geography_mineral_resources_types_of_farming_indian_crops_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_mineral_resources_types_of_farming_indian_mineral_resources.png",
      "title": "geography_indian_geography_mineral_resources_types_of_farming_indian_mineral_resources"
    }
  ],
  "india-transport-routes": [
    {
      "src": "assets/diagrams/geography/indian-geography/india-transport-routes.png",
      "title": "india-transport-routes"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_transport_routes_highways_waterways_indian_airports_map.png",
      "title": "geography_indian_geography_transport_routes_highways_waterways_indian_airports_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_transport_routes_highways_waterways_indian_ports_map.png",
      "title": "geography_indian_geography_transport_routes_highways_waterways_indian_ports_map"
    }
  ],
  "mapping-borders-capitals": [
    {
      "src": "assets/diagrams/geography/indian-geography/mapping-borders-capitals.png",
      "title": "mapping-borders-capitals"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_borders_capitals_mapping_indian_mountains_map.png",
      "title": "geography_indian_geography_borders_capitals_mapping_indian_mountains_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_borders_capitals_mapping_indian_plateaus_map.png",
      "title": "geography_indian_geography_borders_capitals_mapping_indian_plateaus_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_borders_capitals_mapping_india_political_map.png",
      "title": "geography_indian_geography_borders_capitals_mapping_india_political_map"
    },
    {
      "src": "assets/diagrams/geography/indian_geography/geography_indian_geography_borders_capitals_mapping_world_continents_oceans.png",
      "title": "geography_indian_geography_borders_capitals_mapping_world_continents_oceans"
    }
  ],
  "geog-geopolitics": [
    {
      "src": "assets/diagrams/geography/industries-geopolitics/geog-geopolitics.png",
      "title": "geog-geopolitics"
    }
  ],
  "earth-atmosphere": [
    {
      "src": "assets/diagrams/geography/physical-world-geography/earth-atmosphere.png",
      "title": "earth-atmosphere"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_anticyclone_pressure_system.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_anticyclone_pressure_system"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_atmospheric_layers_diagram.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_atmospheric_layers_diagram"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_cyclone_structure_formation.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_cyclone_structure_formation"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_internal_structure_earth.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_internal_structure_earth"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_jet_streams_diagram.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_jet_streams_diagram"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_ozone_layer_depletion.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_ozone_layer_depletion"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_planetary_winds_circulation.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_planetary_winds_circulation"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_earth_structure_atmosphere_pressure_belts_earth.png",
      "title": "geography_physical_world_geography_earth_structure_atmosphere_pressure_belts_earth"
    }
  ],
  "geomorphology-rocks": [
    {
      "src": "assets/diagrams/geography/physical-world-geography/geomorphology-rocks.png",
      "title": "geomorphology-rocks"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_earthquake_anatomy_seismic_waves.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_earthquake_anatomy_seismic_waves"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_plate_tectonics_infographic.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_plate_tectonics_infographic"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_rock_cycle.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_rock_cycle"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_rock_cycle_process.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_rock_cycle_process"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_volcano_anatomy.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_volcano_anatomy"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_weathering_of_rocks.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_weathering_of_rocks"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_world_earthquake_belts.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_world_earthquake_belts"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_world_volcano_belts.png",
      "title": "geography_physical_world_geography_geomorphology_rocks_plate_tectonics_volcanism_world_volcano_belts"
    }
  ],
  "universe-solar-system": [
    {
      "src": "assets/diagrams/geography/physical-world-geography/universe-solar-system.png",
      "title": "universe-solar-system"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_earths_rotation_mechanics.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_earths_rotation_mechanics"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_earth_rotation_seasons.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_earth_rotation_seasons"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_geographic_lines_latitude.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_geographic_lines_latitude"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_international_date_line.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_international_date_line"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_longitudes_prime_meridian_globe.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_longitudes_prime_meridian_globe"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_spring_neap_tides.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_spring_neap_tides"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_the_universe_solar_system_world_time_zones.png",
      "title": "geography_physical_world_geography_the_universe_solar_system_world_time_zones"
    }
  ],
  "world-geography-mountains": [
    {
      "src": "assets/diagrams/geography/physical-world-geography/world-geography-mountains.png",
      "title": "world-geography-mountains"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_coastal_landforms.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_coastal_landforms"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_fold_mountains_structure.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_fold_mountains_structure"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_glacier_landforms.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_glacier_landforms"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_river_landforms_course.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_river_landforms_course"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_world_mountains_map.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_world_mountains_map"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_world_geography_mountains_forests_rivers_world_rivers_map.png",
      "title": "geography_physical_world_geography_world_geography_mountains_forests_rivers_world_rivers_map"
    }
  ],
  "world-geography-straits-deserts": [
    {
      "src": "assets/diagrams/geography/physical-world-geography/world-geography-straits-deserts.png",
      "title": "world-geography-straits-deserts"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_desert_landforms.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_desert_landforms"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_indian_deserts_map.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_indian_deserts_map"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_ocean_currents_world.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_ocean_currents_world"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_seafloor_topography_features.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_seafloor_topography_features"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_world_canals_map.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_world_canals_map"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_world_deserts_map.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_world_deserts_map"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_world_ocean_currents.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_world_ocean_currents"
    },
    {
      "src": "assets/diagrams/geography/physical_world_geography/geography_physical_world_geography_straits_canals_deserts_seas_world_straits_map.png",
      "title": "geography_physical_world_geography_straits_canals_deserts_seas_world_straits_map"
    }
  ],
  "buddhism-jainism": [
    {
      "src": "assets/diagrams/History/3-ancient-india/buddhism-jainism.png",
      "title": "buddhism-jainism"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_buddhism_jainism_buddhism_teachings_origins.png",
      "title": "history_3_ancient_india_buddhism_jainism_buddhism_teachings_origins"
    }
  ],
  "gupta-period": [
    {
      "src": "assets/diagrams/History/3-ancient-india/gupta-period.png",
      "title": "gupta-period"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_gupta_period_gupta_empire_infographic.png",
      "title": "history_3_ancient_india_gupta_period_gupta_empire_infographic"
    }
  ],
  "indus-valley-civilization": [
    {
      "src": "assets/diagrams/History/3-ancient-india/indus-valley-civilization.png",
      "title": "indus-valley-civilization"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_indus_valley_civilization_indus_valley_city_plan.png",
      "title": "history_3_ancient_india_indus_valley_civilization_indus_valley_city_plan"
    }
  ],
  "mauryan-period": [
    {
      "src": "assets/diagrams/History/3-ancient-india/mauryan-period.png",
      "title": "mauryan-period"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_mauryan_period_ashokan_pillar_edicts.png",
      "title": "history_3_ancient_india_mauryan_period_ashokan_pillar_edicts"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_mauryan_period_mauryan_empire_infographic.png",
      "title": "history_3_ancient_india_mauryan_period_mauryan_empire_infographic"
    }
  ],
  "vedic-age": [
    {
      "src": "assets/diagrams/History/3-ancient-india/vedic-age.png",
      "title": "vedic-age"
    },
    {
      "src": "assets/diagrams/History/3_ancient_india/history_3_ancient_india_vedic_age_vedic_social_hierarchy.png",
      "title": "history_3_ancient_india_vedic_age_vedic_social_hierarchy"
    }
  ],
  "delhi-sultanate": [
    {
      "src": "assets/diagrams/History/4-medieval-india/delhi-sultanate.png",
      "title": "delhi-sultanate"
    },
    {
      "src": "assets/diagrams/History/4_medieval_india/history_4_medieval_india_delhi_sultanate_delhi_sultanate_timeline.png",
      "title": "history_4_medieval_india_delhi_sultanate_delhi_sultanate_timeline"
    }
  ],
  "early-medieval-india": [
    {
      "src": "assets/diagrams/History/4-medieval-india/early-medieval-india.png",
      "title": "early-medieval-india"
    },
    {
      "src": "assets/diagrams/History/4_medieval_india/history_4_medieval_india_early_medieval_india_battle_formations.png",
      "title": "history_4_medieval_india_early_medieval_india_battle_formations"
    }
  ],
  "marathas": [
    {
      "src": "assets/diagrams/History/4-medieval-india/marathas.png",
      "title": "marathas"
    },
    {
      "src": "assets/diagrams/History/4_medieval_india/history_4_medieval_india_marathas_maratha_empire_infographic.png",
      "title": "history_4_medieval_india_marathas_maratha_empire_infographic"
    }
  ],
  "mughal-empire": [
    {
      "src": "assets/diagrams/History/4-medieval-india/mughal-empire.png",
      "title": "mughal-empire"
    },
    {
      "src": "assets/diagrams/History/4_medieval_india/history_4_medieval_india_mughal_empire_mansabdari_system_mughal.png",
      "title": "history_4_medieval_india_mughal_empire_mansabdari_system_mughal"
    },
    {
      "src": "assets/diagrams/History/4_medieval_india/history_4_medieval_india_mughal_empire_mughal_administration_chart.png",
      "title": "history_4_medieval_india_mughal_empire_mughal_administration_chart"
    }
  ],
  "freedom-movement": [
    {
      "src": "assets/diagrams/History/5-modern-india-highest-priority/freedom-movement.png",
      "title": "freedom-movement"
    },
    {
      "src": "assets/diagrams/History/5_modern_india_highest_priority/history_5_modern_india_highest_priority_freedom_movement_gandhian_era_timeline.png",
      "title": "history_5_modern_india_highest_priority_freedom_movement_gandhian_era_timeline"
    },
    {
      "src": "assets/diagrams/History/5_modern_india_highest_priority/history_5_modern_india_highest_priority_freedom_movement_inc_sessions_map.png",
      "title": "history_5_modern_india_highest_priority_freedom_movement_inc_sessions_map"
    }
  ],
  "governor-generals-viceroys": [
    {
      "src": "assets/diagrams/History/5-modern-india-highest-priority/governor-generals-viceroys.png",
      "title": "governor-generals-viceroys"
    },
    {
      "src": "assets/diagrams/History/5_modern_india_highest_priority/history_5_modern_india_highest_priority_governor_generals_viceroys_governor_generals_viceroys_timeline.png",
      "title": "history_5_modern_india_highest_priority_governor_generals_viceroys_governor_generals_viceroys_timeline"
    }
  ],
  "revolt-1857": [
    {
      "src": "assets/diagrams/History/5-modern-india-highest-priority/revolt-1857.png",
      "title": "revolt-1857"
    },
    {
      "src": "assets/diagrams/History/5_modern_india_highest_priority/history_5_modern_india_highest_priority_revolt_of_1857_revolt_1857_centres.png",
      "title": "history_5_modern_india_highest_priority_revolt_of_1857_revolt_1857_centres"
    }
  ],
  "international-institutions": [
    {
      "src": "assets/diagrams/History/6-world-history/international-institutions.png",
      "title": "international-institutions"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_international_institutions_league_of_nations_infographic.png",
      "title": "history_6_world_history_international_institutions_league_of_nations_infographic"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_international_institutions_united_nations_system.png",
      "title": "history_6_world_history_international_institutions_united_nations_system"
    }
  ],
  "revolutions": [
    {
      "src": "assets/diagrams/History/6-world-history/revolutions.png",
      "title": "revolutions"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_revolutions_french_revolution_causes.png",
      "title": "history_6_world_history_revolutions_french_revolution_causes"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_revolutions_industrial_revolution_inventions.png",
      "title": "history_6_world_history_revolutions_industrial_revolution_inventions"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_revolutions_russian_revolution_timeline.png",
      "title": "history_6_world_history_revolutions_russian_revolution_timeline"
    }
  ],
  "world-war-i": [
    {
      "src": "assets/diagrams/History/6-world-history/world-war-i.png",
      "title": "world-war-i"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_world_war_ii_world_war_ii_powers.png",
      "title": "history_6_world_history_world_war_ii_world_war_ii_powers"
    },
    {
      "src": "assets/diagrams/History/6_world_history/history_6_world_history_world_war_i_world_war_1_alliances.png",
      "title": "history_6_world_history_world_war_i_world_war_1_alliances"
    }
  ],
  "world-war-ii": [
    {
      "src": "assets/diagrams/History/6-world-history/world-war-ii.png",
      "title": "world-war-ii"
    }
  ],
  "heritage-sites": [
    {
      "src": "assets/diagrams/History/7-art-culture-heritage/heritage-sites.jpg",
      "title": "heritage-sites"
    }
  ],
  "religion-festivals": [
    {
      "src": "assets/diagrams/History/7-art-culture-heritage/religion-festivals.jpg",
      "title": "religion-festivals"
    }
  ],
  "sources-indian-history": [
    {
      "src": "assets/diagrams/History/republic_day_celebrations/republic_day_parade_illustration_at_india_gate.jpg",
      "title": "republic_day_parade_illustration_at_india_gate"
    }
  ],
  "sikh-history": [
    {
      "src": "assets/diagrams/History/sikh_practices/sikh_congregational_worship__sangat_.jpg",
      "title": "sikh_congregational_worship__sangat_"
    }
  ],
  "time-distance": [
    {
      "src": "assets/diagrams/mathematics/arithmetic/mathematics_arithmetic_time_speed_distance_work_clock_angle_movement.png",
      "title": "mathematics_arithmetic_time_speed_distance_work_clock_angle_movement"
    },
    {
      "src": "assets/diagrams/mathematics/work_and_time/calculating_additional_men_needed_for_work_completion.png",
      "title": "calculating_additional_men_needed_for_work_completion"
    },
    {
      "src": "assets/diagrams/mathematics/work_and_time/work_time_problem_to_find_n.png",
      "title": "work_time_problem_to_find_n"
    }
  ],
  "percentages-profit-loss": [
    {
      "src": "assets/diagrams/mathematics/arithmetic/percentages-profit-loss.png",
      "title": "percentages-profit-loss"
    },
    {
      "src": "assets/diagrams/mathematics/modular_arithmetic/finding_remainder_of_37_1000_divided_by_9.png",
      "title": "finding_remainder_of_37_1000_divided_by_9"
    }
  ],
  "straight-lines": [
    {
      "src": "assets/diagrams/mathematics/coordinate-geometry-2d-3d/straight-lines.png",
      "title": "straight-lines"
    },
    {
      "src": "assets/diagrams/mathematics/coordinate_geometry_2d_3d/mathematics_coordinate_geometry_2d_3d_straight_lines_coordinate_geometry_formulas.png",
      "title": "mathematics_coordinate_geometry_2d_3d_straight_lines_coordinate_geometry_formulas"
    },
    {
      "src": "assets/diagrams/mathematics/coordinate_geometry_2d_3d/mathematics_coordinate_geometry_2d_3d_straight_lines_coordinate_system_quadrants.png",
      "title": "mathematics_coordinate_geometry_2d_3d_straight_lines_coordinate_system_quadrants"
    },
    {
      "src": "assets/diagrams/mathematics/coordinate_geometry_2d_3d/mathematics_coordinate_geometry_2d_3d_straight_lines_distance_formula_coordinate_geometry.png",
      "title": "mathematics_coordinate_geometry_2d_3d_straight_lines_distance_formula_coordinate_geometry"
    },
    {
      "src": "assets/diagrams/mathematics/coordinate_geometry_2d_3d/mathematics_coordinate_geometry_2d_3d_straight_lines_midpoint_formula_coordinate_geometry.png",
      "title": "mathematics_coordinate_geometry_2d_3d_straight_lines_midpoint_formula_coordinate_geometry"
    }
  ],
  "circles-polygons": [
    {
      "src": "assets/diagrams/mathematics/geometry/circles-polygons.png",
      "title": "circles-polygons"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_circles_polygons_angle_arc_measures_circles.png",
      "title": "mathematics_geometry_circles_polygons_angle_arc_measures_circles"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_circles_polygons_circle_properties_anatomy.png",
      "title": "mathematics_geometry_circles_polygons_circle_properties_anatomy"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_circles_polygons_cyclic_quadrilateral_properties.png",
      "title": "mathematics_geometry_circles_polygons_cyclic_quadrilateral_properties"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_circles_polygons_regular_polygons_shapes.png",
      "title": "mathematics_geometry_circles_polygons_regular_polygons_shapes"
    }
  ],
  "lines-angles-triangles": [
    {
      "src": "assets/diagrams/mathematics/geometry/lines-angles-triangles.png",
      "title": "lines-angles-triangles"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_lines_angles_triangles_congruence_of_triangles.png",
      "title": "mathematics_geometry_lines_angles_triangles_congruence_of_triangles"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_lines_angles_triangles_pythagoras_theorem_triangle.png",
      "title": "mathematics_geometry_lines_angles_triangles_pythagoras_theorem_triangle"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_lines_angles_triangles_similar_triangles_geometry.jpeg",
      "title": "mathematics_geometry_lines_angles_triangles_similar_triangles_geometry"
    },
    {
      "src": "assets/diagrams/mathematics/geometry/mathematics_geometry_lines_angles_triangles_types_of_triangles.png",
      "title": "mathematics_geometry_lines_angles_triangles_types_of_triangles"
    }
  ],
  "surface-area-volume": [
    {
      "src": "assets/diagrams/mathematics/mensuration/mathematics_mensuration_3d_solids_surface_area_volume_cone_and_frustum.png",
      "title": "mathematics_mensuration_3d_solids_surface_area_volume_cone_and_frustum"
    },
    {
      "src": "assets/diagrams/mathematics/mensuration/mathematics_mensuration_3d_solids_surface_area_volume_cube_surface_area_volume.png",
      "title": "mathematics_mensuration_3d_solids_surface_area_volume_cube_surface_area_volume"
    },
    {
      "src": "assets/diagrams/mathematics/mensuration/mathematics_mensuration_3d_solids_surface_area_volume_cuboid_surface_area_volume.png",
      "title": "mathematics_mensuration_3d_solids_surface_area_volume_cuboid_surface_area_volume"
    },
    {
      "src": "assets/diagrams/mathematics/mensuration/mathematics_mensuration_3d_solids_surface_area_volume_cylinder_surface_area_volume.png",
      "title": "mathematics_mensuration_3d_solids_surface_area_volume_cylinder_surface_area_volume"
    },
    {
      "src": "assets/diagrams/mathematics/mensuration/surface-area-volume.png",
      "title": "surface-area-volume"
    }
  ],
  "syl-numerical-speed": [
    {
      "src": "assets/diagrams/mathematics/numerical-aptitude/syl-numerical-speed.png",
      "title": "syl-numerical-speed"
    }
  ],
  "syl-probability": [
    {
      "src": "assets/diagrams/mathematics/probability-statistics/syl-probability.png",
      "title": "syl-probability"
    },
    {
      "src": "assets/diagrams/mathematics/probability_statistics/mathematics_probability_statistics_probability_theory_bayes_theorem_probability_tree_diagram.png",
      "title": "mathematics_probability_statistics_probability_theory_bayes_theorem_probability_tree_diagram"
    },
    {
      "src": "assets/diagrams/mathematics/probability_statistics/mathematics_probability_statistics_probability_theory_bayes_theorem_venn_diagram_set_operations.png",
      "title": "mathematics_probability_statistics_probability_theory_bayes_theorem_venn_diagram_set_operations"
    }
  ],
  "complex-numbers": [
    {
      "src": "assets/diagrams/mathematics/real_numbers/evaluating_statements_about_negative_real_numbers.png",
      "title": "evaluating_statements_about_negative_real_numbers"
    }
  ],
  "central-tendency": [
    {
      "src": "assets/diagrams/mathematics/statistics-probability/central-tendency.png",
      "title": "central-tendency"
    }
  ],
  "trig-identities": [
    {
      "src": "assets/diagrams/mathematics/trigonometry/mathematics_trigonometry_trigonometric_identities_values_angle_of_depression.png",
      "title": "mathematics_trigonometry_trigonometric_identities_values_angle_of_depression"
    },
    {
      "src": "assets/diagrams/mathematics/trigonometry/mathematics_trigonometry_trigonometric_identities_values_angle_of_elevation.png",
      "title": "mathematics_trigonometry_trigonometric_identities_values_angle_of_elevation"
    },
    {
      "src": "assets/diagrams/mathematics/trigonometry/mathematics_trigonometry_trigonometric_identities_values_pi_unit_circle.png",
      "title": "mathematics_trigonometry_trigonometric_identities_values_pi_unit_circle"
    },
    {
      "src": "assets/diagrams/mathematics/trigonometry/mathematics_trigonometry_trigonometric_identities_values_trig_ratios_table.png",
      "title": "mathematics_trigonometry_trigonometric_identities_values_trig_ratios_table"
    },
    {
      "src": "assets/diagrams/mathematics/trigonometry/trig-identities.png",
      "title": "trig-identities"
    }
  ],
  "physics-electricity-magnetism": [
    {
      "src": "assets/diagrams/physics/electricity-magnetism/physics-electricity-magnetism.png",
      "title": "physics-electricity-magnetism"
    },
    {
      "src": "assets/diagrams/physics/electricity_magnetism/physics_electricity_magnetism_electricity_circuits_magnetism_dc_electric_motor.png",
      "title": "physics_electricity_magnetism_electricity_circuits_magnetism_dc_electric_motor"
    },
    {
      "src": "assets/diagrams/physics/electricity_magnetism/physics_electricity_magnetism_electricity_circuits_magnetism_electrical_distribution_system.png",
      "title": "physics_electricity_magnetism_electricity_circuits_magnetism_electrical_distribution_system"
    },
    {
      "src": "assets/diagrams/physics/electricity_magnetism/physics_electricity_magnetism_electricity_circuits_magnetism_series_parallel_circuits.png",
      "title": "physics_electricity_magnetism_electricity_circuits_magnetism_series_parallel_circuits"
    },
    {
      "src": "assets/diagrams/physics/electricity_magnetism/physics_electricity_magnetism_electricity_circuits_magnetism_transformer_circuit_diagram.png",
      "title": "physics_electricity_magnetism_electricity_circuits_magnetism_transformer_circuit_diagram"
    }
  ],
  "syl-exercises": [
    {
      "src": "assets/diagrams/physics/energy-gravitation/syl-exercises.png",
      "title": "syl-exercises"
    },
    {
      "src": "assets/diagrams/physics/energy_gravitation/physics_energy_gravitation_work_power_energy_gravitation_classes_of_levers.png",
      "title": "physics_energy_gravitation_work_power_energy_gravitation_classes_of_levers"
    },
    {
      "src": "assets/diagrams/physics/energy_gravitation/physics_energy_gravitation_work_power_energy_gravitation_pulley_system.png",
      "title": "physics_energy_gravitation_work_power_energy_gravitation_pulley_system"
    },
    {
      "src": "assets/diagrams/physics/energy_gravitation/physics_energy_gravitation_work_power_energy_gravitation_types_of_pulleys.png",
      "title": "physics_energy_gravitation_work_power_energy_gravitation_types_of_pulleys"
    },
    {
      "src": "assets/diagrams/physics/energy_gravitation/physics_energy_gravitation_work_power_energy_gravitation_wheel_and_axle.png",
      "title": "physics_energy_gravitation_work_power_energy_gravitation_wheel_and_axle"
    }
  ],
  "physics-heat": [
    {
      "src": "assets/diagrams/physics/heat-thermodynamics/physics-heat.png",
      "title": "physics-heat"
    },
    {
      "src": "assets/diagrams/physics/heat_thermodynamics/physics_heat_thermodynamics_thermodynamics_heat_transfer_methods_of_heat_transfer.png",
      "title": "physics_heat_thermodynamics_thermodynamics_heat_transfer_methods_of_heat_transfer"
    },
    {
      "src": "assets/diagrams/physics/heat_thermodynamics/physics_heat_thermodynamics_thermodynamics_heat_transfer_thermal_expansion_kinetic.png",
      "title": "physics_heat_thermodynamics_thermodynamics_heat_transfer_thermal_expansion_kinetic"
    }
  ],
  "newtons-laws": [
    {
      "src": "assets/diagrams/physics/mechanics-motion/newtons-laws.png",
      "title": "newtons-laws"
    },
    {
      "src": "assets/diagrams/physics/mechanics_motion/physics_mechanics_motion_newton_s_laws_of_motion_free_body_diagram.png",
      "title": "physics_mechanics_motion_newton_s_laws_of_motion_free_body_diagram"
    },
    {
      "src": "assets/diagrams/physics/mechanics_motion/physics_mechanics_motion_newton_s_laws_of_motion_inclined_plane_forces.png",
      "title": "physics_mechanics_motion_newton_s_laws_of_motion_inclined_plane_forces"
    },
    {
      "src": "assets/diagrams/physics/mechanics_motion/physics_mechanics_motion_newton_s_laws_of_motion_parallelogram_law_forces.png",
      "title": "physics_mechanics_motion_newton_s_laws_of_motion_parallelogram_law_forces"
    },
    {
      "src": "assets/diagrams/physics/mechanics_motion/physics_mechanics_motion_newton_s_laws_of_motion_projectile_motion_diagram.png",
      "title": "physics_mechanics_motion_newton_s_laws_of_motion_projectile_motion_diagram"
    }
  ],
  "physics-nuclear-basics": [
    {
      "src": "assets/diagrams/physics/modern-physics-units/physics-nuclear-basics.png",
      "title": "physics-nuclear-basics"
    },
    {
      "src": "assets/diagrams/physics/modern_physics_units/physics_modern_physics_units_nuclear_physics_radioactivity_bohrs_atomic_model.png",
      "title": "physics_modern_physics_units_nuclear_physics_radioactivity_bohrs_atomic_model"
    },
    {
      "src": "assets/diagrams/physics/modern_physics_units/physics_modern_physics_units_nuclear_physics_radioactivity_evolution_of_atomic_models.png",
      "title": "physics_modern_physics_units_nuclear_physics_radioactivity_evolution_of_atomic_models"
    },
    {
      "src": "assets/diagrams/physics/modern_physics_units/physics_modern_physics_units_nuclear_physics_radioactivity_fission_and_fusion.png",
      "title": "physics_modern_physics_units_nuclear_physics_radioactivity_fission_and_fusion"
    },
    {
      "src": "assets/diagrams/physics/modern_physics_units/physics_modern_physics_units_nuclear_physics_radioactivity_structure_of_atom.png",
      "title": "physics_modern_physics_units_nuclear_physics_radioactivity_structure_of_atom"
    }
  ],
  "physics-units-everyday": [
    {
      "src": "assets/diagrams/physics/modern-physics-units/physics-units-everyday.png",
      "title": "physics-units-everyday"
    }
  ],
  "reflection-refraction": [
    {
      "src": "assets/diagrams/physics/optics-light/reflection-refraction.png",
      "title": "reflection-refraction"
    },
    {
      "src": "assets/diagrams/physics/optics_light/physics_optics_light_reflection_refraction_lenses_concave_mirror_object_inside_focus.png",
      "title": "physics_optics_light_reflection_refraction_lenses_concave_mirror_object_inside_focus"
    },
    {
      "src": "assets/diagrams/physics/optics_light/physics_optics_light_reflection_refraction_lenses_convex_concave_lenses.png",
      "title": "physics_optics_light_reflection_refraction_lenses_convex_concave_lenses"
    },
    {
      "src": "assets/diagrams/physics/optics_light/physics_optics_light_reflection_refraction_lenses_convex_mirror_ray_diagram.png",
      "title": "physics_optics_light_reflection_refraction_lenses_convex_mirror_ray_diagram"
    },
    {
      "src": "assets/diagrams/physics/optics_light/physics_optics_light_reflection_refraction_lenses_hypermetropia_eye_correction.png",
      "title": "physics_optics_light_reflection_refraction_lenses_hypermetropia_eye_correction"
    }
  ],
  "physics-em-waves": [
    {
      "src": "assets/diagrams/physics/waves-acoustics/physics-em-waves.png",
      "title": "physics-em-waves"
    }
  ],
  "constitutional-bodies": [
    {
      "src": "assets/diagrams/polity/advanced-polity-structures-bodies/constitutional-bodies.png",
      "title": "constitutional-bodies"
    },
    {
      "src": "assets/diagrams/polity/advanced_polity_structures_bodies/polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_comptroller_auditor_general_cag.png",
      "title": "polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_comptroller_auditor_general_cag"
    },
    {
      "src": "assets/diagrams/polity/advanced_polity_structures_bodies/polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_constitutional_bodies_articles.png",
      "title": "polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_constitutional_bodies_articles"
    },
    {
      "src": "assets/diagrams/polity/advanced_polity_structures_bodies/polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_finance_commission.png",
      "title": "polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_finance_commission"
    },
    {
      "src": "assets/diagrams/polity/advanced_polity_structures_bodies/polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_upsc_structure_composition.png",
      "title": "polity_advanced_polity_structures_bodies_constitutional_non_constitutional_bodies_upsc_structure_composition"
    }
  ],
  "positions-tenures": [
    {
      "src": "assets/diagrams/polity/advanced-polity-structures-bodies/positions-tenures.png",
      "title": "positions-tenures"
    }
  ],
  "president": [
    {
      "src": "assets/diagrams/polity/advanced_polity_structures_bodies/polity_advanced_polity_structures_bodies_elections_appointments_terms_of_office_vice_president_election.png",
      "title": "polity_advanced_polity_structures_bodies_elections_appointments_terms_of_office_vice_president_election"
    }
  ],
  "dpsp": [
    {
      "src": "assets/diagrams/polity/constitutional-framework/dpsp.png",
      "title": "dpsp"
    },
    {
      "src": "assets/diagrams/polity/constitutional_framework/polity_constitutional_framework_dpsp_fundamental_duties_art_36_51a_fundamental_duties_article_51a.png",
      "title": "polity_constitutional_framework_dpsp_fundamental_duties_art_36_51a_fundamental_duties_article_51a"
    }
  ],
  "fundamental-rights": [
    {
      "src": "assets/diagrams/polity/constitutional-framework/fundamental-rights.png",
      "title": "fundamental-rights"
    },
    {
      "src": "assets/diagrams/polity/constitutional_framework/polity_constitutional_framework_fundamental_rights_art_12_35_constitution_fundamental_rights.png",
      "title": "polity_constitutional_framework_fundamental_rights_art_12_35_constitution_fundamental_rights"
    }
  ],
  "preamble": [
    {
      "src": "assets/diagrams/polity/constitutional-framework/preamble.png",
      "title": "preamble"
    },
    {
      "src": "assets/diagrams/polity/constitutional_framework/polity_constitutional_framework_preamble_sources_preamble_constitution_india.png",
      "title": "polity_constitutional_framework_preamble_sources_preamble_constitution_india"
    }
  ],
  "important-articles": [
    {
      "src": "assets/diagrams/polity/constitutional_definitions/definition_of__state__under_article_12.png",
      "title": "definition_of__state__under_article_12"
    }
  ],
  "amendments-parts": [
    {
      "src": "assets/diagrams/polity/english_grammar/parts_of_speech_identification_decision_tree.png",
      "title": "parts_of_speech_identification_decision_tree"
    }
  ],
  "polity-rpa": [
    {
      "src": "assets/diagrams/polity/federal-structure-election-law/polity-rpa.png",
      "title": "polity-rpa"
    }
  ],
  "polity-federal-structure": [
    {
      "src": "assets/diagrams/polity/federal_structure_election_law/polity_federal_structure_election_law_representation_of_people_act_election_commission_types_of_elections.png",
      "title": "polity_federal_structure_election_law_representation_of_people_act_election_commission_types_of_elections"
    },
    {
      "src": "assets/diagrams/polity/rajya_sabha_composition/rajya_sabha_seats_by_state.png",
      "title": "rajya_sabha_seats_by_state"
    }
  ],
  "parliament": [
    {
      "src": "assets/diagrams/polity/parliamentary_procedure/parliamentary_language_permission_flow.png",
      "title": "parliamentary_language_permission_flow"
    },
    {
      "src": "assets/diagrams/polity/parliamentary_rules/parliamentary_language_procedure.png",
      "title": "parliamentary_language_procedure"
    },
    {
      "src": "assets/diagrams/polity/union-government/parliament.png",
      "title": "parliament"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_parliament_of_india_art_79_122_legislative_process_india.png",
      "title": "polity_union_government_parliament_of_india_art_79_122_legislative_process_india"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_parliament_of_india_art_79_122_structure_indian_parliament.png",
      "title": "polity_union_government_parliament_of_india_art_79_122_structure_indian_parliament"
    }
  ],
  "judiciary": [
    {
      "src": "assets/diagrams/polity/separation_of_powers/separation_of_judiciary_from_executive.png",
      "title": "separation_of_judiciary_from_executive"
    },
    {
      "src": "assets/diagrams/polity/union-government/judiciary.png",
      "title": "judiciary"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_integrated_judiciary_sc_hc_hierarchy_of_courts.png",
      "title": "polity_union_government_integrated_judiciary_sc_hc_hierarchy_of_courts"
    }
  ],
  "goverment-executives": [
    {
      "src": "assets/diagrams/polity/union-government/goverment-executives.png",
      "title": "goverment-executives"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_executives_pm_cm_governor_governor_powers_qualifications.png",
      "title": "polity_union_government_executives_pm_cm_governor_governor_powers_qualifications"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_executives_pm_cm_governor_structure_union_executive.png",
      "title": "polity_union_government_executives_pm_cm_governor_structure_union_executive"
    }
  ],
  "panchayati-raj": [
    {
      "src": "assets/diagrams/polity/union-government/panchayati-raj.png",
      "title": "panchayati-raj"
    },
    {
      "src": "assets/diagrams/polity/union_government/polity_union_government_local_self_govt_panchayati_raj_panchayati_raj_municipal_corps.png",
      "title": "polity_union_government_local_self_govt_panchayati_raj_panchayati_raj_municipal_corps"
    }
  ]
};
