mindmap
  root((Transformation))
    Clause Types
      ::icon(fas fa-check)
      Simple to Compound  FANBOYS
      ::icon(fas fa-check)
      Simple to Complex  Subordinators
      ::icon(fas fa-check)
      Compound to Complex
    Mood & Style
      ::icon(fas fa-check)
      Assertive to Interrogative
      ::icon(fas fa-check)
      Assertive to Exclamatory
    Degrees
      ::icon(fas fa-check)
      Positive: as...as
      ::icon(fas fa-check)
      Comparative: -er than
      ::icon(fas fa-check)
      Superlative: the -est