mindmap
  root((Active & Passive))
    Tense Changes
      ::icon(fas fa-check)
      Simple -> be + V3
      ::icon(fas fa-check)
      Continuous -> being + V3
      ::icon(fas fa-check)
      Perfect -> been + V3
    Special Cases
      ::icon(fas fa-check)
      Imperatives  Let + object + be + V3
      ::icon(fas fa-check)
      Questions  Who -> By whom
      ::icon(fas fa-check)
      Modal verbs  + be + V3