mindmap
  root((Industries))
    Iron & Steel
      ::icon(fas fa-check)
      Jamshedpur
      ::icon(fas fa-check)
      Bhilai
      ::icon(fas fa-check)
      Rourkela
    Textiles
      ::icon(fas fa-check)
      Mumbai
      ::icon(fas fa-check)
      Ahmedabad
      ::icon(fas fa-check)
      Coimbatore
    Corridors
      ::icon(fas fa-check)
      DMIC
      ::icon(fas fa-check)
      CBIC
      ::icon(fas fa-check)
      AKIC
    SEZs
      ::icon(fas fa-check)
      Kandla  first
      ::icon(fas fa-check)
      SEEPZ
      ::icon(fas fa-check)
      Noida