mindmap
  root((Geopolitics))
    India-China LAC
      ::icon(fas fa-check)
      Western  Aksai Chin
      ::icon(fas fa-check)
      Eastern  McMahon
      ::icon(fas fa-check)
      Galwan 2020
    Indo-Pacific
      ::icon(fas fa-check)
      Quad
      ::icon(fas fa-check)
      AUKUS
      ::icon(fas fa-check)
      SAGAR
      ::icon(fas fa-check)
      Malacca Dilemma
    Flashpoints
      ::icon(fas fa-check)
      Siliguri Corridor
      ::icon(fas fa-check)
      LoC
      ::icon(fas fa-check)
      BRI/CPEC
      ::icon(fas fa-check)
      String of Pearls