graph TD
A[India's Indo-Pacific Vision] --> B(Key Policy Instruments)
B --> B1(Strategic Partnership with Japan (2014))
B1 --> B1a(Cooperative Security)
B1 --> B1b(Joint Development of Maritime Domain Awareness (MDA) systems)
B --> B2(Indo-Pacific Oceans Initiative (IPOI, 2019))
B2 --> B2a(Capacity Building)
B2 --> B2b(Maritime Security)
B2 --> B2c(Blue-Economy Cooperation)
B --> B3(Act East Policy (re-oriented 2014))
B3 --> B3a(Deepening Economic Ties)
B3 --> B3b(Deepening Strategic Ties with Southeast Asian Nations)
B3 --> B3c(Underpinning India's "neighbourhood first" approach)