mindmap
  root((Forests & Wetlands))
    Forest Types
      ::icon(fas fa-check)
      Evergreen: >200cm rain
      ::icon(fas fa-check)
      Deciduous: Teak, Sal
      ::icon(fas fa-check)
      Thorn/Scrub: <75cm
      ::icon(fas fa-check)
      Mangrove: coastal/delta
    Ramsar Sites
      ::icon(fas fa-check)
      Chilika  Odisha, 1st
      ::icon(fas fa-check)
      Keoladeo  Rajasthan
      ::icon(fas fa-check)
      Loktak  Manipur
      ::icon(fas fa-check)
      Wular  J&K
    Mangroves
      ::icon(fas fa-check)
      Sundarbans  largest
      ::icon(fas fa-check)
      Sundari tree namesake
      ::icon(fas fa-check)
      Bengal/Andaman/Gujarat
    Wildlife Projects
      ::icon(fas fa-check)
      Project Tiger  1973
      ::icon(fas fa-check)
      54 Tiger Reserves
      ::icon(fas fa-check)
      Project Elephant
      ::icon(fas fa-check)
      Crocodile Project
    Wetlands
      ::icon(fas fa-check)
      Ramsar Convention
      ::icon(fas fa-check)
      Chilika
      ::icon(fas fa-check)
      Keoladeo