mindmap
  root((Service Commands))
    Army  7
      ::icon(fas fa-check)
      Northern: Udhampur
      ::icon(fas fa-check)
      Eastern: Kolkata
      ::icon(fas fa-check)
      Training: Shimla
    Air Force  7
      ::icon(fas fa-check)
      Central: Prayagraj
      ::icon(fas fa-check)
      SW: Gandhinagar
      ::icon(fas fa-check)
      Maintenance: Nagpur
    Navy  3
      ::icon(fas fa-check)
      Western: Mumbai
      ::icon(fas fa-check)
      Eastern: Vizag
      ::icon(fas fa-check)
      Southern: Kochi
    Joint Commands
      ::icon(fas fa-check)
      Andaman: Port Blair
      ::icon(fas fa-check)
      Strategic Forces Command