mindmap
  root((Ranks Equivalence))
    Junior Officers
      ::icon(fas fa-check)
      Lieutenant  Army
      ::icon(fas fa-check)
      Sub-Lieutenant  Navy
      ::icon(fas fa-check)
      Flying Officer  IAF
    Mid-Level
      ::icon(fas fa-check)
      Major = Lt Commander = Sqn Leader
      ::icon(fas fa-check)
      Lt Colonel = Commander = Wing Cdr
    Senior Level
      ::icon(fas fa-check)
      Colonel = Captain = Group Captain
      ::icon(fas fa-check)
      Brigadier = Commodore = Air Comm
    Command Star Ranks
      ::icon(fas fa-check)
      Maj Gen  2 Star
      ::icon(fas fa-check)
      Lt Gen  3 Star
      ::icon(fas fa-check)
      General / Chief  4 Star