const fs = require('fs');
const path = require('path');

const analysisFile = path.join(__dirname, 'exam_focus_analysis.json');
const analysisData = JSON.parse(fs.readFileSync(analysisFile, 'utf8'));

// Consolidate by subject
const consolidated = {};

for (const paperName in analysisData) {
    const paper = analysisData[paperName];
    const topics = paper.topic_analysis;
    
    for (const subject in topics) {
        if (!consolidated[subject]) {
            consolidated[subject] = {
                difficulty: [],
                trend_shifts: [],
                high_yield_areas: new Set()
            };
        }
        
        consolidated[subject].difficulty.push(topics[subject].difficulty);
        consolidated[subject].trend_shifts.push(topics[subject].trend_shift);
        topics[subject].high_yield_areas.forEach(area => consolidated[subject].high_yield_areas.add(area));
    }
}

// Format for output
const outputData = {};
for (const subject in consolidated) {
    outputData[subject] = {
        difficulty: consolidated[subject].difficulty.join(" / "),
        trend_shift: consolidated[subject].trend_shifts.join("<br><br>"),
        high_yield_areas: Array.from(consolidated[subject].high_yield_areas)
    };
}

const injectorScript = `
// Auto-generated by build_injector.js
const EXAM_FOCUS_INSIGHTS = ${JSON.stringify(outputData, null, 2)};

(function injectExamFocus() {
    // Wait for the DOM and data to be fully loaded
    window.addEventListener('DOMContentLoaded', () => {
        if (typeof NOTES_DATABASE === 'undefined') {
            console.warn("NOTES_DATABASE is not defined. Cannot inject exam focus.");
            return;
        }
        
        for (let subject in EXAM_FOCUS_INSIGHTS) {
            // Note: Our keys in json might be 'polity', 'geography', etc.
            // Check if it matches existing keys in NOTES_DATABASE
            if (NOTES_DATABASE[subject]) {
                const data = EXAM_FOCUS_INSIGHTS[subject];
                
                const newChapter = {
                    id: "exam-focus-2026",
                    title: "🔥 Exam Focus & Trends (2025-26)",
                    topics: [
                        {
                            id: "latest-trends",
                            title: "PYQ Analysis & High-Yield",
                            notes: \`
                                <div class="revision-card" style="border: 2px solid #ff4757; padding: 20px; border-radius: 8px; margin-bottom: 20px; background: rgba(255, 71, 87, 0.05);">
                                    <h3 style="color: #ff4757; margin-top: 0;">⚠️ Recent Trend Analysis</h3>
                                    <p style="font-weight: bold; color: var(--text);">Overall Topic Difficulty: \${data.difficulty}</p>
                                    <div style="margin-top: 15px;">
                                        <h4 style="color: var(--accent);">Shift in Trends:</h4>
                                        <p>\${data.trend_shift}</p>
                                    </div>
                                    <div style="margin-top: 15px;">
                                        <h4 style="color: #2ed573;">High Yield Areas (Do Not Skip):</h4>
                                        <ul style="list-style-type: square; padding-left: 20px;">
                                            \${data.high_yield_areas.map(area => \`<li><strong>\${area}</strong></li>\`).join('')}
                                        </ul>
                                    </div>
                                </div>
                            \`,
                            formulas: "Prioritize High Yield topics for the upcoming exam.",
                            mindmap: {
                                root: "Exam Trends 2026",
                                branches: data.high_yield_areas.map(area => ({ title: area, subnodes: [] }))
                            }
                        }
                    ]
                };
                
                // Add to the beginning of the chapters
                NOTES_DATABASE[subject].chapters.unshift(newChapter);
            }
        }
        console.log("🔥 Exam focus insights successfully injected into NOTES_DATABASE!");
    });
})();
`;

fs.writeFileSync(path.join(__dirname, 'exam_focus_injector.js'), injectorScript, 'utf8');
console.log("Created exam_focus_injector.js");
