// =============================================================================
// CURRENT AFFAIRS DATA — SINGLE SOURCE OF TRUTH
// =============================================================================
// HOW TO UPDATE THIS FILE:
//
// EXAM CYCLE STRUCTURE:
//   Cycle 1: April → September  (covers NDA I, CDS I, AFCAT I exams)
//   Cycle 2: October → March    (covers NDA II, CDS II, AFCAT II exams)
//
// The Monthly Feed in the app automatically shows only months within the
// current cycle — no manual filtering needed. After each exam, the UI
// self-refreshes to the next cycle on the following month.
//
// AFTER EACH CDS / NDA / AFCAT EXAM:
//   1. Update CA_META.examCycle to the next upcoming exam (e.g., "NDA I 2027")
//   2. Update CA_META.lastRefreshed to today's date
//   3. Clear CA_VISITS_DATA and re-populate with visits from the NEW cycle only
//   4. Keep CA_FTA_DATA — add new FTAs, mark status changes; old ones stay
//   5. Keep CA_DATES_DATA — only update `theme` fields each year
//
// WHEN AI GETS NEW INFO:
//   - Simply replace the relevant object in the array below
//   - Old entry out, new entry in — renderers pick up changes automatically
//
// STRUCTURE: Each section is a separate exported array/object
// =============================================================================

window.CA_META = {
  examCycle: "CDS II 2026",        // UPDATE AFTER EACH EXAM
  lastRefreshed: "June 2026",      // UPDATE AFTER EACH REFRESH
  coverageFrom: "April 2026",      // Start of current cycle (Apr–Sep cycle)
  coverageTo: "September 2026",    // End of current cycle
  cycleNote: "Exam Cycle: Apr 2026 — Sep 2026 | Covers NDA I, CDS I, AFCAT I 2026",
};

// =============================================================================
// SECTION A: PM VISITS & BILATERAL AGREEMENTS
// UPDATE: Clear and re-populate after each CDS exam cycle
// =============================================================================
window.CA_VISITS_DATA = [
  {
    visit: "Exercise PRAGATI 2026",
    period: "May 2026",
    purpose: "Multinational exercise hosted by the Indian Army at Umroi, Meghalaya.",
    deals: "Involved over 400 personnel from 12 friendly nations, focusing on counter-terrorism and tactical operations in semi-mountainous and jungle terrain."
  },
  {
    visit: "Exercise KHAAN QUEST 2026",
    period: "June-July 2026",
    purpose: "Multilateral peacekeeping exercise in Ulaanbaatar, Mongolia.",
    deals: "Indian Army contingent participated alongside 17 other nations to refine peacekeeping skills under the UN Charter and boost interoperability."
  },
  {
    visit: "DRDO Long Range Land Attack Cruise Missile (LRLACM) Test",
    period: "June 2026",
    purpose: "Successful flight test from Dr. APJ Abdul Kalam Island, Odisha.",
    deals: "Indigenously developed missile featuring terrain-following and waypoint navigation capabilities, with an estimated range of 1,000–1,500 km."
  },
  {
    visit: "DRDO Multi-Layered Ballistic Missile Defence (BMD) Test",
    period: "June 2026",
    purpose: "Successful consecutive flight tests of AD-1 and AD-2 interceptors.",
    deals: "Demonstrated a multi-layered BMD system capable of neutralizing threats ranging up to Intercontinental Ballistic Missiles (ICBMs) across endo and exo-atmospheric ranges."
  },
  {
    visit: "DRDO Naval Anti-Ship Missile-Medium Range (NASM-MR) Test",
    period: "June 2026",
    purpose: "Maiden flight test of the new maritime strike missile.",
    deals: "Designed for maritime strike operations, featuring a range of approximately 300 km, sea-skimming capabilities, and advanced terminal guidance."
  },
  {
    visit: "PM Modi's State Visit to Indonesia",
    period: "July 2026",
    purpose: "State visit at the invitation of President Prabowo Subianto.",
    deals: "Reaffirmed the Comprehensive Strategic Partnership. Discussions focused on regional security, trade, and cultural ties, including a visit to the Prambanan Temple complex."
  },
  {
    visit: "Japanese PM Sanae Takaichi to India",
    period: "July 2026",
    purpose: "16th India-Japan Annual Summit.",
    deals: "Signed multiple agreements enhancing defence and security cooperation, economic partnership (AI, semiconductors, green energy), and reaffirmed commitment to a Free and Open Indo-Pacific (FOIP)."
  },
  {
    visit: "BEL Artillery Fuses Contract",
    period: "June 2026",
    purpose: "Rs 5,336 crore deal for electronic fuses for artillery guns.",
    deals: "Massive boost to Make in India and Atmanirbhar Bharat in defence manufacturing. Reduces import dependency for critical ammunition components.",
  },
  {
    visit: "Indo-French Naval Exercise 'Varuna'",
    period: "June 2026",
    purpose: "21st edition bilateral exercise in the Arabian Sea.",
    deals: "Focus on advanced anti-submarine warfare (ASW), air defence exercises, and interoperability to secure critical sea lanes in the Indian Ocean Region.",
  },
  {
    visit: "Akash-NG Missile Test",
    period: "June 2026",
    purpose: "Successful flight test by DRDO from ITR Odisha.",
    deals: "Validates the next-generation surface-to-air missile with an active electronically scanned array (AESA) radar. Enhances Indian Air Force's intercept capabilities against agile aerial threats.",
  },
  {
    visit: "Indo-US Joint Special Forces Exercise 'Vajra Prahar'",
    period: "April 2026",
    purpose: "15th edition bilateral exercise at Special Forces Training School (SFTS), Bakloh.",
    deals: "Focused on counter-terrorism operations, cross-border infiltration tactics, and special helicopter-borne operations. Enhances strategic partnership in the Indo-Pacific.",
  },
  {
    visit: "DefConnect 2026 & iDEX Expansion",
    period: "April 2026",
    purpose: "Ministry of Defence launch of ADITI scheme (Acing Development of Innovative Technologies with iDEX).",
    deals: "Rs 750 crore allocated for startups to develop niche military technologies, including swarm drones, secure quantum communications, and AI-based surveillance.",
  },
  {
    visit: "BrahMos Supersonic Cruise Missile Export to Philippines",
    period: "May 2026",
    purpose: "First batch of BrahMos missiles delivered to the Philippine Marine Corps.",
    deals: "Historic $375 million deal marking India's biggest defence export. Boosts India's image as a reliable defence exporter and strengthens deterrence in the South China Sea.",
  },
  {
    visit: "Commissioning of INS Jatayu",
    period: "May 2026",
    purpose: "New naval base commissioned at Minicoy Island, Lakshadweep.",
    deals: "Strategic base to monitor commercial shipping and secure sea lines of communication in the western Indian Ocean, countering the Maldives' shifting geopolitical stance.",
  },

  {
    visit: "French President Emmanuel Macron to India",
    period: "Jan 2026",
    purpose: "Republic Day Chief Guest & Bilateral Summit.",
    deals: "Defence Industrial Roadmap: Co-designing and co-production of military hardware (advanced helicopter and combat aircraft engines), space launch partnerships, and a new consulate in Marseille.",
  },
  {
    visit: "PM Modi to Abu Dhabi, UAE",
    period: "Feb 2026",
    purpose: "Strategic Bilateral Summit & CEPA Review.",
    deals: "Comprehensive Economic Partnership Agreement (CEPA) Review: Strengthening defence ties, joint naval exercises in the Arabian Sea, UPI expansion across UAE, and maritime security partnerships.",
  },
  {
    visit: "PM Modi to Europe (Germany, Denmark, France)",
    period: "Mid 2026",
    purpose: "India-Nordic Summit & Key Bilaterals.",
    deals: "Indo-Pacific Security & Defence Tech: Enhancing strategic autonomy, boosting Make in India in defence, and maritime cooperation in the Indian Ocean Region.",
  },
  {
    visit: "PM Modi to France and Slovak Republic",
    period: "June 2026",
    purpose: "52nd G7 Summit (Outreach) & Slovakia First State Visit.",
    deals: "Co-inauguration of the 'Bharat Innovates' event in Nice (tech partnerships); bilateral agreements in Bratislava on semiconductor supply chains, renewable energy, and cyber security.",
  },
];

// =============================================================================
// SECTION B: TRADE DEALS & FREE TRADE AGREEMENTS (FTAs)
// UPDATE: Add new FTAs as concluded; replace entries once terms are finalised
// =============================================================================
window.CA_FTA_DATA = [
  {
    deal: "India-EU Free Trade Agreement (FTA) — 'Mother of All Deals'",
    status: "Under Negotiation (resumed 2023, active rounds 2025-26)",
    scope: "Comprehensive trade pact covering goods, services, investments, and GI protections. EU is India's largest trading partner (~EUR 124 billion trade). Key issues: market access for Indian pharma and IT, EU concerns on IPR and data protection.",
    significance: "Strategically critical for India's manufacturing ambitions and Europe's supply-chain de-risking from China.",
  },
  {
    deal: "India-UK Free Trade Agreement (FTA)",
    status: "Concluded & Ratified (May 2025)",
    scope: "India's most significant FTA in years — covering tariff reductions on 99% of UK exports to India and 90% of Indian goods to UK. Key gains: Scotch whisky & cars duty cuts; India gains easier access for textiles, garments, and IT professionals.",
    significance: "First major Western FTA concluded by India; strategic pivot in post-Brexit UK foreign policy.",
  },
  {
    deal: "India-GCC (Gulf Cooperation Council) FTA",
    status: "Under Negotiation (resumed 2024)",
    scope: "Covers 6 Gulf nations (Saudi Arabia, UAE, Qatar, Kuwait, Bahrain, Oman). Focus areas: energy, petrochemicals, logistics, and digital services. UAE already has a separate CEPA with India (2022).",
    significance: "Gulf region accounts for ~18% of India's total trade and hosts 9 million Indian diaspora.",
  },
  {
    deal: "India-Canada Comprehensive Economic Partnership Agreement (CEPA)",
    status: "Negotiations Suspended (pending diplomatic thaw post-2023 Nijjar crisis)",
    scope: "Covering goods, services, investments. Canada is a key source of pulses, fertilizers, and potash for India. Resumption contingent on bilateral diplomatic normalization.",
    significance: "Highlights how geopolitics directly impacts trade negotiations.",
  },
  {
    deal: "India-ASEAN FTA — Review & Upgrade",
    status: "Review Underway (2024-2026)",
    scope: "Original FTA (2010) led to trade deficit widening; review aims to rebalance — tighter rules of origin, digital trade chapter, and services liberalization.",
    significance: "ASEAN is India's 4th largest trading partner; Act East Policy cornerstone.",
  },
  {
    deal: "India-Australia Economic Cooperation & Trade Agreement (ECTA)",
    status: "In Force (December 2022); Upgraded CECA under negotiation",
    scope: "Interim deal covers 85%+ of trade lines. Comprehensive CECA (Comprehensive Economic Cooperation Agreement) to also cover services and investment.",
    significance: "Part of Quad strategic alignment; supports critical minerals (lithium, cobalt) supply chain for India.",
  },
  {
    deal: "India-Sri Lanka ETCA (Economic and Technology Cooperation Agreement)",
    status: "Negotiations Ongoing (2024-26)",
    scope: "Builds on existing FTA (2000); new ETCA to add services, digital trade, and investment. India is Sri Lanka's largest trading partner.",
    significance: "Critical for India's neighbourhood-first policy and strategic depth in the Indian Ocean.",
  },
];

// =============================================================================
// SECTION C: IMPORTANT DATES & THEMES
// UPDATE: Only update the `theme` field each year — dates and significance stay permanent
// =============================================================================
window.CA_DATES_DATA = [
  // --- JANUARY ---
  { date: "Jan 9",  name: "Pravasi Bharatiya Divas", theme: "\"Reliable Partners for India's Progress in Amrit Kaal\"", significance: "Marks the return of Mahatma Gandhi from South Africa to Mumbai in 1915, honoring the contribution of the overseas Indian community." , detailedSignificance: "1. Pravasi Bharatiya Divas is celebrated on 9th January to mark the return of Mahatma Gandhi from South Africa to Ahmedabad in 1915.\n2. Mahatma Gandhi is considered the greatest 'Pravasi' who led India's freedom struggle and changed the course of national history.\n3. The day was established in 2003 under the Prime Ministership of Atal Bihari Vajpayee.\n4. It aims to recognize and honor the contributions of the overseas Indian community (NRIs and PIOs) to the development of India.\n5. In CDS and NDA exams, questions are frequently asked about Mahatma Gandhi's early returns and regional satyagrahas of 1917-18.\n6. The Ministry of External Affairs organizes biennial conventions to foster global networking among the Indian diaspora.\n7. During the event, the prestigious Pravasi Bharatiya Samman Awards are conferred by the President of India.\n8. It highlights India's soft power, global influence, and the strategic role of remittances in the Indian economy.\n9. For defence aspirants, understanding diaspora diplomacy is critical for topics related to international relations and geopolitics.\n10. The event reinforces connections between overseas Indians and their heritage, promoting collaborative growth and investments." },
  { date: "Jan 12", name: "National Youth Day", theme: "\"It's all in the mind\"", significance: "Birth anniversary of Swami Vivekananda, celebrating youth leadership and nation-building." , detailedSignificance: "1. National Youth Day is observed on 12th January to commemorate the birth anniversary of Swami Vivekananda.\n2. Swami Vivekananda was a great social reformer, philosopher, and disciple of Sri Ramakrishna Paramahansa.\n3. He famously represented India and Hinduism at the Parliament of the World's Religions in Chicago in 1893.\n4. His teachings emphasize physical strength, moral courage, spiritual growth, and dedication to the motherland.\n5. In defence exams, his quotes and life events are often asked in General Knowledge and English essays.\n6. The day was declared by the Government of India in 1984 and has been celebrated annually since 1985.\n7. It aims to inspire the youth of India to channel their energy towards national development and unity.\n8. Youth festivals, seminars, and speech competitions are organized across schools and colleges nationwide.\n9. Swami Vivekananda's message 'Arise, awake, and stop not till the goal is reached' serves as a beacon for defence aspirants.\n10. The celebration focuses on character-building and fostering leadership qualities among the future leaders of the nation." },
  { date: "Jan 15", name: "Indian Army Day", theme: "\"In Service of the Nation\"", significance: "Honors the taking over of the Indian Army by Field Marshal K.M. Cariappa in 1949." , detailedSignificance: "1. Indian Army Day is celebrated on 15th January every year in recognition of Field Marshal K. M. Cariappa.\n2. On this day in 1949, he took over as the first Commander-in-Chief of the Indian Army from General Sir Francis Butcher.\n3. This transition marked the formal transfer of military authority from British command to independent India.\n4. The day honors the supreme sacrifices made by soldiers in protecting the nation's borders, peace, and security.\n5. Defence exams (NDA, CDS, AFCAT) heavily test the history, commands, and gallantry awards of the Indian Armed Forces.\n6. Parades, tactical drills, and exhibitions of advanced weaponry are organized at Delhi Cantonment and other command headquarters.\n7. The Param Vir Chakra, Maha Vir Chakra, and Vir Chakra awards are prominently highlighted on this occasion.\n8. It showcases the operational readiness, modernization, and indigenous weapon integrations of the army.\n9. Aspiring officers learn about the core values of the Indian Army: service before self, honor, and courage under fire.\n10. Tribute is paid to martyrs at the National War Memorial, reminding the nation of the high price of freedom." },
  { date: "Jan 25", name: "National Voters' Day", theme: "\"Nothing Like Voting, I Vote For Sure\"", significance: "Marks the foundation day of the Election Commission of India (1950) to enhance electoral participation." , detailedSignificance: "1. National Voters' Day is celebrated on 25th January to mark the foundation day of the Election Commission of India.\n2. The Election Commission of India was established on this day in 1950 as a constitutional body under Article 324.\n3. The day was initiated in 2011 by the Ministry of Law and Justice to increase voter enrollment, especially among the youth.\n4. It aims to raise awareness about the importance of voting and maximizing enrollment in the democratic process.\n5. Polity questions in CDS and NDA exams frequently focus on the Election Commission, voter eligibility, and electoral reforms.\n6. Voters are reminded of their democratic rights and responsibilities, promoting ethical and informed voting.\n7. The National Awards for Best Electoral Practices are presented to state and district-level officers for outstanding poll conduct.\n8. New voters (18+) are handed their Elector Photo Identity Cards (EPIC) at special functions held across the country.\n9. The day reinforces the democratic values of equality, inclusivity, and the power of adult franchise.\n10. Active participation in elections is highlighted as a fundamental pillar of national governance and progress." },
  { date: "Jan 26", name: "Republic Day", theme: "\"Viksit Bharat\" (Developed India)", significance: "Marks the adoption of the Constitution of India in 1950." , detailedSignificance: "1. Republic Day is celebrated on 26th January to mark the day when the Constitution of India came into effect in 1950.\n2. Although India gained independence in 1947, it remained a Dominion under the British Crown until the adoption of the Constitution.\n3. The Constituent Assembly, led by Dr. B. R. Ambedkar, drafted the document over a period of 2 years, 11 months, and 17 days.\n4. The date 26th January was chosen to honor the Declaration of Purna Swaraj (Complete Independence) by the INC in 1930.\n5. In defence exams, constitution-making, key amendments, and schedules are major focus areas in the polity section.\n6. The grand parade on Kartavya Path showcases India's military might, cultural diversity, and technological advancements.\n7. The President of India, who is the Supreme Commander of the Armed Forces, takes the salute during the parade.\n8. Gallantry medals (Ashoka Chakra, Kirti Chakra) are awarded to brave soldiers and citizens by the President on this day.\n9. A foreign head of state is traditionally invited as the Chief Guest, reflecting India's diplomatic priorities.\n10. The celebrations conclude with the Beating Retreat ceremony on 29th January, symbolizing the end of Republic Day events." },
  // --- FEBRUARY ---
  { date: "Feb 1",  name: "Indian Coast Guard Day", theme: "-", significance: "Commemorates the establishment of the Coast Guard in 1977 to protect maritime interests.", detailedSignificance: "1. Indian Coast Guard Day is celebrated on 1st February to mark the foundation of this maritime law enforcement force.\n2. The Indian Coast Guard (ICG) was formally established on this day in 1977 under the Coast Guard Act, 1978.\n3. It operates under the Ministry of Defence, working in close coordination with the Indian Navy and Fisheries Department.\n4. The ICG is responsible for protecting India's Exclusive Economic Zone (EEZ) and preventing maritime smuggling.\n5. Defence aspirants must study the role of ICG in coastal security, search and rescue (SAR), and marine pollution control.\n6. ICG plays a critical role in preventing illegal fishing, safeguarding offshore assets, and assisting during cyclones.\n7. Over the years, the force has grown to become the fourth largest coast guard in the world with state-of-the-art ships and aircraft.\n8. The day celebrates the professionalism and dedication of the coast guard personnel under the motto 'Vayam Rakshamah' (We Protect).\n9. Special seminars, community outreach programs, and maritime security demonstrations are held on this day.\n10. It highlights the strategic importance of maritime security in the Indian Ocean Region and the security of sea lanes.", detailedSignificance: "1. Indian Coast Guard Day is celebrated on 1st February to mark the foundation of this maritime law enforcement force.\n2. The Indian Coast Guard (ICG) was formally established on this day in 1977 under the Coast Guard Act, 1978.\n3. It operates under the Ministry of Defence, working in close coordination with the Indian Navy and Fisheries Department.\n4. The ICG is responsible for protecting India's Exclusive Economic Zone (EEZ) and preventing maritime smuggling.\n5. Defence aspirants must study the role of ICG in coastal security, search and rescue (SAR), and marine pollution control.\n6. ICG plays a critical role in preventing illegal fishing, safeguarding offshore assets, and assisting during cyclones.\n7. Over the years, the force has grown to become the fourth largest coast guard in the world with state-of-the-art ships and aircraft.\n8. The day celebrates the professionalism and dedication of the coast guard personnel under the motto 'Vayam Rakshamah' (We Protect).\n9. Special seminars, community outreach programs, and maritime security demonstrations are held on this day.\n10. It highlights the strategic importance of maritime security in the Indian Ocean Region and the security of sea lanes." },
  { date: "Feb 2",  name: "World Wetlands Day", theme: "\"Wetlands and Human Wellbeing\"", significance: "Marks the signing of the Ramsar Convention on Wetlands in 1971 to promote wetland conservation." , detailedSignificance: "1. World Wetlands Day is observed on 2nd February to raise global awareness about the vital role of wetlands.\n2. It marks the date of the adoption of the Convention on Wetlands on 2nd February 1971 in the Iranian city of Ramsar.\n3. India became a contracting party to the Ramsar Convention in 1982 and has designated dozens of Ramsar sites.\n4. Wetlands are crucial ecosystems that act as water filters, flood buffers, and hosts to rich biodiversity.\n5. Geography and environment sections in CDS and NDA exams frequently ask about Ramsar sites, wetlands, and ecological conservation.\n6. These habitats are often described as 'Earth's Kidneys' due to their ability to purify water and store carbon.\n7. The day promotes actions for the conservation, restoration, and sustainable management of wetlands worldwide.\n8. Rapid urbanization, pollution, and climate change present major threats to these fragile water bodies.\n9. Special awareness campaigns, bird-watching tours, and clean-up drives are organized at Ramsar sites in India.\n10. Protecting wetlands is essential for global freshwater security, biodiversity preservation, and climate resilience." },
  { date: "Feb 13", name: "World Radio Day", theme: "\"Radio: A century informing, entertaining and educating\"", significance: "Commemorates the anniversary of the first broadcast by United Nations Radio, highlighting radio as a medium for peace." , detailedSignificance: "1. World Radio Day is celebrated on 13th February to highlight the importance of radio as a medium of communication.\n2. The day was proclaimed by UNESCO in 2011 and adopted by the United Nations General Assembly in 2012.\n3. It commemorates the anniversary of the establishment of United Nations Radio on 13th February 1946.\n4. Radio remains one of the most accessible, low-cost, and far-reaching communication technologies in the world.\n5. In GK sections, history of broadcasting in India (like All India Radio / Akashvani) and communication tech are tested.\n6. Radio plays a vital role during emergencies, natural disasters, and in providing educational broadcasts to remote areas.\n7. It acts as a platform for democratic discourse, promoting freedom of expression and diverse community voices.\n8. In India, public broadcasts like 'Mann Ki Baat' utilize radio to reach millions of citizens in regional languages.\n9. The day encourages broadcasters, community stations, and listeners to cooperate and improve accessibility.\n10. The celebration underscores radio's enduring legacy and its transition into the digital era via podcasts and online streams." },
  { date: "Feb 20", name: "World Day of Social Justice", theme: "\"Bridging Gaps, Building Alliances\"", significance: "Promotes international efforts in poverty eradication, gender equality, and social justice." , detailedSignificance: "1. World Day of Social Justice is observed on 20th February to promote international efforts in social equality.\n2. It was declared by the United Nations General Assembly in 2007, with the first observance in 2009.\n3. The day focuses on tackling issues like poverty, exclusion, gender inequality, unemployment, and human rights violations.\n4. It emphasizes that social justice is an essential foundation for peaceful and prosperous coexistence within nations.\n5. In NDA/CDS polity and economics, concepts of justice, directive principles, and welfare state structures are highly relevant.\n6. The UN works with member states to create fair trade, decent work opportunities, and social protection floors.\n7. It calls for bridging social gaps, protecting marginalized groups, and ensuring equal access to resources.\n8. In India, constitutional provisions (Articles 14, 15, 38, 39) directly align with the goals of social justice.\n9. Seminars, workshops, and school campaigns are held to educate the public on legal aid and social security rights.\n10. Fostering social justice is presented as critical for global stability, preventing conflict, and sustainable development." },
  { date: "Feb 28", name: "National Science Day", theme: "\"Indigenous Technologies for Viksit Bharat\"", significance: "Marks the discovery of the Raman Effect by Sir C.V. Raman in 1928." , detailedSignificance: "1. National Science Day is celebrated on 28th February to mark the discovery of the Raman Effect by Sir C. V. Raman.\n2. He discovered the inelastic scattering of light on this day in 1928, which won him the Nobel Prize in Physics in 1930.\n3. Sir C. V. Raman was the first Indian and Asian to receive a Nobel Prize in any branch of science.\n4. The day was designated by the Government of India in 1986 on the recommendation of the NCSTC.\n5. Science and physics sections in defence exams regularly feature questions on the Raman Effect, scattering, and optics.\n6. The day aims to popularize science, cultivate a scientific temper, and encourage research among the youth of India.\n7. Science exhibitions, quizzes, and laboratory open-houses are organized in schools, colleges, and national labs.\n8. The National Awards for Science Popularization are presented by the President of India on this occasion.\n9. It highlights the role of science and indigenous technologies in achieving national self-reliance (Atmanirbhar Bharat).\n10. The celebration honors the achievements of Indian scientists and inspires future generations to pursue scientific careers." },
  // --- MARCH ---
  { date: "Mar 3",  name: "World Wildlife Day", theme: "\"Connecting People and Planet: Exploring Digital Innovation in Wildlife Conservation\"", significance: "Dedicated to celebrating and raising awareness of the world's wild fauna and flora." , detailedSignificance: "1. World Wildlife Day is celebrated on 3rd March to celebrate and raise awareness of the world's wild fauna and flora.\n2. It marks the day of the adoption of CITES (Convention on International Trade in Endangered Species) in 1973.\n3. The UN General Assembly proclaimed this day in 2013 to protect endangered species from illegal trade.\n4. CITES is a legally binding treaty that ensures international trade does not threaten the survival of wild species.\n5. Geography and environment sections in defence exams regularly test wildlife sanctuaries, national parks, and CITES classifications.\n6. Poaching, habitat destruction, and illegal wildlife trafficking are highlighted as major threats to global biodiversity.\n7. India's efforts, such as Project Tiger, Project Elephant, and Project Cheetah, are showcased on this day.\n8. The day promotes sustainable development goals (SDGs), specifically Goal 15 (Life on Land) and Goal 14 (Life Below Water).\n9. Global campaigns and photography contests are organized to engage citizens in conservation efforts.\n10. Protecting wildlife is presented as essential for ecological balance, forest regeneration, and human survival." },
  { date: "Mar 8",  name: "International Women's Day", theme: "\"Invest in women: Accelerate progress\"", significance: "Celebrates social, economic, cultural, and political achievements of women worldwide." , detailedSignificance: "1. International Women's Day is celebrated on 8th March to recognize the achievements and rights of women globally.\n2. The day originated from labor movements in North America and Europe during the early 20th century.\n3. It was officially recognized by the United Nations in 1977, promoting gender equality and women's empowerment.\n4. The day focuses on issues like gender pay gaps, equal opportunities, safety, education, and reproductive rights.\n5. Questions on women's rights, landmark legal cases, and female figures in history appear in NDA/CDS GK papers.\n6. It celebrates the path-breaking contributions of women in politics, science, arts, business, and military services.\n7. In the Indian Armed Forces, the day highlights the growing role of female officers in combat support and command positions.\n8. Various social welfare schemes and awards (like the Nari Shakti Puraskar) are announced or presented on this day.\n9. It calls for concerted action to eliminate violence against women and promote inclusivity in decision-making.\n10. Fostering gender equality is celebrated as key to economic prosperity, peace, and sustainable national progress." },
  { date: "Mar 21", name: "International Day of Forests", theme: "\"Forests and Innovation: New Solutions for a Better World\"", significance: "Proclaimed by the UN to celebrate and raise awareness of all types of forests and woodlands." , detailedSignificance: "1. International Day of Forests is observed on 21st March to celebrate and protect all types of forest ecosystems.\n2. It was established by a resolution of the United Nations General Assembly on 28th November 2012.\n3. The day raises awareness about the importance of forests in biodiversity conservation, climate control, and water supply.\n4. Forests cover about 31% of the global land area, acting as critical carbon sinks and supporting millions of livelihoods.\n5. NDA/CDS geography sections test Indian forest reports, types of vegetation, and biosphere reserves.\n6. Deforestation, forest fires, and encroachment are discussed as major threats causing soil erosion and desertification.\n7. Tree-planting campaigns, educational programs, and community forestry workshops are organized globally.\n8. The day highlights the role of tribal communities and indigenous people in preserving forest ecosystems.\n9. Forest conservation is linked to achieving the goals of the Paris Agreement and the UN Decade on Ecosystem Restoration.\n10. Protecting woodlands is emphasized as a necessity to preserve biodiversity and combat global warming." },
  { date: "Mar 22", name: "World Water Day", theme: "\"Water for Peace\"", significance: "Focuses on the critical importance of freshwater and advocating for its sustainable management." , detailedSignificance: "1. World Water Day is held on 22nd March to focus attention on the importance of freshwater and its conservation.\n2. The day was recommended at the 1992 UN Conference on Environment and Development (UNCED) in Rio de Janeiro.\n3. It has been celebrated annually since 1993, advocating for the sustainable management of freshwater resources.\n4. Currently, billions of people worldwide live without access to safe, clean drinking water and sanitation.\n5. In defence exams, water pollution, river basins, dams, and international water treaties are frequently tested topics.\n6. The day supports the achievement of Sustainable Development Goal 6: Water and Sanitation for all by 2030.\n7. It raises awareness about water scarcity, groundwater depletion, and the impact of climate change on water cycles.\n8. In India, programs like the Jal Jeevan Mission and Namami Gange are highlighted during the celebrations.\n9. Public campaigns, school competitions, and water-conservation pledge drives are organized across states.\n10. Efficient water management is projected as vital for food security, energy production, health, and global peace." },
  { date: "Mar 23", name: "World Meteorological Day", theme: "\"At the Frontline of Climate Action\"", significance: "Marks the establishment of the World Meteorological Organization (WMO) in 1950." , detailedSignificance: "1. World Meteorological Day is observed on 23rd March to highlight the contribution of meteorology to safety and welfare.\n2. It commemorates the entry into force of the Convention creating the World Meteorological Organization (WMO) in 1950.\n3. The WMO is a specialized agency of the United Nations focusing on weather, climate, and water resources.\n4. The day showcases the critical role of national meteorological and hydrological services in early warning systems.\n5. General Knowledge sections in NDA and CDS cover weather systems, monsoons, cyclones, and atmospheric layers.\n6. Weather forecasting is essential for disaster management, aviation, agriculture, maritime operations, and military planning.\n7. The day raises awareness about climate change, global warming, and the increasing frequency of extreme weather events.\n8. WMO coordinates global data-sharing, research, and weather monitoring across 193 member states and territories.\n9. Seminars, scientific exhibitions, and meteorological awards are organized at research centres on this day.\n10. Accurate climate and weather services are promoted as key to building resilient societies and sustainable economies." },
  // --- APRIL ---
  { date: "Apr 7",  name: "World Health Day", theme: "\"My health, my right\"", significance: "Promotes global health awareness — marks the foundation of WHO in 1948." , detailedSignificance: "1. World Health Day is celebrated on 7th April to draw attention to important global health priorities.\n2. It marks the anniversary of the founding of the World Health Organization (WMO) on 7th April 1948.\n3. The day has been celebrated since 1950, with a unique theme selected each year by the WHO.\n4. It aims to achieve Universal Health Coverage (UHC), ensuring everyone has access to quality healthcare without financial hardship.\n5. In defence exams, common diseases, vaccines, biology questions, and WHO programs are regular topics of testing.\n6. It focuses on addressing global health challenges like pandemics, mental health, sanitation, and clean water access.\n7. Health promotion campaigns, medical camps, and wellness webinars are organized by governments and NGOs.\n8. The day highlights the critical role of doctors, nurses, and healthcare workers in community welfare.\n9. In India, health initiatives like Ayushman Bharat are promoted to strengthen rural and urban healthcare structures.\n10. Investing in public health systems is emphasized as crucial for national security, economic stability, and human development." },
  { date: "Apr 21", name: "Civil Services Day", theme: "\"Viksit Bharat: Empowering Citizens & Reaching the Last Mile\"", significance: "Marks the historic address of Sardar Vallabhbhai Patel in 1947 to the first batch of civil service officers." , detailedSignificance: "1. Civil Services Day is celebrated on 21st April to appreciate the work of civil servants and renew their dedication.\n2. On this day in 1947, Sardar Vallabhbhai Patel addressed the first batch of Indian Administrative Service officers.\n3. He famously referred to civil servants as the 'Steel Frame of India' during his address at Metcalf House, Delhi.\n4. The first official celebration of Civil Services Day was organized in Vigyan Bhawan in 2006.\n5. Polity sections in CDS and NDA exams cover civil services, UPSC constitutional provisions (Articles 308-323), and reforms.\n6. The day is used by officers to introspect, discuss administrative reforms, and share best practices in governance.\n7. The Prime Minister's Awards for Excellence in Public Administration are presented to districts and central units.\n8. It promotes transparency, efficiency, citizen-centric administration, and reaching the last mile of development.\n9. Civil servants are encouraged to work with dedication to achieve the vision of a developed India (Viksit Bharat).\n10. The event underscores the critical role of administration in implementing government welfare schemes and maintaining order." },
  { date: "Apr 22", name: "World Earth Day", theme: "\"Planet vs. Plastics\"", significance: "Advocates for environmental protection and reducing single-use plastic." , detailedSignificance: "1. World Earth Day is celebrated on 22nd April to demonstrate support for environmental protection.\n2. The first Earth Day was organized in 1970 in the United States by Senator Gaylord Nelson, engaging 20 million citizens.\n3. It led to the creation of the US Environmental Protection Agency and the passage of landmark environmental laws.\n4. Today, Earth Day is coordinated globally by the Earth Day Network, involving over 190 countries.\n5. Geography and ecology questions in NDA/CDS cover global warming, pollution, carbon footprint, and conservation treaties.\n6. The day raises awareness about deforestation, plastic pollution, climate change, and biodiversity loss.\n7. Tree-planting drives, clean-up campaigns, and eco-friendly workshops are organized by communities worldwide.\n8. It advocates for transitioning to renewable energy, reducing waste, and adopting sustainable lifestyles.\n9. Global accords, like the Paris Agreement on climate change, are frequently signed or highlighted on this day.\n10. Protecting the planet is presented as a collective responsibility to secure a healthy future for coming generations." },
  // --- MAY ---
  { date: "May 3",  name: "World Press Freedom Day", theme: "\"A Press for the Planet: Journalism in the Face of the Environmental Crisis\"", significance: "Proclaimed to evaluate press freedom, defend media independence, and pay tribute to journalists." , detailedSignificance: "1. World Press Freedom Day is observed on 3rd May to celebrate the fundamental principles of press freedom.\n2. It was proclaimed by the United Nations General Assembly in 1993, following a recommendation from UNESCO.\n3. The day commemorates the anniversary of the Declaration of Windhoek, a statement of free press principles.\n4. It serves as an occasion to inform citizens of violations of press freedom and remind them of the right to expression.\n5. CDS and NDA polity sections cover Article 19(1)(a) of the Constitution, which guarantees the freedom of speech and expression.\n6. The day pays tribute to journalists who have lost their lives in the line of duty, reporting from conflict zones.\n7. The UNESCO/Guillermo Cano World Press Freedom Prize is awarded to individuals or organizations defending media freedom.\n8. It highlights the role of independent journalism in exposing corruption, holding power accountable, and upholding democracy.\n9. Censorship, media ownership, fake news, and safety of journalists are key topics of discussion on this day.\n10. A free and independent press is celebrated as a cornerstone of transparent, democratic, and just societies." },
  { date: "May 8",  name: "World Red Cross Day", theme: "\"I give for humanity\"", significance: "Celebrates the humanitarian work and principles of the Red Cross and Red Crescent movements." , detailedSignificance: "1. World Red Cross Day is celebrated on 8th May to honor the humanitarian work of the Red Cross and Red Crescent.\n2. It marks the birth anniversary of Henry Dunant, the founder of the International Committee of the Red Cross (ICRC).\n3. Henry Dunant was the recipient of the first-ever Nobel Peace Prize in 1901 for his humanitarian efforts.\n4. The Red Cross provides assistance during armed conflicts, natural disasters, epidemics, and health emergencies.\n5. General Knowledge sections cover the history of international humanitarian law, Geneva Conventions, and world bodies.\n6. The movement operates under seven fundamental principles: humanity, impartiality, neutrality, independence, voluntary service, unity, and universality.\n7. Blood donation drives, first-aid training, and disaster response drills are organized by national societies.\n8. In India, the Indian Red Cross Society (established in 1920) coordinates health and relief services.\n9. The day recognizes the selfless service of millions of volunteers worldwide who assist vulnerable communities.\n10. It promotes international solidarity, peace, and the alleviation of human suffering without discrimination." },
  { date: "May 11", name: "National Technology Day", theme: "\"Sustainable Future for a Developed India\"", significance: "Marks the successful Pokhran-II nuclear tests (Operation Shakti) in 1998." , detailedSignificance: "1. National Technology Day is celebrated on 11th May to mark India's technological advancements and scientific achievements.\n2. On this day in 1998, India successfully conducted the Pokhran-II nuclear tests (Operation Shakti) in Rajasthan.\n3. The tests were led by scientific advisor Dr. A. P. J. Abdul Kalam and Prime Minister Atal Bihari Vajpayee.\n4. It also marks the flight of the first indigenous aircraft, Hansa-3, and the successful test firing of the Trishul missile.\n5. In defence exams, India's missile programs (IGMDP), nuclear doctrine, and defense technologies are major testing areas.\n6. The day was officially declared by Prime Minister Atal Bihari Vajpayee in 1998 to promote scientific temper.\n7. The Ministry of Science and Technology presents national awards to companies and technology innovators.\n8. Science exhibitions, lectures, and technology hackathons are organized in academic and research institutions.\n9. It highlights the role of technology in national security, self-reliance, and socio-economic development.\n10. The celebration inspires students to pursue science and technology careers, contributing to national innovation." },
  { date: "May 21", name: "Anti-Terrorism Day", theme: "-", significance: "Observed to spread the message of peace and humanity, marking the death anniversary of Rajiv Gandhi.", detailedSignificance: "1. Anti-Terrorism Day is observed on 21st May to spread the message of peace, harmony, and humanity.\n2. It marks the death anniversary of former Prime Minister Rajiv Gandhi, who was assassinated on this day in 1991.\n3. He was assassinated during an election rally in Sriperumbudur, Tamil Nadu, by an LTTE suicide bomber.\n4. The day was officially designated by the government to raise awareness about the devastating impact of terrorism.\n5. Security agencies, counter-terror operations (like Operation Blue Star), and national security laws are tested in exams.\n6. Public offices, schools, and colleges take an anti-terrorism pledge to oppose all forms of violence and extremism.\n7. Special seminars and discussions on national security, intelligence sharing, and border protection are organized.\n8. It honors the sacrifices of police, paramilitary, and military personnel who lost their lives fighting terror.\n9. The day highlights the need for international cooperation to combat global terror networks and funding.\n10. Promoting national integration and unity is emphasized as the strongest shield against divisive and extremist forces.", detailedSignificance: "1. Anti-Terrorism Day is observed on 21st May to spread the message of peace, harmony, and humanity.\n2. It marks the death anniversary of former Prime Minister Rajiv Gandhi, who was assassinated on this day in 1991.\n3. He was assassinated during an election rally in Sriperumbudur, Tamil Nadu, by an LTTE suicide bomber.\n4. The day was officially designated by the government to raise awareness about the devastating impact of terrorism.\n5. Security agencies, counter-terror operations (like Operation Blue Star), and national security laws are tested in exams.\n6. Public offices, schools, and colleges take an anti-terrorism pledge to oppose all forms of violence and extremism.\n7. Special seminars and discussions on national security, intelligence sharing, and border protection are organized.\n8. It honors the sacrifices of police, paramilitary, and military personnel who lost their lives fighting terror.\n9. The day highlights the need for international cooperation to combat global terror networks and funding.\n10. Promoting national integration and unity is emphasized as the strongest shield against divisive and extremist forces." },
  { date: "May 22", name: "International Day for Biological Diversity", theme: "\"Be part of the Plan\"", significance: "Promotes biodiversity conservation, sustainable utilization, and fair sharing of genetic resources." , detailedSignificance: "1. International Day for Biological Diversity is celebrated on 22nd May to promote biodiversity conservation.\n2. The day was created by the Second Committee of the UN General Assembly on 29th December 1993.\n3. In 2000, the date was shifted to 22nd May to commemorate the adoption of the Convention on Biological Diversity (CBD) in 1992.\n4. The CBD is a multilateral treaty aimed at conserving biodiversity, sustainable use, and equitable benefit sharing.\n5. Environmental protocols (Cartagena, Nagoya), biodiversity hotspots, and Indian wildlife acts are tested in NDA/CDS.\n6. Biodiversity is crucial for ecosystem services, food security, medicine, agriculture, and economic stability.\n7. Habitat loss, invasive species, overexploitation, and pollution are highlighted as major drivers of biodiversity decline.\n8. Educational campaigns, forest walks, and species-monitoring projects are conducted by environment departments.\n9. India's Biological Diversity Act, 2002, and the role of National Biodiversity Authority (NBA) are showcased on this day.\n10. Conserving biodiversity is presented as vital for climate adaptation and maintaining global ecological balance." },
  { date: "May 29", name: "International Day of UN Peacekeepers", theme: "\"Fit for the future, building better together\"", significance: "Honors military, police, and civilian personnel serving in UN peacekeeping operations worldwide." , detailedSignificance: "1. International Day of UN Peacekeepers is observed on 29th May to honor the service and sacrifice of peacekeepers.\n2. It marks the day when the first UN peacekeeping mission, 'UN Truce Supervision Organization' (UNTSO), began operations in 1948.\n3. The day was established by a UN General Assembly resolution in 2002 to recognize the contribution of peacekeepers.\n4. UN peacekeepers (referred to as Blue Helmets) work in volatile regions to maintain peace, protect civilians, and support political transitions.\n5. Defence exams cover UN bodies, peacekeeping operations, and India's leading role as a troop contributor.\n6. India has historically been one of the largest contributors of military and police personnel to UN missions.\n7. The Dag Hammarskjöld Medal is posthumously awarded to peacekeepers who lost their lives in the line of duty.\n8. The day highlights the challenges of modern peacekeeping, including asymmetrical warfare, local politics, and funding shortages.\n9. Commemorative events and parades are held at UN Headquarters in New York and national military establishments.\n10. India's contribution of the first-ever all-female police unit to a UN mission (Liberia, 2007) is highly celebrated." },
  // --- JUNE ---
  { date: "Jun 5",  name: "World Environment Day", theme: "\"Land restoration, desertification and drought resilience\"", significance: "Promotes awareness and action to protect nature." , detailedSignificance: "1. World Environment Day is celebrated on 5th June to inspire global action for the protection of nature.\n2. It was established by the United Nations General Assembly in 1972 at the Stockholm Conference on the Human Environment.\n3. The first World Environment Day was celebrated in 1974 with the slogan 'Only One Earth'.\n4. It is hosted by a different country each year, which coordinates the official celebrations and selects the theme.\n5. Ecology and geography sections in NDA/CDS cover global summits, carbon credits, and environmental indicators.\n6. The day focuses on tackling major environmental crises like climate change, marine pollution, and wildlife crime.\n7. Tree-planting drives, plastic collection campaigns, and community workshops are organized globally.\n8. It urges governments, industries, and individuals to adopt sustainable green practices and reduce carbon emissions.\n9. In India, policy initiatives like LiFE (Lifestyle for Environment) are promoted to encourage eco-friendly habits.\n10. Restoring ecosystems and conserving resources are presented as essential to ensure a sustainable future." },
  { date: "Jun 21", name: "International Yoga Day", theme: "\"Yoga for Women Empowerment\"", significance: "Global observance to celebrate the ancient Indian practice of Yoga." , detailedSignificance: "1. International Yoga Day is observed on 21st June to promote the global practice of Yoga and its health benefits.\n2. The resolution to establish the day was proposed by PM Narendra Modi at the UN General Assembly in September 2014.\n3. The resolution was adopted with an overwhelming majority, co-sponsored by a record 175 member nations.\n4. The date 21st June was chosen because it is the Summer Solstice, the longest day of the year in the Northern Hemisphere.\n5. General Knowledge sections test the origin of Yoga, classic Indian philosophies, and national health initiatives.\n6. Yoga is recognized as an ancient physical, mental, and spiritual practice that originated in India.\n7. Mass Yoga demonstrations led by the Prime Minister are held at historical and public venues across India.\n8. The World Health Organization (WHO) has integrated Yoga into its global health and wellness strategies.\n9. The day promotes the message of harmony, mindfulness, stress reduction, and holistic physical well-being.\n10. It showcases India's rich cultural heritage, soft power, and contribution to global preventive healthcare." },
  { date: "Jun 29", name: "National Statistics Day", theme: "\"Alignment of State Indicator Framework with National Indicator Framework for Monitoring Sustainable Development Goals\"", significance: "Celebrates the birth anniversary of Professor Prasanta Chandra Mahalanobis, recognizing his role in India's planning." , detailedSignificance: "1. National Statistics Day is celebrated on 29th June to recognize the importance of statistics in planning and development.\n2. It commemorates the birth anniversary of Professor Prasanta Chandra Mahalanobis, the father of modern Indian statistics.\n3. He founded the Indian Statistical Institute (ISI) in Kolkata in 1931 and established the National Sample Survey.\n4. Prof. Mahalanobis designed the second five-year plan of India, which focused on rapid industrialization and heavy industries.\n5. Economics sections in defence exams cover Five-Year Plans, planning commission history, and national income data.\n6. The day was designated by the Government of India in 2007 to popularize statistics among the public and policymakers.\n7. National awards in official statistics are presented to outstanding researchers and statistical officers.\n8. Seminars and panel discussions are organized by the Ministry of Statistics and Programme Implementation (MoSPI).\n9. It highlights the role of reliable data in formulating national policies, monitoring development, and tracking SDGs.\n10. Statistical methods are shown as essential tools for economic planning, census operations, and administrative decision-making." },
  // --- JULY ---
  { date: "Jul 11", name: "World Population Day", theme: "\"Unleashing the power of gender equality: Uplifting the voices of women and girls to unlock our world’s infinite possibilities\"", significance: "Raises global awareness on demographics, population growth, and reproductive health rights." , detailedSignificance: "1. World Population Day is observed on 11th July to focus attention on the urgency and importance of population issues.\n2. The day was established by the Governing Council of the United Nations Development Programme (UNDP) in 1989.\n3. It was inspired by the public interest in 'Five Billion Day' on 11th July 1987, the approximate date when the world's population reached 5 billion.\n4. The day raises awareness about family planning, gender equality, maternal health, and human rights.\n5. Geography and demographics questions in NDA/CDS focus on population density, sex ratio, census data, and demographic transition.\n6. It addresses the challenges of rapid population growth, resource depletion, and aging demographics in developed nations.\n7. Seminars, educational programs, and public debates on reproductive health and resource management are held.\n8. Governments use the day to review national population policies, healthcare access, and social welfare programs.\n9. The day highlights the empowerment of women and girls as key to unlocking demographic dividends.\n10. Balancing population growth with sustainable development is presented as critical for global peace and prosperity." },
  { date: "Jul 26", name: "Kargil Vijay Diwas", theme: "-", significance: "Honors the victory of the Indian Armed Forces in Operation Vijay (1999) and the sacrifices made by soldiers.", detailedSignificance: "1. Kargil Vijay Diwas is celebrated on 26th July to commemorate India's victory in the Kargil War of 1999.\n2. On this day, the Indian Armed Forces successfully recaptured the high outposts in Jammu and Kashmir that had been infiltrated by Pakistani forces.\n3. The military operation launched to evict the infiltrators was codenamed Operation Vijay.\n4. The war was fought at extremely high altitudes in freezing temperatures, displaying extraordinary military tactical skills.\n5. In defence exams, Kargil war history, key peaks (Tiger Hill, Tololing), gallantry award winners, and weapons are tested.\n6. The day honors the supreme sacrifice of 527 Indian soldiers who lost their lives during the two-month conflict.\n7. A grand memorial service is held at the Kargil War Memorial in Drass, attended by the military leadership.\n8. Iconic heroes like Captain Vikram Batra, Lieutenant Manoj Kumar Pandey, and Major Rajesh Adhikari are remembered.\n9. It highlights the importance of mountain warfare capabilities, military intelligence, and tri-service coordination.\n10. The celebrations include lighting of the Kargil Victory Flame and laying wreaths to pay tribute to the martyrs.", detailedSignificance: "1. Kargil Vijay Diwas is celebrated on 26th July to commemorate India's victory in the Kargil War of 1999.\n2. On this day, the Indian Armed Forces successfully recaptured the high outposts in Jammu and Kashmir that had been infiltrated by Pakistani forces.\n3. The military operation launched to evict the infiltrators was codenamed Operation Vijay.\n4. The war was fought at extremely high altitudes in freezing temperatures, displaying extraordinary military tactical skills.\n5. In defence exams, Kargil war history, key peaks (Tiger Hill, Tololing), gallantry award winners, and weapons are tested.\n6. The day honors the supreme sacrifice of 527 Indian soldiers who lost their lives during the two-month conflict.\n7. A grand memorial service is held at the Kargil War Memorial in Drass, attended by the military leadership.\n8. Iconic heroes like Captain Vikram Batra, Lieutenant Manoj Kumar Pandey, and Major Rajesh Adhikari are remembered.\n9. It highlights the importance of mountain warfare capabilities, military intelligence, and tri-service coordination.\n10. The celebrations include lighting of the Kargil Victory Flame and laying wreaths to pay tribute to the martyrs." },
  // --- AUGUST ---
  { date: "Aug 15", name: "Independence Day", theme: "\"Viksit Bharat\"", significance: "Commemorates India's independence from British rule on 15 August 1947." , detailedSignificance: "1. Independence Day is celebrated on 15th August to mark India's freedom from British colonial rule in 1947.\n2. The Indian Independence Act, passed by the UK Parliament in 1947, transferred legislative sovereignty to the Indian Constituent Assembly.\n3. The day marks the partition of British India into two independent dominions: India and Pakistan.\n4. On 15th August 1947, Prime Minister Jawaharlal Nehru raised the Indian national flag above the Lahori Gate of the Red Fort in Delhi.\n5. History sections in NDA/CDS cover the Indian national movement, partition history, and major viceroys.\n6. The Prime Minister delivers a speech from the ramparts of the Red Fort, summarizing national achievements and future goals.\n7. The national flag is hoisted across schools, offices, and residential communities, accompanied by national anthem singing.\n8. Armed forces organize parades, guard of honor ceremonies, and showcase advanced combat platforms.\n9. It honors the struggle and sacrifices of freedom fighters like Mahatma Gandhi, Subhas Chandra Bose, and Bhagat Singh.\n10. The day promotes national unity, patriotic pride, and dedication to the progress of the sovereign republic." },
  { date: "Aug 29", name: "National Sports Day", theme: "\"Sports as an enabler for an inclusive and fit society\"", significance: "Birth anniversary of hockey legend Major Dhyan Chand, promoting sports participation." , detailedSignificance: "1. National Sports Day is celebrated on 29th August to honor the legacy of hockey legend Major Dhyan Chand.\n2. It marks the birth anniversary of Major Dhyan Chand, who won gold medals for India in the 1928, 1932, and 1936 Olympics.\n3. Known as the 'Wizard of Hockey', his exceptional ball control and stickwork remain legendary worldwide.\n4. The day was designated by the Government of India in 2012 to promote sports and physical fitness.\n5. GK sections in defence exams cover sports trophies, major tournaments, Olympic achievements, and sports personalities.\n6. The President of India presents national sports awards (Major Dhyan Chand Khel Ratna, Arjuna Award, Dronacharya Award) on this day.\n7. Fitness campaigns, sports tournaments, and athletic meets are organized in schools and colleges nationwide.\n8. It highlights the role of sports in character-building, team spirit, national integration, and international prestige.\n9. In the military, sports participation is encouraged to maintain high physical fitness, combat readiness, and morale.\n10. The day inspires the youth to pursue active lifestyles and represent the nation in global sports platforms." },
  // --- SEPTEMBER ---
  { date: "Sep 5",  name: "National Teachers' Day", theme: "\"Teachers at the heart of education recovery\"", significance: "Commemorates the birth anniversary of India's second President, Dr. Sarvepalli Radhakrishnan." , detailedSignificance: "1. National Teachers' Day is celebrated on 5th September to honor the contribution of teachers in nation-building.\n2. It commemorates the birth anniversary of Dr. Sarvepalli Radhakrishnan, India's second President and first Vice-President.\n3. Dr. Radhakrishnan was a highly respected philosopher, educationist, diplomat, and recipient of the Bharat Ratna.\n4. The celebration began in 1962 when his students requested to celebrate his birthday, and he suggested honoring teachers instead.\n5. In defence exams, the roles, history, and constitutional provisions related to education (Article 21A, Right to Education) are tested.\n6. The President of India presents the National Awards to Teachers to primary, secondary, and higher secondary educators.\n7. Students organize cultural performances, self-governance days, and express gratitude to their teachers.\n8. It highlights the role of educators in shaping values, knowledge, and career paths of future citizens.\n9. The day emphasizes the need to reform educational standards, support teachers, and ensure inclusive learning.\n10. Celebrating teachers is presented as vital for social progress, scientific advancement, and national development." },
  { date: "Sep 8",  name: "International Literacy Day", theme: "\"Promoting literacy for a world in transition: Building the foundation for sustainable and peaceful societies\"", significance: "Proclaimed by UNESCO to raise awareness of the status of literacy and adult learning globally." , detailedSignificance: "1. International Literacy Day is observed on 8th September to highlight literacy as a matter of dignity and human rights.\n2. The day was proclaimed by UNESCO on 14th October 1966 at the 14th session of UNESCO's General Conference.\n3. It has been celebrated annually since 1967 to advance the literacy agenda towards a more literate society.\n4. Despite progress, millions of youth and adults worldwide still lack basic reading, writing, and numeracy skills.\n5. General Knowledge sections test literacy rates in India (from the 2011 census), education policies, and demographics.\n6. Literacy is key to eradicating poverty, reducing child mortality, achieving gender equality, and ensuring sustainable development.\n7. Educational workshops, book distribution drives, and adult literacy classes are organized globally.\n8. The UNESCO International Literacy Prizes are awarded to outstanding projects combating illiteracy on this day.\n9. In India, programs like Saakshar Bharat and the National Literacy Mission are highlighted during the events.\n10. Fostering literacy is celebrated as the foundation for peace, community development, and economic growth." },
  { date: "Sep 15", name: "Engineers' Day", theme: "\"Engineering for a Sustainable Future\"", significance: "Commemorates the birth anniversary of eminent engineer Bharat Ratna Sir M. Visvesvaraya." , detailedSignificance: "1. Engineers' Day is celebrated on 15th September to mark the contributions of engineers to national infrastructure and growth.\n2. It commemorates the birth anniversary of Sir Mokshagundam Visvesvaraya, a pioneer in Indian engineering.\n3. Sir M. Visvesvaraya was a civil engineer, statesman, and the 19th Diwan of Mysore, receiving the Bharat Ratna in 1955.\n4. He designed the Krishna Raja Sagara Dam in Mysore and developed automatic floodgates at Khadakwasla Reservoir, Pune.\n5. Questions in exams cover scientific breakthroughs, dam projects, national engineering organizations, and tech developments.\n6. The day is celebrated across engineering institutions, research labs, and public works departments in India.\n7. Seminars, project exhibitions, and innovation hackathons are organized to showcase engineering solutions.\n8. It highlights the role of engineers in building transport networks, clean energy grids, digital systems, and space technology.\n9. In the military, the Corps of Engineers plays a vital role in combat support, bridge building, and border road construction.\n10. The celebration inspires students to pursue engineering disciplines to solve national challenges and promote industrialization." },
  { date: "Sep 16", name: "International Ozone Day", theme: "\"Montreal Protocol: Fixing the ozone layer and reducing climate change\"", significance: "Commemorates the signing of the Montreal Protocol in 1987 for global ozone layer protection." , detailedSignificance: "1. International Ozone Day is observed on 16th September to raise awareness about the protection of the Ozone Layer.\n2. It commemorates the date of the signing of the Montreal Protocol on Substances that Deplete the Ozone Layer in 1987.\n3. The day was designated by the United Nations General Assembly in 1994 to promote global environmental protection.\n4. The Montreal Protocol is widely recognized as one of the most successful international environmental treaties.\n5. In science and geography sections, the ozone layer, UV radiation, CFCs, and atmospheric layers are highly tested.\n6. The ozone layer in the Stratosphere protects the Earth from harmful ultraviolet (UV) rays of the sun.\n7. The day advocates for phasing out ozone-depleting substances, such as chlorofluorocarbons (CFCs) and halons.\n8. The Kigali Amendment to the Montreal Protocol is highlighted, focusing on reducing hydrofluorocarbons (HFCs).\n9. Environmental seminars, science quiz competitions, and clean-tech campaigns are organized on this day.\n10. Protecting the ozone layer is presented as essential for preventing skin cancer, cataracts, and agricultural damage." },
  { date: "Sep 21", name: "International Day of Peace", theme: "\"Actions for Peace: Our Ambition for the #GlobalGoals\"", significance: "Dedicated to strengthening the ideals of peace and promoting a non-violent world." , detailedSignificance: "1. International Day of Peace is held on 21st September to strengthen the ideals of peace both within and among all nations.\n2. The day was established in 1981 by a resolution of the United Nations General Assembly.\n3. In 2001, the General Assembly voted to designate the day as a period of non-violence and cease-fire globally.\n4. The United Nations invites all nations and people to honor a cessation of hostilities and observe peace education.\n5. GK sections cover UN agencies, historical peace treaties, disarmament summits, and global security organizations.\n6. The Peace Bell is rung at UN Headquarters in New York to inaugurate the events of the day.\n7. It addresses the root causes of conflict, promoting social justice, human rights, and sustainable development.\n8. Peace education, interfaith dialogues, and international cooperation forums are organized worldwide.\n9. In India, the principles of non-violence (Ahimsa) pioneered by Mahatma Gandhi are highlighted on this day.\n10. Fostering global peace is presented as a prerequisite for human progress and achieving the Sustainable Development Goals." },
  { date: "Sep 27", name: "World Tourism Day", theme: "\"Tourism and Peace\"", significance: "Focuses on the social, cultural, political, and economic value of tourism globally." , detailedSignificance: "1. World Tourism Day is celebrated on 27th September to foster awareness of the social and economic value of tourism.\n2. It marks the anniversary of the adoption of the Statutes of the World Tourism Organization (UNWTO) in 1970.\n3. The UNWTO established the day in 1980 to promote sustainable, accessible, and responsible global travel.\n4. Tourism is a major driver of economic growth, generating millions of jobs and promoting cultural exchange.\n5. Geography and economy sections cover historical monuments, UNESCO world heritage sites, and tourism statistics.\n6. The day highlights the need to minimize the environmental impact of tourism and preserve local cultures.\n7. Heritage walks, cultural festivals, and travel exhibitions are organized by tourism departments across states.\n8. It encourages the development of eco-tourism, rural tourism, and adventure sports infrastructure.\n9. In India, campaigns like 'Incredible India' and the promotion of heritage corridors are showcased.\n10. Responsible travel is presented as a bridge to peace, cultural understanding, and global community building." },
  // --- OCTOBER ---
  { date: "Oct 8",  name: "Indian Air Force Day", theme: "-", significance: "Commemorates the official establishment of the Indian Air Force in 1932.", detailedSignificance: "1. Indian Air Force Day is celebrated on 8th October to commemorate the official establishment of the force.\n2. The Indian Air Force (IAF) was established on 8th October 1932 as an auxiliary air force of the British Empire.\n3. It was prefix-designated 'Royal' in 1945 in recognition of its services during World War II, dropping it in 1950.\n4. The IAF is the fourth largest air force in the world, responsible for securing Indian airspace and conducting aerial warfare.\n5. In defence exams, IAF command structure, fighter squadrons, missile integrations, and operations (like Operation Meghdoot) are tested.\n6. A grand parade and air show are organized at Hindon Air Force Station or selected national venues.\n7. Advanced aircraft, including Rafale, Su-30MKI, Tejas, and Apache helicopters, showcase aerial acrobatics.\n8. The day honors the bravery and professionalism of the air warriors under the motto 'Nabhah Sprisham Diptam' (Touch the Sky with Glory).\n9. Tribute is paid to the pioneers of the IAF, such as Air Marshal Subroto Mukerjee, the first Chief of the Air Staff.\n10. It highlights IAF's humanitarian assistance and disaster relief (HADR) operations in domestic and international crises.", detailedSignificance: "1. Indian Air Force Day is celebrated on 8th October to commemorate the official establishment of the force.\n2. The Indian Air Force (IAF) was established on 8th October 1932 as an auxiliary air force of the British Empire.\n3. It was prefix-designated 'Royal' in 1945 in recognition of its services during World War II, dropping it in 1950.\n4. The IAF is the fourth largest air force in the world, responsible for securing Indian airspace and conducting aerial warfare.\n5. In defence exams, IAF command structure, fighter squadrons, missile integrations, and operations (like Operation Meghdoot) are tested.\n6. A grand parade and air show are organized at Hindon Air Force Station or selected national venues.\n7. Advanced aircraft, including Rafale, Su-30MKI, Tejas, and Apache helicopters, showcase aerial acrobatics.\n8. The day honors the bravery and professionalism of the air warriors under the motto 'Nabhah Sprisham Diptam' (Touch the Sky with Glory).\n9. Tribute is paid to the pioneers of the IAF, such as Air Marshal Subroto Mukerjee, the first Chief of the Air Staff.\n10. It highlights IAF's humanitarian assistance and disaster relief (HADR) operations in domestic and international crises." },
  { date: "Oct 16", name: "World Food Day", theme: "\"Water is life, water is food. Leave no one behind\"", significance: "Commemorates the founding of the Food and Agriculture Organization (FAO) of the United Nations in 1945." , detailedSignificance: "1. World Food Day is observed on 16th October to raise awareness about global hunger and promote food security.\n2. It commemorates the founding anniversary of the Food and Agriculture Organization (FAO) of the United Nations in 1945.\n3. The day was established by FAO member countries at the organization's 20th General Conference in November 1979.\n4. Currently, millions of people worldwide suffer from chronic malnutrition, food insecurity, and hunger.\n5. Exams regularly cover agriculture, food security index, biotechnology in crops, and international food bodies (WFP, IFAD).\n6. The day supports Sustainable Development Goal 2 (Zero Hunger) by promoting sustainable agricultural practices.\n7. It calls for international action to reduce food waste, improve supply chains, and combat soil degradation.\n8. Food distribution campaigns, agricultural seminars, and nutrition workshops are organized by governments and NGOs.\n9. In India, national schemes like the National Food Security Act (NFSA) and PDS are highlighted during the events.\n10. Ensuring food security is presented as essential for public health, economic stability, and international security." },
  { date: "Oct 24", name: "United Nations Day", theme: "-", significance: "Marks the entry into force of the UN Charter in 1945, celebrating global cooperation.", detailedSignificance: "1. United Nations Day is celebrated on 24th October to mark the anniversary of the entry into force of the UN Charter.\n2. On 24th October 1945, the UN Charter was ratified by the P5 and a majority of other signatory nations.\n3. The United Nations was established in the aftermath of World War II to prevent future global conflicts.\n4. The day has been celebrated since 1948, promoting the ideals of international peace, justice, and human rights.\n5. NDA/CDS GK sections regularly feature questions on UN organs (Security Council, ICJ, General Assembly) and protocols.\n6. The UN works across six official languages to coordinate global diplomacy, development, and humanitarian aid.\n7. Concerts, flag-hoisting ceremonies, and debates on global security are organized at UN offices and schools worldwide.\n8. It addresses modern challenges like climate change, poverty eradication, disarmament, and refugee protection.\n9. India was one of the founding members of the UN, signing the declaration in San Francisco in 1945.\n10. The day reinforces the collective commitment of 193 member states to the principles of multilateral diplomacy.", detailedSignificance: "1. United Nations Day is celebrated on 24th October to mark the anniversary of the entry into force of the UN Charter.\n2. On 24th October 1945, the UN Charter was ratified by the P5 and a majority of other signatory nations.\n3. The United Nations was established in the aftermath of World War II to prevent future global conflicts.\n4. The day has been celebrated since 1948, promoting the ideals of international peace, justice, and human rights.\n5. NDA/CDS GK sections regularly feature questions on UN organs (Security Council, ICJ, General Assembly) and protocols.\n6. The UN works across six official languages to coordinate global diplomacy, development, and humanitarian aid.\n7. Concerts, flag-hoisting ceremonies, and debates on global security are organized at UN offices and schools worldwide.\n8. It addresses modern challenges like climate change, poverty eradication, disarmament, and refugee protection.\n9. India was one of the founding members of the UN, signing the declaration in San Francisco in 1945.\n10. The day reinforces the collective commitment of 193 member states to the principles of multilateral diplomacy." },
  { date: "Oct 31", name: "National Unity Day", theme: "\"Unity for Nation\"", significance: "Birth anniversary of Sardar Vallabhbhai Patel (Rashtriya Ekta Diwas), celebrating his role in national integration." , detailedSignificance: "1. National Unity Day (Rashtriya Ekta Diwas) is celebrated on 31st October to mark the birth anniversary of Sardar Vallabhbhai Patel.\n2. Sardar Patel was the first Deputy Prime Minister and Home Minister of independent India, serving from 1947 to 1950.\n3. He is known as the 'Iron Man of India' and the 'Patron Saint of India's Civil Servants' for his administrative leadership.\n4. He played a historic role in the integration of 562 princely states into the Indian Union after independence.\n5. History and polity sections test the integration of Hyderabad (Operation Polo), Junagadh, and Jammu & Kashmir.\n6. The day was introduced by the Government of India in 2014 to foster national integration, unity, and security.\n7. The 'Run for Unity' marathon is organized in cities, towns, and villages across the country.\n8. Police forces and paramilitary units hold march pasts and take the National Unity Pledge on this day.\n9. The Statue of Unity, the world's tallest statue (182 m) built in Gujarat, is the central venue of celebrations.\n10. The day honors Patel's vision, courage, and dedication in creating a united and strong sovereign nation." },
  // --- NOVEMBER ---
  { date: "Nov 10", name: "World Science Day for Peace and Development", theme: "\"Building Trust in Science\"", significance: "Highlights the significant role of science in society and the need to engage the public on scientific issues." , detailedSignificance: "1. World Science Day for Peace and Development is celebrated on 10th November to highlight the role of science in society.\n2. The day was proclaimed by UNESCO in 2001 and has been celebrated globally since 2002.\n3. It aims to ensure that citizens are kept informed of scientific developments and the role of research.\n4. The day underscores the importance of science in solving global challenges and building sustainable peace.\n5. Science, technology policies, and international research agreements (like CERN, ITER) are tested in exams.\n6. It promotes national and international solidarity for shared science between countries to bridge tech gaps.\n7. Science exhibitions, open-house labs, and school contests are organized by scientific departments on this day.\n8. The UNESCO Kalinga Prize for the Popularization of Science is presented during the celebrations.\n9. It connects scientific discoveries to daily life, focusing on health, climate change, and resource management.\n10. Fostering scientific research is presented as critical for national development, education, and global cooperation." },
  { date: "Nov 19", name: "World Toilet Day", theme: "\"Accelerating Change\"", significance: "Raises global awareness and inspires action to tackle the global sanitation crisis." , detailedSignificance: "1. World Toilet Day is observed on 19th November to inspire action to tackle the global sanitation crisis.\n2. The day was established by the World Toilet Organization in 2001 and officially declared by the UN in 2013.\n3. It aims to achieve Sustainable Development Goal 6, which calls for sanitation for all and ending open defecation.\n4. Currently, billions of people live without safely managed sanitation, causing severe health and environmental risks.\n5. NDA/CDS General Studies sections cover hygiene, waterborne diseases, public health policies, and environmental sanitation.\n6. Inadequate sanitation leads to the spread of diseases like cholera, typhoid, and dysentery, impacting rural health.\n7. In India, the Swachh Bharat Mission (launched in 2014) is highlighted for its role in constructing toilets.\n8. The day promotes the safety and dignity of women, who are disproportionately affected by the lack of private toilets.\n9. Seminars, hygiene awareness drives, and sanitation policy reviews are conducted by health departments.\n10. Safe sanitation systems are celebrated as essential for child survival, public health, and human dignity." },
  { date: "Nov 26", name: "Constitution Day", theme: "-", significance: "Marks the historic adoption of the Constitution of India by the Constituent Assembly in 1949 (Samvidhan Divas).", detailedSignificance: "1. Constitution Day (Samvidhan Divas) is celebrated on 26th November to commemorate the adoption of the Constitution.\n2. On 26th November 1949, the Constituent Assembly of India formally adopted the Constitution, which came into force in 1950.\n3. The day was declared by the government in 2015 to honor Dr. B. R. Ambedkar, the father of the Indian Constitution.\n4. Previously, the day was celebrated as National Law Day following a resolution by the Supreme Court Bar Association.\n5. Constitutional features, fundamental rights, preamble, directive principles, and amendments are heavily tested.\n6. The Preamble to the Constitution is read aloud in schools, colleges, and public offices across the country.\n7. Special sessions of Parliament and state assemblies are held to discuss constitutional values and democracy.\n8. Lectures, quizzes, and essay competitions on the Constitution are organized to educate citizens on their rights.\n9. It honors the contributions of the members of the Constituent Assembly, including Rajendra Prasad and Nehru.\n10. The celebration reinforces the democratic principles of justice, liberty, equality, and fraternity in India.", detailedSignificance: "1. Constitution Day (Samvidhan Divas) is celebrated on 26th November to commemorate the adoption of the Constitution.\n2. On 26th November 1949, the Constituent Assembly of India formally adopted the Constitution, which came into force in 1950.\n3. The day was declared by the government in 2015 to honor Dr. B. R. Ambedkar, the father of the Indian Constitution.\n4. Previously, the day was celebrated as National Law Day following a resolution by the Supreme Court Bar Association.\n5. Constitutional features, fundamental rights, preamble, directive principles, and amendments are heavily tested.\n6. The Preamble to the Constitution is read aloud in schools, colleges, and public offices across the country.\n7. Special sessions of Parliament and state assemblies are held to discuss constitutional values and democracy.\n8. Lectures, quizzes, and essay competitions on the Constitution are organized to educate citizens on their rights.\n9. It honors the contributions of the members of the Constituent Assembly, including Rajendra Prasad and Nehru.\n10. The celebration reinforces the democratic principles of justice, liberty, equality, and fraternity in India." },
  // --- DECEMBER ---
  { date: "Dec 1",  name: "World AIDS Day", theme: "\"Let Communities Lead\"", significance: "Global awareness day to fight HIV and support those affected." , detailedSignificance: "1. World AIDS Day is celebrated on 1st December to raise awareness about the fight against HIV/AIDS.\n2. The day was first conceived in August 1987 by James W. Bunn and Thomas Netter, public information officers for the WHO.\n3. It has been observed annually since 1988, becoming the first-ever global health day in history.\n4. The day aims to support people living with HIV, honor those who have died, and promote prevention research.\n5. In biology and science sections, HIV virus structure, transmission modes, diagnostics (ELISA), and drugs are covered.\n6. It addresses the social stigma and discrimination faced by individuals living with HIV, promoting human rights.\n7. Health clinics, red-ribbon campaigns, and free testing drives are organized by health agencies.\n8. The National AIDS Control Organisation (NACO) in India coordinates awareness, prevention, and treatment.\n9. The day urges increased funding, access to life-saving antiretroviral therapy (ART), and medical research.\n10. Global solidarity is highlighted as crucial to ending the AIDS epidemic as a public health threat by 2030." },
  { date: "Dec 4",  name: "Indian Navy Day", theme: "-", significance: "Celebrates the success of Operation Trident against Karachi harbor during the 1971 Indo-Pak war.", detailedSignificance: "1. Indian Navy Day is celebrated on 4th December to recognize the achievements and role of the maritime force.\n2. It commemorates the success of Operation Trident, a highly successful attack on Karachi harbor during the 1971 Indo-Pak war.\n3. Operation Trident involved the first use of anti-ship missiles in the region, causing severe damage to Pakistani naval assets.\n4. The Indian Navy is responsible for securing India's maritime borders, EEZ, and strategic interests in the Indian Ocean.\n5. NDA/CDS exams regularly cover naval commands, missile destroyers, aircraft carriers (Vikrant, Vikramaditya), and sub-surface fleets.\n6. Grand celebrations and naval demonstrations are held at Gateway of India, Mumbai, and naval command bases.\n7. Elite Marine Commandos (MARCOS) display search-and-rescue, tactical boarding, and helicopter operations.\n8. The day pays tribute to naval martyrs and honors officers under the motto 'Sam No Varunah' (May the Lord of Water be auspicious unto us).\n9. It showcases the navy's growing capabilities in blue-water operations, anti-piracy, and humanitarian assistance.\n10. The role of the Navy in Indo-Pacific security and defending sea lanes of communication is highly emphasized.", detailedSignificance: "1. Indian Navy Day is celebrated on 4th December to recognize the achievements and role of the maritime force.\n2. It commemorates the success of Operation Trident, a highly successful attack on Karachi harbor during the 1971 Indo-Pak war.\n3. Operation Trident involved the first use of anti-ship missiles in the region, causing severe damage to Pakistani naval assets.\n4. The Indian Navy is responsible for securing India's maritime borders, EEZ, and strategic interests in the Indian Ocean.\n5. NDA/CDS exams regularly cover naval commands, missile destroyers, aircraft carriers (Vikrant, Vikramaditya), and sub-surface fleets.\n6. Grand celebrations and naval demonstrations are held at Gateway of India, Mumbai, and naval command bases.\n7. Elite Marine Commandos (MARCOS) display search-and-rescue, tactical boarding, and helicopter operations.\n8. The day pays tribute to naval martyrs and honors officers under the motto 'Sam No Varunah' (May the Lord of Water be auspicious unto us).\n9. It showcases the navy's growing capabilities in blue-water operations, anti-piracy, and humanitarian assistance.\n10. The role of the Navy in Indo-Pacific security and defending sea lanes of communication is highly emphasized." },
  { date: "Dec 7",  name: "Armed Forces Flag Day", theme: "-", significance: "Observed to honor martyrs and the men in uniform, and collect funds for their welfare.", detailedSignificance: "1. Armed Forces Flag Day is observed on 7th December to honor the martyrs and soldiers in uniform.\n2. The day has been observed annually since 1949, designated by the Ministry of Defence committee.\n3. It aims to collect funds from citizens for the welfare of service personnel, veterans, and their families.\n4. The collected funds are managed by the Kendriya Sainik Board under the Armed Forces Flag Day Fund.\n5. Exams cover armed forces welfare schemes, Sainik Boards, rehabilitation programs, and the Ministry of Defence.\n6. Small flags in red, deep blue, and light blue (representing Army, Navy, Air Force) are distributed for donations.\n7. The day raises public awareness about the sacrifices made by soldiers in defending the nation's borders.\n8. Funds are utilized for the rehabilitation of war widows, disabled soldiers, and medical care of veterans.\n9. Commemorative events, band performances, and donation drives are organized by state Sainik Boards.\n10. Citizens are encouraged to contribute generously, expressing solidarity and gratitude to the armed forces.", detailedSignificance: "1. Armed Forces Flag Day is observed on 7th December to honor the martyrs and soldiers in uniform.\n2. The day has been observed annually since 1949, designated by the Ministry of Defence committee.\n3. It aims to collect funds from citizens for the welfare of service personnel, veterans, and their families.\n4. The collected funds are managed by the Kendriya Sainik Board under the Armed Forces Flag Day Fund.\n5. Exams cover armed forces welfare schemes, Sainik Boards, rehabilitation programs, and the Ministry of Defence.\n6. Small flags in red, deep blue, and light blue (representing Army, Navy, Air Force) are distributed for donations.\n7. The day raises public awareness about the sacrifices made by soldiers in defending the nation's borders.\n8. Funds are utilized for the rehabilitation of war widows, disabled soldiers, and medical care of veterans.\n9. Commemorative events, band performances, and donation drives are organized by state Sainik Boards.\n10. Citizens are encouraged to contribute generously, expressing solidarity and gratitude to the armed forces." },
  { date: "Dec 10", name: "Human Rights Day", theme: "\"Freedom, Equality and Justice for All\"", significance: "Marks the adoption of the Universal Declaration of Human Rights in 1948 by the UN." , detailedSignificance: "1. Human Rights Day is observed on 10th December to advocate for the rights of all people globally.\n2. It commemorates the date when the United Nations General Assembly adopted the Universal Declaration of Human Rights (UDHR) in 1948.\n3. The UDHR is a milestone document that proclaims the inalienable rights which everyone is inherently entitled to.\n4. The day was officially established in 1950, following a UN General Assembly resolution inviting all states to celebrate it.\n5. NDA/CDS exams cover the UDHR, national and state human rights commissions (NHRC), and fundamental rights.\n6. The UDHR is the most translated document in the world, available in over 500 languages.\n7. Human rights conferences, award ceremonies, and photo exhibitions are held at UN centres and cities.\n8. It addresses modern challenges like discrimination, poverty, inequality, and human rights in conflict zones.\n9. In India, the Protection of Human Rights Act, 1993, establishes the statutory framework for human rights protection.\n10. Defending human rights is presented as essential for democracy, rule of law, and sustainable global peace." },
  { date: "Dec 16", name: "Vijay Diwas", theme: "-", significance: "Commemorates India's historic victory over Pakistan in the 1971 war, leading to the liberation of Bangladesh.", detailedSignificance: "1. Vijay Diwas (Victory Day) is celebrated on 16th December to mark India's victory over Pakistan in the 1971 war.\n2. On this day, the Chief of Pakistani Forces, General A. A. K. Niazi, surrendered to the Indian Army and Mukti Bahini.\n3. Over 93,000 Pakistani soldiers surrendered, marking the largest military surrender in the world since World War II.\n4. The war lasted for 13 days and resulted in the liberation of East Pakistan, leading to the creation of Bangladesh.\n5. History sections in NDA/CDS cover the 1971 war, Shimla Agreement (1972), and heroes like Field Marshal Sam Manekshaw.\n6. The main ceremony is held at the National War Memorial in New Delhi, where the military leadership pays tribute.\n7. The Param Vir Chakra was awarded to Lance Naik Albert Ekka, Flying Officer Nirmal Jit Singh Sekhon, and others for their role.\n8. Joint celebrations are held by India and Bangladesh, highlighting their shared historical ties and strategic cooperation.\n9. It showcases the military planning, intelligence success, and jointmanship displayed by the Indian Armed Forces.\n10. The day celebrates the triumph of justice, human rights, and military professional excellence over oppression.", detailedSignificance: "1. Vijay Diwas (Victory Day) is celebrated on 16th December to mark India's victory over Pakistan in the 1971 war.\n2. On this day, the Chief of Pakistani Forces, General A. A. K. Niazi, surrendered to the Indian Army and Mukti Bahini.\n3. Over 93,000 Pakistani soldiers surrendered, marking the largest military surrender in the world since World War II.\n4. The war lasted for 13 days and resulted in the liberation of East Pakistan, leading to the creation of Bangladesh.\n5. History sections in NDA/CDS cover the 1971 war, Shimla Agreement (1972), and heroes like Field Marshal Sam Manekshaw.\n6. The main ceremony is held at the National War Memorial in New Delhi, where the military leadership pays tribute.\n7. The Param Vir Chakra was awarded to Lance Naik Albert Ekka, Flying Officer Nirmal Jit Singh Sekhon, and others for their role.\n8. Joint celebrations are held by India and Bangladesh, highlighting their shared historical ties and strategic cooperation.\n9. It showcases the military planning, intelligence success, and jointmanship displayed by the Indian Armed Forces.\n10. The day celebrates the triumph of justice, human rights, and military professional excellence over oppression." },
  { date: "Dec 23", name: "National Farmers' Day", theme: "\"Delivering Smart Solutions for Sustainable Food Security and Resilience\"", significance: "Birth anniversary of Chaudhary Charan Singh (Kisan Diwas), celebrating the contribution of India's farmers." , detailedSignificance: "1. National Farmers' Day (Kisan Diwas) is celebrated on 23rd December to recognize the contributions of farmers.\n2. It commemorates the birth anniversary of Chaudhary Charan Singh, the fifth Prime Minister of India.\n3. Chaudhary Charan Singh was a champion of peasant rights, introducing land reform acts and debt redemption bills.\n4. The day was established by the Government of India in 2001 to honor his dedication to the farming community.\n5. Economics and geography sections cover Indian agriculture, major crops, soil types, and farming welfare schemes.\n6. It raises awareness about the issues faced by farmers, such as climate change, water scarcity, and fair pricing.\n7. Agricultural seminars, exhibition of modern machinery, and workshops on organic farming are organized.\n8. The day highlights the role of farmers as the backbone of the Indian economy and food security system.\n9. In the military, the slogan 'Jai Jawan Jai Kisan' (coined by Lal Bahadur Shastri) is celebrated to honor both sectors.\n10. Promoting sustainable farming practices and digital technologies is emphasized to improve agricultural productivity." },
];
