const fs = require('fs');
const path = require('path');

const progressFile = path.join(__dirname, 'diagram_pipeline', 'progress.json');
const artifactFile = path.join('C:\\Users\\Trayodh Khandalkar\\.gemini\\antigravity-ide\\brain\\40775e62-ac16-44ca-b442-e860045b5422', 'diagram_checklist.md');

let progressData = { generated: [] };
if (fs.existsSync(progressFile)) {
    progressData = JSON.parse(fs.readFileSync(progressFile, 'utf8'));
}

// Extract subject and title from keys like "mathematics_car_production_bar_chart__2014_2018_"
function formatKey(key) {
    const parts = key.split('_');
    const subject = parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
    const titleRaw = parts.slice(1).join(' ').replace(/_+/g, ' ').trim();
    const title = titleRaw.charAt(0).toUpperCase() + titleRaw.slice(1);
    return { subject, title };
}

const categorized = {};
for (const key of progressData.generated) {
    const { subject, title } = formatKey(key);
    if (!categorized[subject]) categorized[subject] = [];
    categorized[subject].push(title);
}

let md = `# Visual Generation Checklist\n\n`;
md += `> [!NOTE]\n> The diagrams below are grouped by subject. The exact titles of **Future Diagrams** are dynamically generated by the AI as it reads through the remaining textbook chunks.\n\n`;

md += `## ✅ Completed Diagrams\n\n`;

for (const subject of Object.keys(categorized).sort()) {
    md += `### ${subject}\n`;
    for (const title of categorized[subject]) {
        md += `- [x] ${title}\n`;
    }
    md += `\n`;
}

md += `## ⏳ Upcoming/Pending Categories\n`;
md += `The pipeline is currently at chunk ~20 out of 867. As it processes the remaining 840+ chunks of the Pathfinder CDS syllabus, it will dynamically generate diagrams for the following expected sections:\n\n`;

md += `### General Sciences\n`;
md += `- [ ] **Physics**: Optics, Electricity & Magnetism, Mechanics, Thermodynamics\n`;
md += `- [ ] **Chemistry**: Atomic Structure, Chemical Bonding, Acids & Bases, Carbon Compounds\n`;
md += `- [ ] **Biology**: Cell Biology, Human Anatomy, Plant Physiology, Diseases\n\n`;

md += `### Humanities\n`;
md += `- [ ] **History**: Modern Indian History (Freedom Struggle), Medieval Empires, World History\n`;
md += `- [ ] **Geography**: World Geography, Climate, Indian Agriculture, Mineral Resources\n`;
md += `- [ ] **Polity**: Constitution Details, Parliament, Judiciary, Fundamental Rights\n`;
md += `- [ ] **Economics**: Macroeconomics, Five Year Plans, Banking & Finance\n\n`;

md += `### Mathematics\n`;
md += `- [ ] **Advanced Geometry**: 3D Mensuration, Advanced Trigonometry\n`;
md += `- [ ] **Statistics**: Histograms, Probability, Mean/Median/Mode Distributions\n`;
md += `- [ ] **Algebra**: Polynomials, Logarithms, Set Theory\n`;

fs.writeFileSync(artifactFile, md, 'utf8');
console.log('Artifact generated successfully.');
