import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_MOCK_ASSEMBLER_PROMPT = """
# STAGE 8 — MASTER MOCK TEST BLUEPRINT, ASSEMBLY & QUALITY ASSURANCE PROMPT

## ROLE
You are an Expert Defence Examination Paper Setter, Assessment Designer, and Blueprint Engineer.
Your responsibility is to generate examination-quality mock tests that accurately replicate the standards, syllabus coverage, difficulty distribution, question style, and psychometric characteristics of NDA, CDS, AFCAT, CAPF AC, Territorial Army, and IB examinations.

## INPUT
You will receive a list of available Canonical Questions from the validated Question Bank, their metadata, and a target Blueprint configuration.

## PRIMARY OBJECTIVE
Construct balanced, realistic mock examinations that closely resemble official examination patterns.
Never include duplicate questions. Ensure balanced difficulty. 

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the assembled Mock Test (no markdown code blocks):
{
  "mock_test_id": "...",
  "exam": "...",
  "paper_type": "...",
  "blueprint_used": "...",
  "total_questions": 0,
  "total_marks": 0,
  "time_limit": "...",
  "difficulty_distribution": {
    "very_easy": "0%",
    "easy": "0%",
    "medium": "0%",
    "hard": "0%",
    "very_hard": "0%"
  },
  "subject_distribution": {},
  "chapter_distribution": {},
  "topic_distribution": {},
  "selected_questions": [
    {
       "question_id": "...",
       "question_text": "...",
       "options": {},
       "estimated_solve_time": "..."
    }
  ],
  "estimated_total_solve_time": "...",
  "similarity_score": {
    "syllabus_similarity": 0,
    "difficulty_similarity": 0,
    "overall_similarity_score": 0
  },
  "quality_assurance_report": "...",
  "answer_key": [
    {
       "question_id": "...",
       "correct_answer": "...",
       "explanation": "..."
    }
  ],
  "performance_metadata": {
       "question_id": "..."
  },
  "export_format": "JSON"
}

## GOLDEN RULES
* Never generate a random paper without following the blueprint.
* Never include duplicate or semantically equivalent questions.
* Every mock must closely resemble the official examination.
"""

def generate_mock_gemini(available_q_str, exam_config):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_MOCK_ASSEMBLER_PROMPT}\n\nTarget Blueprint/Configuration:\n{exam_config}\n\nAvailable Question Bank:\n{available_q_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.3, # slightly higher temp for varied paper generation
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Assemble a Mock Test from the consolidated question bank.")
    parser.add_argument("input_json", help="Path to the input JSON file containing consolidated questions")
    parser.add_argument("output_json", help="Path to the output JSON file for the generated mock test")
    parser.add_argument("--exam", default="CDS", help="Target Exam (e.g. NDA, CDS, AFCAT)")
    parser.add_argument("--paper", default="General Knowledge", help="Target Paper")
    parser.add_argument("--count", type=int, default=1, help="Number of questions to include in the mock")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    # Filter canonical questions to use for assembly
    canonical_qs = [q for q in questions if q.get("deduplication_metadata", {}).get("retention_decision") == "Canonical Question"]
    
    print(f"Found {len(canonical_qs)} canonical questions available for assembly.")
    
    # In a real scenario, we would use a vector DB to pull the relevant questions for the blueprint. 
    # Here we just pass the available canonical questions.
    available_q_str = json.dumps(canonical_qs, indent=2)
    
    exam_config = f"Exam: {args.exam}, Paper: {args.paper}, Total Questions Target: {args.count}, Test Type: Mini-Mock"
    print(f"\n--- Generating {args.exam} {args.paper} Mock Test ---")
    
    result = generate_mock_gemini(available_q_str, exam_config)
    
    if result:
        with open(args.output_json, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
            
        print(f"Successfully generated Mock Test: {result.get('mock_test_id', 'UNKNOWN')}")
        print(f"Total Questions Assembled: {result.get('total_questions', 0)}")
        print(f"Overall Similarity Score: {result.get('similarity_score', {}).get('overall_similarity_score', 0)}")
    else:
        print(f"Failed to generate mock test.")

if __name__ == "__main__":
    main()
