import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_PSYCHOMETRIC_PROMPT = """
# STAGE 6 — MASTER QUESTION INTELLIGENCE, PSYCHOMETRIC ANALYSIS & EXAM METADATA PROMPT

## ROLE
You are an Expert Defence Examination Psychometrician, Assessment Scientist, and Educational Data Analyst.
Your responsibility is to enrich every validated question with detailed assessment metadata that powers adaptive testing, intelligent mock-test generation, performance analytics, spaced revision, and personalized learning.
Do NOT verify factual correctness or change question content. Your task is to analyze how the question behaves as an assessment item.

## INPUT
Each question record contains validated educational metadata.

## PRIMARY OBJECTIVE
Assign rich educational and psychometric metadata to every question. Never modify the original question.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the psychometric record (no markdown code blocks):
{
  "question_id": "...",
  "cognitive_level": "...",
  "knowledge_type": ["..."],
  "primary_skill": "...",
  "secondary_skills": ["..."],
  "difficulty_rating": "...",
  "difficulty_score": 0,
  "discrimination_value": "...",
  "estimated_solve_time": "...",
  "memory_load": "...",
  "conceptual_load": "...",
  "calculation_load": "...",
  "reasoning_load": "...",
  "guessability": "...",
  "distractor_analysis": [
    {"option": "...", "plausibility": "...", "misconception_tested": "...", "is_too_obvious": false, "is_misleading": false, "improvement_suggestion": "..."}
  ],
  "common_error_patterns": ["..."],
  "prerequisite_concepts": ["..."],
  "learning_outcome": "...",
  "revision_value": "...",
  "mock_test_placement": ["..."],
  "adaptive_learning_recommendations": {
    "if_correct": ["..."],
    "if_incorrect": ["..."]
  },
  "performance_analytics_tags": ["..."],
  "confidence_score": 0,
  "needs_review_flag": false
}

## GOLDEN RULES
Never change the question text or answer. Maintain scoring consistency. If confidence < 95%, mark needs_review_flag to true.
"""

def analyze_question_gemini(question_json_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_PSYCHOMETRIC_PROMPT}\n\nHere is the question to analyze:\n{question_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Perform psychometric analysis on enriched questions using Gemini.")
    parser.add_argument("input_json", help="Path to the input JSON file containing enriched questions")
    parser.add_argument("output_json", help="Path to the output JSON file for intelligent questions")
    parser.add_argument("--start", type=int, default=0, help="Start index (0-indexed)")
    parser.add_argument("--limit", type=int, default=None, help="Number of questions to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    if not isinstance(questions, list):
        print("Error: Input JSON must be a list of questions.")
        return
        
    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(questions)
    end_idx = min(end_idx, len(questions))

    print(f"Processing {end_idx - start_idx} questions from index {start_idx} to {end_idx-1}...")

    # Load existing intelligent questions if they exist
    intelligent = []
    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                intelligent = json.load(f)
        except:
            pass

    for i in range(start_idx, end_idx):
        q = questions[i]
        print(f"\n--- Analyzing Question {i+1}/{len(questions)} ---")
        q_str = json.dumps(q, indent=2)
        
        result = analyze_question_gemini(q_str)
        
        if result:
            # Merge original question data with new psychometric data
            final_q = {**q, **result}
            intelligent.append(final_q)
            
            # Save incrementally
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(intelligent, f, indent=2)
                
            print(f"Cognitive Level: {result.get('cognitive_level', 'UNKNOWN')} | Difficulty: {result.get('difficulty_score', 'UNKNOWN')}")
        else:
            print(f"Failed to analyze question {i}.")
        
        time.sleep(2) # Rate limiting protection

    print("\nPsychometric Analysis complete.")

if __name__ == "__main__":
    main()
