import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_DEDUPLICATOR_PROMPT = """
# STAGE 7 — MASTER SEMANTIC DUPLICATE DETECTION, CANONICALIZATION & QUESTION CONSOLIDATION PROMPT

## ROLE
You are an Expert Assessment Content Auditor, Semantic Similarity Specialist, and Defence Examination Question Bank Architect.
Your responsibility is to identify duplicate, near-duplicate, equivalent, overlapping, and derivative questions across the entire question database.
Your goal is to create a single canonical, non-redundant question bank while preserving every unique examination concept.
Never delete questions automatically. Never merge questions without strong evidence.

## INPUT
You will receive a target question and a list of existing canonical questions to compare it against.

## PRIMARY OBJECTIVE
Identify semantic duplication rather than exact text matches.
Decide if the target question is a duplicate of any existing question, or if it should be a new canonical question.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the deduplication decision (no markdown code blocks):
{
  "question_id": "...",
  "duplicate_status": "Duplicate" | "Unique" | "Partial Overlap" | "Concept Variant",
  "duplicate_type": "Exact" | "Semantic" | "Conceptual" | "Numerical Variant" | "Current Affairs Variant" | "Partial Overlap" | "Unique",
  "canonical_question_id": "...",
  "duplicate_cluster_id": "...",
  "concept_family_id": "...",
  "similarity_scores": {
    "semantic_similarity": 0,
    "concept_similarity": 0,
    "learning_objective_similarity": 0,
    "overall_duplicate_confidence": 0
  },
  "shared_learning_objective": "...",
  "shared_concepts": ["..."],
  "canonical_recommendation": "...",
  "explanation_recommendation": "...",
  "retention_decision": "Canonical Question" | "Keep as Separate PYQ" | "Keep as Historical Variant" | "Keep as Numerical Variant" | "Keep as Concept Variant" | "Needs Manual Review",
  "related_question_ids": ["..."],
  "knowledge_gap_flags": ["..."],
  "confidence_score": 0,
  "needs_review_flag": false
}

## GOLDEN RULES
* Never delete previous-year questions.
* Compare meaning, not wording.
* Maintain complete audit trails.
* If confidence is below 95%, mark Needs Review.
"""

def detect_duplicates_gemini(target_q_str, existing_q_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_DEDUPLICATOR_PROMPT}\n\nHere is the target question:\n{target_q_str}\n\nHere is the list of existing canonical questions to compare against:\n{existing_q_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Perform semantic duplicate detection on questions.")
    parser.add_argument("input_json", help="Path to the input JSON file containing intelligent questions")
    parser.add_argument("output_json", help="Path to the output JSON file for consolidated questions")
    parser.add_argument("--start", type=int, default=0, help="Start index")
    parser.add_argument("--limit", type=int, default=None, help="Number of questions to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(questions)
    end_idx = min(end_idx, len(questions))

    print(f"Processing {end_idx - start_idx} questions for deduplication...")

    consolidated = []
    canonical_db = []

    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                consolidated = json.load(f)
                # Build simple canonical DB from existing consolidated (just getting the first 5 for context)
                for c in consolidated:
                    if c.get("retention_decision") == "Canonical Question":
                        canonical_db.append(c)
        except:
            pass

    for i in range(start_idx, end_idx):
        q = questions[i]
        print(f"\n--- Deduplicating Question {i+1}/{len(questions)} ({q.get('question_id')}) ---")
        
        target_str = json.dumps(q, indent=2)
        
        # We only pass a small subset of canonical DB to LLM to prevent context overflow.
        # In a real production system, we'd use vector embeddings (FAISS/ChromaDB) to retrieve top K matches first.
        # For this prototype, we just pass the most recent canonicals.
        existing_str = json.dumps(canonical_db[-5:], indent=2) if canonical_db else "[]"
        
        result = detect_duplicates_gemini(target_str, existing_str)
        
        if result:
            final_q = {**q, "deduplication_metadata": result}
            consolidated.append(final_q)
            
            if result.get("duplicate_status") == "Unique" or result.get("retention_decision") == "Canonical Question":
                 canonical_db.append(final_q)
            
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(consolidated, f, indent=2)
                
            print(f"Status: {result.get('duplicate_status', 'UNKNOWN')} | Type: {result.get('duplicate_type', 'UNKNOWN')}")
            print(f"Canonical ID: {result.get('canonical_question_id', 'UNKNOWN')}")
        else:
            print(f"Failed to deduplicate question {i}.")
        
        time.sleep(2)

    print("\nDeduplication complete.")

if __name__ == "__main__":
    main()
