import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_DRONACHARYA_PROMPT = """
# STAGE 10 — MASTER "ASK DRONACHARYA" AI TUTOR, RAG & INTELLIGENT MENTOR PROMPT

## ROLE
You are Ask Dronacharya, an AI Defence Examination Mentor for NDA, CDS, AFCAT, CAPF AC, Territorial Army, and Intelligence Bureau examinations.
Your purpose is to teach, explain, guide, test, mentor, and personalize learning using ONLY verified educational content from the platform whenever possible.

## INPUT
You will receive:
1. The student's natural language query.
2. RAG Context (Student Analytics, Relevant Questions, Knowledge Base).

## PRIMARY OBJECTIVE
Understand the intent, retrieve the most relevant verified content, build a structured answer, adapt to the student's current level, and recommend the next learning step.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the Dronacharya Response (no markdown code blocks):
{
  "intent": "...",
  "student_level": "...",
  "retrieved_resources": [],
  "direct_answer": "...",
  "detailed_explanation": "...",
  "supporting_concepts": [],
  "common_mistakes": "...",
  "memory_aid": "...",
  "related_pyqs": [],
  "related_practice_questions": [],
  "knowledge_graph_connections": [],
  "recommended_next_topic": "...",
  "revision_recommendation": "...",
  "confidence_level": "High/Medium/Low",
  "knowledge_sources": []
}

## GOLDEN RULES
* Prefer verified platform content over general model knowledge.
* Adapt explanations to the student's demonstrated level.
* When information is unavailable or uncertain, explicitly say so rather than guessing.
* Every response should leave the student with a clear next action for learning.
"""

def generate_tutor_response_gemini(query, analytics_str, questions_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_DRONACHARYA_PROMPT}\n\nStudent Query:\n\"{query}\"\n\nRAG Context - Student Analytics:\n{analytics_str}\n\nRAG Context - Knowledge Base (Relevant Questions):\n{questions_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Ask Dronacharya AI Tutor.")
    parser.add_argument("query", help="The student's natural language query")
    parser.add_argument("analytics_json", help="Path to the student's analytics report")
    parser.add_argument("questions_json", help="Path to the knowledge base (consolidated questions)")
    parser.add_argument("output_json", help="Path to save the generated tutor response")
    args = parser.parse_args()

    if not os.path.exists(args.analytics_json):
        print(f"File not found: {args.analytics_json}")
        return
        
    if not os.path.exists(args.questions_json):
        print(f"File not found: {args.questions_json}")
        return

    with open(args.analytics_json, "r", encoding="utf-8") as f:
        analytics = json.load(f)
        
    with open(args.questions_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    # In a full system, you would use semantic search (e.g. vector DB) on the query.
    # Here, we pass the available context.
    analytics_str = json.dumps(analytics, indent=2)
    questions_str = json.dumps(questions, indent=2)
    
    print(f"\n--- Querying Ask Dronacharya ---")
    print(f"Query: {args.query}")
    
    result = generate_tutor_response_gemini(args.query, analytics_str, questions_str)
    
    if result:
        with open(args.output_json, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
            
        print(f"Successfully generated Dronacharya Response!")
        print(f"Intent Detected: {result.get('intent', 'UNKNOWN')}")
        print(f"Confidence Level: {result.get('confidence_level', 'UNKNOWN')}")
    else:
        print(f"Failed to generate response.")

if __name__ == "__main__":
    main()
