import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_ANALYTICS_PROMPT = """
# STAGE 9 — MASTER STUDENT ANALYTICS, ADAPTIVE LEARNING & PERSONALIZED REVISION ENGINE PROMPT

## ROLE
You are an Expert Educational Data Scientist, Learning Analytics Architect, Cognitive Learning Specialist, and Defence Examination Mentor.
Your responsibility is to continuously analyze every student's learning journey and generate highly personalized recommendations, adaptive practice, revision schedules, performance insights, and exam readiness predictions.
You must only analyze student performance and generate recommendations.

## INPUT
You will receive:
1. The student's performance data and attempt history.
2. The metadata of the questions they attempted.

## PRIMARY OBJECTIVE
Create a personalized learning engine that identifies strengths, weaknesses, learning patterns, and optimal study paths.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the 20-step analytics report (no markdown code blocks):
{
  "student_id": "...",
  "performance_summary": {
     "overall_accuracy": "...",
     "questions_attempted": 0,
     "questions_correct": 0,
     "questions_incorrect": 0,
     "average_solve_time": "..."
  },
  "subject_analytics": {},
  "chapter_analytics": {},
  "topic_analytics": {},
  "concept_mastery_map": {},
  "error_analysis": {},
  "speed_analysis": {},
  "revision_schedule": [],
  "knowledge_gap_report": [],
  "adaptive_study_plan": {},
  "question_recommendations": [],
  "mock_recommendations": [],
  "exam_readiness_report": {},
  "score_projection": {},
  "risk_report": [],
  "learning_behavior_analysis": [],
  "goal_tracking": {},
  "motivational_feedback": "...",
  "dashboard_metrics": {},
  "confidence_score": 0,
  "last_updated": "..."
}

## GOLDEN RULES
* Base every recommendation on actual student performance.
* Never invent progress or achievements.
* Adapt recommendations as new performance data becomes available.
* Ensure recommendations are actionable, personalized, and explainable.
"""

def generate_analytics_gemini(student_data_str, questions_data_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_ANALYTICS_PROMPT}\n\nStudent Data:\n{student_data_str}\n\nQuestion Metadata:\n{questions_data_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Generate student analytics.")
    parser.add_argument("student_json", help="Path to the input JSON file containing student data")
    parser.add_argument("questions_json", help="Path to the input JSON file containing consolidated questions")
    parser.add_argument("output_json", help="Path to the output JSON file for the analytics report")
    args = parser.parse_args()

    if not os.path.exists(args.student_json):
        print(f"File not found: {args.student_json}")
        return
        
    if not os.path.exists(args.questions_json):
        print(f"File not found: {args.questions_json}")
        return

    with open(args.student_json, "r", encoding="utf-8") as f:
        student = json.load(f)
        
    with open(args.questions_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    # Filter question metadata to only those attempted by the student
    attempted_q_ids = [a.get("question_id") for a in student.get("attempt_history", [])]
    relevant_qs = [q for q in questions if q.get("question_id") in attempted_q_ids]
    
    student_str = json.dumps(student, indent=2)
    questions_str = json.dumps(relevant_qs, indent=2)
    
    print(f"\n--- Generating Analytics for Student {student.get('student_id', 'UNKNOWN')} ---")
    
    result = generate_analytics_gemini(student_str, questions_str)
    
    if result:
        with open(args.output_json, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
            
        print(f"Successfully generated Analytics Report!")
        print(f"Overall Accuracy: {result.get('performance_summary', {}).get('overall_accuracy', 'UNKNOWN')}")
    else:
        print(f"Failed to generate analytics.")

if __name__ == "__main__":
    main()
