import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_CLASSIFICATION_PROMPT = """
# MASTER SYLLABUS CLASSIFICATION & METADATA ENRICHMENT PROMPT

## ROLE
You are an Expert Defence Examination Syllabus Architect.
Your responsibility is to classify every validated question into the exact syllabus hierarchy for NDA, CDS, AFCAT, CAPF AC, Territorial Army, and IB examinations.
Your goal is to build a machine-readable Question Knowledge Base.
Never guess. If confidence is below 95%, mark **Needs Review**.

## INPUT
Each record has already passed validation. Do NOT verify factual correctness. Your only task is classification and metadata enrichment.

## PRIMARY OBJECTIVE
Assign every approved question to the most precise location in the syllabus hierarchy. Never stop at only the subject level.

## STEPS
1. SUBJECT CLASSIFICATION: Assign ONE primary subject (e.g. Mathematics, English, Physics, History, Geography, Indian Polity, Current Affairs). Optional secondary subjects.
2. CHAPTER CLASSIFICATION: Identify exact chapter (e.g., History -> Modern India).
3. TOPIC CLASSIFICATION: Determine exact topic (e.g., Revolt of 1857 -> Causes).
4. SUBTOPIC CLASSIFICATION: Continue drilling down to deepest level (e.g., Article 19 -> Reasonable Restrictions).
5. CONCEPT IDENTIFICATION: Identify principal concept tested (e.g., Constitutional Amendment, Photosynthesis).
6. LEARNING OBJECTIVE: Recall, Conceptual Understanding, Application, Numerical Problem Solving, Logical Reasoning, Interpretation, etc.
7. QUESTION TYPE: Fact Based, Concept Based, Statement Based, Calculation, Reasoning, etc.
8. DIFFICULTY TAGS: Very Easy, Easy, Medium, Hard, Very Hard. Also Memory Heavy, Concept Heavy, Calculation Heavy, Application Heavy.
9. EXAM TAGGING: Mark all applicable (NDA, CDS, AFCAT, etc).
10. EXAM WEIGHTAGE: Very High, High, Medium, Low, Very Low.
11. KEYWORDS: 5–20 concise searchable keywords.
12. RELATED CONCEPTS: Identify directly related topics.
13. PREREQUISITE TOPICS: Identify true prerequisites.
14. NEXT RECOMMENDED TOPICS: Logical follow-ups.
15. COMMON MISTAKES: List common misconceptions.
16. REVISION PRIORITY: Critical, High, Medium, Low.
17. INTERCONNECTION GRAPH: Question -> Topic, Topic -> Chapter, Question -> Similar Questions, etc.
18. OUTPUT: Return one enriched metadata record.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the enriched record (no markdown code blocks):
{
  "question_id": "...",
  "primary_subject": "...",
  "secondary_subjects": ["..."],
  "chapter": "...",
  "subchapter": "...",
  "topic": "...",
  "subtopic": "...",
  "core_concept": "...",
  "learning_objective": "...",
  "question_type": ["..."],
  "difficulty": "...",
  "cognitive_level": ["..."],
  "exam_tags": ["..."],
  "exam_weightage": "...",
  "keywords": ["..."],
  "related_concepts": ["..."],
  "prerequisite_topics": ["..."],
  "next_recommended_topics": ["..."],
  "common_mistakes": ["..."],
  "revision_priority": "...",
  "knowledge_graph_links": {
      "question_to_topic": "...",
      "topic_to_chapter": "..."
  },
  "confidence_score": 0,
  "needs_review_flag": false
}

## GOLDEN RULES
Never change the question text. Never modify the answer. Prefer deepest possible syllabus classification. Use consistent taxonomy. Ensure metadata supports adaptive learning. If confidence < 95%, set needs_review_flag to true.
"""

def classify_question_gemini(question_json_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_CLASSIFICATION_PROMPT}\n\nHere is the validated question to classify:\n{question_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Classify and enrich a validated question database using Gemini.")
    parser.add_argument("input_json", help="Path to the input JSON file containing validated questions")
    parser.add_argument("output_json", help="Path to the output JSON file for enriched questions")
    parser.add_argument("--start", type=int, default=0, help="Start index (0-indexed)")
    parser.add_argument("--limit", type=int, default=None, help="Number of questions to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    if not isinstance(questions, list):
        print("Error: Input JSON must be a list of questions.")
        return
        
    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(questions)
    end_idx = min(end_idx, len(questions))

    print(f"Processing {end_idx - start_idx} questions from index {start_idx} to {end_idx-1}...")

    # Load existing enriched questions if they exist
    enriched = []
    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                enriched = json.load(f)
        except:
            pass

    for i in range(start_idx, end_idx):
        q = questions[i]
        print(f"\n--- Classifying Question {i+1}/{len(questions)} ---")
        q_str = json.dumps(q, indent=2)
        
        result = classify_question_gemini(q_str)
        
        if result:
            # Merge original question data with new classification data
            final_q = {**q, **result}
            enriched.append(final_q)
            
            # Save incrementally
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(enriched, f, indent=2)
                
            print(f"Subject: {result.get('primary_subject', 'UNKNOWN')} | Topic: {result.get('topic', 'UNKNOWN')}")
        else:
            print(f"Failed to classify question {i}.")
        
        time.sleep(2) # Rate limiting protection

    print("\nClassification complete.")

if __name__ == "__main__":
    main()
