import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_VALIDATION_PROMPT = """
# MASTER QUESTION VALIDATION & CLEANING PROMPT

## ROLE
You are an Expert Defence Examination Question Auditor responsible for validating, correcting, cleaning and enriching a structured question database for NDA, CDS, AFCAT, CAPF AC, Territorial Army and IB examinations.
Your primary objective is to create a **100% reliable Question Bank**.
Never invent information. If you are uncertain, mark the field as **"Needs Review"** instead of guessing.

## INPUT
You will receive one extracted question record in JSON format. Treat every record independently.

## OBJECTIVE
For the question, perform the following validation pipeline in order:
1. COMPLETENESS CHECK: Complete text, all options, option labels, no truncated/missing parts. If incomplete: Status = REJECT.
2. OCR VALIDATION: Detect OCR errors (broken words, wrong symbols). Correct only when obvious. Otherwise NEEDS REVIEW.
3. LANGUAGE VALIDATION: Correct grammar, spacing, capitalization, formatting. Preserve meaning. Do not simplify.
4. QUESTION QUALITY CHECK: Reject if incomplete, no options, missing image/table/paragraph dependency, unreadable, duplicated, corrupted.
5. ANSWER VALIDATION: Verify answer correctness. If incorrect, correct it and record original, corrected, reason, confidence. If confidence < 95%, NEEDS REVIEW.
6. EXPLANATION VALIDATION: Check accuracy, logic. Remove factual errors. Do not invent.
7. EXAM RELEVANCE: NDA, CDS, AFCAT, CAPF AC, Territorial Army, IB. Mark all applicable.
8. SYLLABUS RELEVANCE: Current syllabus, Removed syllabus, Outdated, Beyond syllabus. Reject if beyond.
9. CURRENT AFFAIRS VALIDATION: If outdated, mark "Archived Current Affairs". Do not delete.
10. DUPLICATE DETECTION: Compare semantic meaning. (Set as Unknown if evaluating independently).
11. IMAGE DEPENDENCY: If requires image that is unavailable, NEEDS REVIEW.
12. MATHEMATICAL VALIDATION: Verify notation. Do not alter unless incorrect.
13. SCIENTIFIC VALIDATION: Check facts. Correct only when supported by established knowledge.
14. HISTORICAL VALIDATION: Verify facts. Preserve accepted exam standard.
15. POLITY & LAW VALIDATION: Verify legal facts and current status.
16. DIFFICULTY VALIDATION: Assign Very Easy, Easy, Medium, Hard, Very Hard based on NDA/CDS/AFCAT standards.
17. QUALITY SCORE: Assign a score (0-100) based on accuracy, readability, completeness, formatting.
18. FINAL DECISION: APPROVED, APPROVED WITH CORRECTIONS, NEEDS REVIEW, REJECTED. Provide justification.

## OUTPUT FORMAT
Return a raw JSON object (without markdown code blocks) representing the validated record:
{
  "question_id": "...",
  "validation_status": "...",
  "final_decision": "...",
  "subject": "...",
  "chapter": "...",
  "topic": "...",
  "question_text": "...",
  "options": {"A": "...", "B": "...", "C": "...", "D": "..."},
  "correct_answer": "...",
  "explanation": "...",
  "original_answer": "...",
  "corrections_made": "...",
  "duplicate_status": "...",
  "duplicate_reference_id": "...",
  "ocr_corrections": "...",
  "exam_relevance": ["..."],
  "syllabus_status": "...",
  "current_affairs_status": "...",
  "difficulty": "...",
  "quality_score": 0,
  "confidence": 0,
  "reviewer_notes": "..."
}

## GOLDEN RULES
Never invent missing info. Never generate new questions. Never change intent. Correct only verified errors. If confidence < 95%, NEEDS REVIEW. Reject paragraph/passage based questions. Preserve math notation. Prioritize examination accuracy.
"""

def validate_question_gemini(question_json_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_VALIDATION_PROMPT}\n\nHere is the question to validate:\n{question_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Validate and clean a question database using Gemini.")
    parser.add_argument("input_json", help="Path to the input JSON file containing questions")
    parser.add_argument("output_json", help="Path to the output JSON file for validated questions")
    parser.add_argument("--start", type=int, default=0, help="Start index (0-indexed)")
    parser.add_argument("--limit", type=int, default=None, help="Number of questions to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        questions = json.load(f)

    if not isinstance(questions, list):
        print("Error: Input JSON must be a list of questions.")
        return
        
    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(questions)
    end_idx = min(end_idx, len(questions))

    print(f"Processing {end_idx - start_idx} questions from index {start_idx} to {end_idx-1}...")

    # Load existing validated questions if they exist
    validated = []
    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                validated = json.load(f)
        except:
            pass

    for i in range(start_idx, end_idx):
        q = questions[i]
        print(f"\n--- Validating Question {i+1}/{len(questions)} ---")
        q_str = json.dumps(q, indent=2)
        
        result = validate_question_gemini(q_str)
        
        if result:
            validated.append(result)
            
            # Save incrementally
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(validated, f, indent=2)
                
            print(f"Status: {result.get('final_decision', 'UNKNOWN')} | Score: {result.get('quality_score', 'N/A')}")
        else:
            print(f"Failed to validate question {i}.")
        
        time.sleep(2) # Rate limiting protection

    print("\nValidation complete.")

if __name__ == "__main__":
    main()
