import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_GRAPH_PROMPT = """
# STAGE 5 — MASTER KNOWLEDGE GRAPH & RELATIONSHIP ENGINE PROMPT

## ROLE
You are an Expert Knowledge Graph Architect and Defence Examination Intelligence Engineer.
Your responsibility is to convert structured notes and validated questions into a connected Knowledge Graph that enables intelligent search, AI tutoring, adaptive revision, concept navigation, syllabus mapping, and personalized learning.
You are NOT generating new educational content. You are discovering and creating relationships between existing verified content.
Never invent relationships that are not supported by established academic knowledge.

## INPUT
You will receive a set of validated and enriched records (Questions and/or Notes).

## PRIMARY OBJECTIVE
Build an interconnected knowledge graph where every educational object becomes a searchable node connected through meaningful relationships.

## OUTPUT FORMAT
Return ONLY a raw JSON array containing the structured graph nodes (no markdown code blocks):
[
  {
    "node_id": "...",
    "node_type": "...",
    "canonical_name": "...",
    "aliases": ["..."],
    "description": "...",
    "parent_node": "...",
    "child_nodes": ["..."],
    "incoming_relationships": [{"source": "...", "type": "..."}],
    "outgoing_relationships": [{"target": "...", "type": "..."}],
    "prerequisites": ["..."],
    "successor_topics": ["..."],
    "related_concepts": ["..."],
    "related_questions": ["..."],
    "related_notes": ["..."],
    "related_formulae": ["..."],
    "related_diagrams": ["..."],
    "current_affairs_links": ["..."],
    "previous_year_links": ["..."],
    "exam_tags": ["..."],
    "difficulty_tags": ["..."],
    "keywords": ["..."],
    "confidence_score": 0,
    "needs_review_flag": false
  }
]

## GOLDEN RULES
Never create unsupported relationships. Use consistent naming conventions. Support fast semantic search. If confidence < 95%, set needs_review_flag to true.
"""

def build_graph_gemini(combined_json_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_GRAPH_PROMPT}\n\nHere are the records to process into graph nodes:\n{combined_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.1,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Build Knowledge Graph nodes from enriched questions and notes.")
    parser.add_argument("--questions", help="Path to enriched_questions.json")
    parser.add_argument("--notes", help="Path to enriched_notes.json")
    parser.add_argument("output_json", help="Path to the output JSON file for graph nodes")
    args = parser.parse_args()

    combined_data = []

    if args.questions and os.path.exists(args.questions):
        with open(args.questions, "r", encoding="utf-8") as f:
            questions = json.load(f)
            combined_data.extend([{"source_type": "question", "data": q} for q in questions])

    if args.notes and os.path.exists(args.notes):
        with open(args.notes, "r", encoding="utf-8") as f:
            notes = json.load(f)
            combined_data.extend([{"source_type": "note", "data": n} for n in notes])

    if not combined_data:
        print("Error: No input data provided. Specify --questions or --notes.")
        return

    print(f"Processing {len(combined_data)} records into the Knowledge Graph...")
    
    # In a real batch pipeline, we'd chunk this. For testing, we send it all.
    batch_str = json.dumps(combined_data, indent=2)
    
    result = build_graph_gemini(batch_str)
    
    if result:
        with open(args.output_json, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2)
            
        print(f"Successfully generated {len(result)} graph nodes.")
    else:
        print("Failed to generate knowledge graph.")

if __name__ == "__main__":
    main()
