import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    pass

def get_master_prompt():
    prompt_path = os.path.join(os.path.dirname(__file__), "KNOWLEDGE_SYNTHESIS_PROMPT.md")
    if os.path.exists(prompt_path):
        with open(prompt_path, "r", encoding="utf-8") as f:
            return f.read()
    return "Error: KNOWLEDGE_SYNTHESIS_PROMPT.md not found."

REQUIRED_JSON_SCHEMA = """
## OUTPUT FORMAT
Return ONLY a raw JSON object containing the enriched record (no markdown code blocks):
{
  "subject": "...",
  "chapter": "...",
  "subchapter": "...",
  "topic": "...",
  "subtopic": "...",
  "master_notes": "...",
  "revision_notes": "...",
  "one_liner_notes": ["..."],
  "key_facts": ["..."],
  "definitions": [{"term": "...", "exact_meaning": "...", "simplified_explanation": "..."}],
  "formulae": [{"formula": "...", "variables": "...", "application": "..."}],
  "tables": [{"title": "...", "content": "... (markdown format) ..."}],
  "diagram_descriptions": [{"title": "...", "description": "...", "labels": ["..."]}],
  "timelines": [{"event": "...", "date": "...", "description": "..."}],
  "comparison_tables": [{"title": "...", "content": "... (markdown format) ..."}],
  "mnemonics": ["..."],
  "common_exam_traps": ["..."],
  "previous_year_links": ["..."],
  "related_topics": ["..."],
  "search_keywords": ["..."],
  "beginner_explanation": "...",
  "intermediate_explanation": "...",
  "advanced_explanation": "...",
  "revision_priority": "...",
  "confidence_score": 0,
  "needs_review_flag": false
}
"""

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")

def enrich_notes_openrouter(notes_json_str, existing_chapter_content=""):
    if not OPENROUTER_API_KEY:
        print("Error: OPENROUTER_API_KEY not found in .env file.")
        return None
        
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }
    
    master_prompt = get_master_prompt()
    prompt_text = f"{master_prompt}\n\n{REQUIRED_JSON_SCHEMA}\n\nHere are the existing canonical chapter notes (DO NOT REPEAT THESE):\n{existing_chapter_content}\n\nHere are the raw NEW notes to evaluate and merge:\n{notes_json_str}"
    
    data = {
        "model": "meta-llama/llama-3.1-8b-instruct:free",
        "messages": [
            {"role": "system", "content": "You are a specialized JSON-only output assistant. You must ONLY output a valid JSON object matching the required schema. Do NOT include markdown blocks like ```json or any conversational text."},
            {"role": "user", "content": prompt_text}
        ],
        "temperature": 0.2
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "choices" in res_json and len(res_json["choices"]) > 0:
            text = res_json["choices"][0]["message"]["content"]
            # Clean up potential markdown formatting if the model disobeys
            text = text.strip()
            if text.startswith("```json"):
                text = text[7:]
            if text.startswith("```"):
                text = text[3:]
            if text.endswith("```"):
                text = text[:-3]
            text = text.strip()
            return json.loads(text)
        else:
            print("No output generated by OpenRouter.")
            return None
    except Exception as e:
        print(f"OpenRouter API Error: {e}")
        return None

def enrich_notes_gemini(notes_json_str, existing_chapter_content=""):
    if not GEMINI_API_KEY:
        return None
        
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    master_prompt = get_master_prompt()
    prompt_text = f"{master_prompt}\n\n{REQUIRED_JSON_SCHEMA}\n\nHere are the existing canonical chapter notes (DO NOT REPEAT THESE):\n{existing_chapter_content}\n\nHere are the raw NEW notes to evaluate and merge:\n{notes_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"Gemini API Error: {e}")
        return None

def enrich_notes(notes_json_str, existing_chapter_content=""):
    result = enrich_notes_gemini(notes_json_str, existing_chapter_content)
    if not result:
        print("Gemini failed. Falling back to OpenRouter...")
        result = enrich_notes_openrouter(notes_json_str, existing_chapter_content)
    return result

def main():
    parser = argparse.ArgumentParser(description="Enrich and format theory notes using Gemini (with OpenRouter fallback).")
    parser.add_argument("input_json", help="Path to the input JSON file containing raw notes")
    parser.add_argument("output_json", help="Path to the output JSON file for enriched notes")
    parser.add_argument("--start", type=int, default=0, help="Start index (0-indexed)")
    parser.add_argument("--limit", type=int, default=None, help="Number of notes to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        notes = json.load(f)

    if not isinstance(notes, list):
        print("Error: Input JSON must be a list of notes.")
        return
        
    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(notes)
    end_idx = min(end_idx, len(notes))

    print(f"Processing {end_idx - start_idx} notes from index {start_idx} to {end_idx-1}...")

    # Load existing enriched notes if they exist
    enriched = []
    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                enriched = json.load(f)
        except:
            pass

    for i in range(start_idx, end_idx):
        n = notes[i]
        print(f"\n--- Enriching Note {i+1}/{len(notes)} ---")
        n_str = json.dumps(n, indent=2)
        
        result = enrich_notes(n_str)
        
        if result:
            enriched.append(result)
            
            # Save incrementally
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(enriched, f, indent=2)
                
            print(f"Subject: {result.get('subject', 'UNKNOWN')} | Topic: {result.get('topic', 'UNKNOWN')}")
        else:
            print(f"Failed to enrich note {i}.")
        
        time.sleep(2) # Rate limiting protection

    print("\nNotes enrichment complete.")

if __name__ == "__main__":
    main()
