import os
import json
import time
import sys
import argparse
import requests
from dotenv import load_dotenv

load_dotenv()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

if not GEMINI_API_KEY:
    print("Error: GEMINI_API_KEY not found in .env file.")
    sys.exit(1)

MASTER_NOTES_ENRICHMENT_PROMPT = """
# STAGE 4 — MASTER NOTES REFINEMENT, ENRICHMENT & KNOWLEDGE BASE PROMPT

## ROLE
You are an Expert Defence Examination Educator, Instructional Designer, and Knowledge Architect.
Your responsibility is to convert validated theory extracted from books into a structured, searchable, exam-oriented knowledge base.
Your objective is to maximize understanding, retention, revision efficiency, and AI searchability without changing factual accuracy.
Never invent facts. If information is uncertain or incomplete, mark it as **Needs Review**.

## INPUT
Each record contains raw notes extracted during previous stages.

## PRIMARY OBJECTIVE
Transform each topic into multiple learning formats while preserving all important information.

## STEPS
1. CONTENT VALIDATION: Check completeness, flow, remove OCR leftovers.
2. STRUCTURE THE CONTENT: Subject -> Chapter -> Subchapter -> Topic -> Subtopic -> Concept.
3. MASTER EXAM NOTES: Produce comprehensive notes (Definitions, Background, Exceptions, Features, etc).
4. REVISION NOTES: Generate concise revision notes (highest-yield info, formulas, dates).
5. ONE-LINER NOTES: Convert topic into rapid revision bullets.
6. KEY FACTS: Extract most exam-relevant facts (Dates, Ranks, Ranges, Articles, etc).
7. FORMULAE & EQUATIONS: Extract and explain.
8. DEFINITIONS: Exact meaning, simplified explanation.
9. TABLES: Reconstruct cleanly.
10. DIAGRAMS: Title, description, labels, purpose.
11. TIMELINES: Generate chronological timelines.
12. COMPARISON TABLES: Generate useful comparisons.
13. MEMORY AIDS: Mnemonics, acronyms.
14. COMMON EXAM TRAPS: Identify frequent mistakes.
15. PREVIOUS YEAR LINKS: Identify frequently asked areas.
16. RELATED TOPICS: Prerequisites, related chapters.
17. SEARCH INDEX: Keywords, alternative names.
18. AI EXPLANATION BLOCKS: Beginner (simple), Intermediate (exam-oriented), Advanced (conceptual depth).
19. REVISION PRIORITY: Critical, High, Medium, Low.
20. OUTPUT FORMAT: Return structured knowledge record.

## OUTPUT FORMAT
Return ONLY a raw JSON object containing the enriched record (no markdown code blocks):
{
  "subject": "...",
  "chapter": "...",
  "subchapter": "...",
  "topic": "...",
  "subtopic": "...",
  "master_notes": "...",
  "revision_notes": "...",
  "one_liner_notes": ["..."],
  "key_facts": ["..."],
  "definitions": [{"term": "...", "exact_meaning": "...", "simplified_explanation": "..."}],
  "formulae": [{"formula": "...", "variables": "...", "application": "..."}],
  "tables": [{"title": "...", "content": "... (markdown format) ..."}],
  "diagram_descriptions": [{"title": "...", "description": "...", "labels": ["..."]}],
  "timelines": [{"event": "...", "date": "...", "description": "..."}],
  "comparison_tables": [{"title": "...", "content": "... (markdown format) ..."}],
  "mnemonics": ["..."],
  "common_exam_traps": ["..."],
  "previous_year_links": ["..."],
  "related_topics": ["..."],
  "search_keywords": ["..."],
  "beginner_explanation": "...",
  "intermediate_explanation": "...",
  "advanced_explanation": "...",
  "revision_priority": "...",
  "confidence_score": 0,
  "needs_review_flag": false
}

## GOLDEN RULES
Never change verified facts. Never invent information. Preserve technical terminology. Keep mathematical notation intact. Maintain a consistent structure.
"""

def enrich_notes_gemini(notes_json_str):
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key={GEMINI_API_KEY}"
    headers = {"Content-Type": "application/json"}
    
    prompt_text = f"{MASTER_NOTES_ENRICHMENT_PROMPT}\n\nHere are the raw notes to enrich:\n{notes_json_str}"
    
    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt_text}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.2,
            "response_mime_type": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status()
        res_json = response.json()
        
        if "candidates" in res_json and len(res_json["candidates"]) > 0:
            text = res_json["candidates"][0]["content"]["parts"][0]["text"]
            return json.loads(text)
        else:
            print("No output generated by Gemini.")
            return None
    except Exception as e:
        print(f"API Error: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Enrich and format theory notes using Gemini.")
    parser.add_argument("input_json", help="Path to the input JSON file containing raw notes")
    parser.add_argument("output_json", help="Path to the output JSON file for enriched notes")
    parser.add_argument("--start", type=int, default=0, help="Start index (0-indexed)")
    parser.add_argument("--limit", type=int, default=None, help="Number of notes to process")
    args = parser.parse_args()

    if not os.path.exists(args.input_json):
        print(f"File not found: {args.input_json}")
        return

    with open(args.input_json, "r", encoding="utf-8") as f:
        notes = json.load(f)

    if not isinstance(notes, list):
        print("Error: Input JSON must be a list of notes.")
        return
        
    start_idx = args.start
    end_idx = start_idx + args.limit if args.limit else len(notes)
    end_idx = min(end_idx, len(notes))

    print(f"Processing {end_idx - start_idx} notes from index {start_idx} to {end_idx-1}...")

    # Load existing enriched notes if they exist
    enriched = []
    if os.path.exists(args.output_json):
        try:
            with open(args.output_json, "r", encoding="utf-8") as f:
                enriched = json.load(f)
        except:
            pass

    for i in range(start_idx, end_idx):
        n = notes[i]
        print(f"\n--- Enriching Note {i+1}/{len(notes)} ---")
        n_str = json.dumps(n, indent=2)
        
        result = enrich_notes_gemini(n_str)
        
        if result:
            enriched.append(result)
            
            # Save incrementally
            with open(args.output_json, "w", encoding="utf-8") as f:
                json.dump(enriched, f, indent=2)
                
            print(f"Subject: {result.get('subject', 'UNKNOWN')} | Topic: {result.get('topic', 'UNKNOWN')}")
        else:
            print(f"Failed to enrich note {i}.")
        
        time.sleep(2) # Rate limiting protection

    print("\nNotes enrichment complete.")

if __name__ == "__main__":
    main()
