// notes_extra_physics_rich.js - Auto-generated rich HTML notes for physics
window.EXPANDED_NOTES_DATA = window.EXPANDED_NOTES_DATA || {};

window.EXPANDED_NOTES_DATA["reflection-refraction"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Reflection, Refraction & Lenses
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Reflection</b> occurs when light bounces back into the same medium after hitting a surface, governed by the law that the angle of incidence equals the angle of reflection. <b>Refraction</b> is the bending of light as it passes from one optical medium to another of different density, described by [[Snell's Law]]. The <b>Refractive Index</b> determines the speed of light in a medium relative to a vacuum. Understanding these principles is crucial for analyzing how images are formed by <b>Spherical Mirrors</b> (Concave and Convex) and <b>Lenses</b>, which are fundamental to optical instruments used in defence surveillance.</p><p>The mechanism of refraction leads to phenomena like <b>Total Internal Reflection (TIR)</b>, which occurs when light travels from a denser to a rarer medium at an angle greater than the <b>Critical Angle</b>. This is the core principle behind <b>Optical Fibres</b> used in secure military communications. Lenses are categorized as <b>Converging (Convex)</b> and <b>Diverging (Concave)</b>. The <b>Lens Maker's Formula</b> and the <b>Mirror Formula</b> allow for the precise calculation of focal length and image distance, essential for designing telescopes and binoculars used in reconnaissance.</p><p>The significance of these concepts extends to <b>Atmospheric Refraction</b>, causing the twinkling of stars and the apparent position of the sun during sunrise/sunset. In defence, the application of these laws enables the creation of <b>Periscopes</b> for submarines and high-precision <b>Laser-guided systems</b>. Mastery of these topics is essential for the Physics section of NDA/CDS/AFCAT, as they frequently test the relationship between focal length, power, and image characteristics.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Concave Mirror</td><td style='border:1px solid var(--border);padding:8px;'>Converging mirror; can form real/inverted or virtual/erect images.</td><td style='border:1px solid var(--border);padding:8px;'>Used as shaving mirrors or in car headlights.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Convex Mirror</td><td style='border:1px solid var(--border);padding:8px;'>Diverging mirror; always forms virtual, erect, and diminished images.</td><td style='border:1px solid var(--border);padding:8px;'>Used as rear-view mirrors for wide field of view.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Convex Lens</td><td style='border:1px solid var(--border);padding:8px;'>Converging lens; focal point is real.</td><td style='border:1px solid var(--border);padding:8px;'>Corrects Hypermetropia (far-sightedness).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Concave Lens</td><td style='border:1px solid var(--border);padding:8px;'>Diverging lens; focal point is virtual.</td><td style='border:1px solid var(--border);padding:8px;'>Corrects Myopia (near-sightedness).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Refractive Index</td><td style='border:1px solid var(--border);padding:8px;'>Ratio of speed of light in vacuum to speed in medium (n = c/v).</td><td style='border:1px solid var(--border);padding:8px;'>Dimensionless quantity; always &ge; 1.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Power of Lens</td><td style='border:1px solid var(--border);padding:8px;'>Reciprocal of focal length in meters (P = 1/f). Unit: Dioptre (D).</td><td style='border:1px solid var(--border);padding:8px;'>Positive for Convex, Negative for Concave.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Critical Angle</td><td style='border:1px solid var(--border);padding:8px;'>Angle of incidence for which angle of refraction is 90&deg;.</td><td style='border:1px solid var(--border);padding:8px;'>Necessary condition for Total Internal Reflection.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>V-E-D</strong>: Convex Mirrors are <b>V</b>irtual, <b>E</b>rect, and <b>D</b>iminished.</li><li><strong>C-C-M</strong>: <b>C</b>oncave lens <b>C</b>orrects <b>M</b>yopia.</li><li><strong>V-C-H</strong>: <b>V</b>ex (Convex) lens <b>C</b>orrects <b>H</b>ypermetropia.</li><li><strong>S-N-L</strong>: <b>S</b>nell's law relates <b>N</b>-index and <b>L</b>ight bending.</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. Light travels fastest in a vacuum (3&times;10<sup>8</sup> m/s).</li><li><span style='color:var(--warning)'>2</span>. For a plane mirror, the image is always virtual, erect, and laterally inverted.</li><li><span style='color:var(--warning)'>3</span>. The focal length of a spherical mirror is half its radius of curvature (f = R/2).</li><li><span style='color:var(--warning)'>4</span>. Total Internal Reflection requires light to travel from a denser to a rarer medium.</li><li><span style='color:var(--warning)'>5</span>. Mirage is an optical illusion caused by atmospheric refraction and TIR.</li><li><span style='color:var(--warning)'>6</span>. The power of a combination of lenses is the algebraic sum of individual powers (P = P1 + P2).</li><li><span style='color:var(--warning)'>7</span>. Myopia is caused by an elongated eyeball or excessive curvature of the lens.</li><li><span style='color:var(--warning)'>8</span>. Hypermetropia is caused by a shortened eyeball or focal length that is too long.</li><li><span style='color:var(--warning)'>9</span>. A lens placed in a medium with the same refractive index becomes invisible.</li><li><span style='color:var(--warning)'>10</span>. The speed of light decreases as the refractive index of the medium increases.</li><li><span style='color:var(--warning)'>11</span>. Dispersion is the splitting of white light into seven colors (VIBGYOR) through a prism.</li><li><span style='color:var(--warning)'>12</span>. The image formed by a convex mirror is always virtual, regardless of object position.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["newtons-laws"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Newton's Laws of Motion
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p>Newton's Laws of Motion, formulated by [[Isaac Newton]], form the bedrock of <b>Classical Mechanics</b>. These laws describe the relationship between a body, the forces acting upon it, and its motion in response to those forces. The <b>First Law</b> introduces the concept of <b>Inertia</b>, stating that an object remains at rest or in uniform motion unless acted upon by an external force. This establishes the framework for <b>Inertial Reference Frames</b>, which are critical for solving complex kinematics problems in NDA and CDS physics sections.</p><p>The <b>Second Law</b> provides the quantitative definition of force, expressed as <b>F = ma</b>, where force is proportional to the rate of change of <b>Linear Momentum</b>. This law explains how acceleration occurs in a specific direction when a net force is applied. The <b>Third Law</b> posits that for every action, there is an <b>Equal and Opposite Reaction</b>. This mechanism is fundamental to understanding propulsion, such as the lift-off of rockets or the recoil of a gun, which are frequent themes in AFCAT and CDS technical questions.</p><p>The significance of these laws lies in their universal applicability to macroscopic objects. They allow engineers and military strategists to calculate <b>Ballistics</b>, structural integrity, and vehicle dynamics. Understanding these laws is essential for mastering subsequent topics like <b>Work-Energy Theorem</b> and <b>Circular Motion</b>, ensuring a comprehensive grasp of the physical world for defence aspirants.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Inertia</td><td style='border:1px solid var(--border);padding:8px;'>Resistance of any physical object to any change in its velocity.</td><td style='border:1px solid var(--border);padding:8px;'>Remember: Mass is a measure of inertia.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Momentum</td><td style='border:1px solid var(--border);padding:8px;'>Product of mass and velocity (p = mv).</td><td style='border:1px solid var(--border);padding:8px;'>Vector quantity; direction is same as velocity.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Net Force</td><td style='border:1px solid var(--border);padding:8px;'>Vector sum of all forces acting on a body.</td><td style='border:1px solid var(--border);padding:8px;'>If Net Force = 0, object is in equilibrium.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Impulse</td><td style='border:1px solid var(--border);padding:8px;'>Change in momentum (Force × time).</td><td style='border:1px solid var(--border);padding:8px;'>Area under Force-Time graph.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Friction</td><td style='border:1px solid var(--border);padding:8px;'>Opposing force acting between two surfaces in contact.</td><td style='border:1px solid var(--border);padding:8px;'>Static friction is always higher than kinetic.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Tension</td><td style='border:1px solid var(--border);padding:8px;'>Pulling force transmitted through a string/cable.</td><td style='border:1px solid var(--border);padding:8px;'>Assumed constant in ideal massless strings.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Normal Force</td><td style='border:1px solid var(--border);padding:8px;'>Perpendicular force exerted by a surface.</td><td style='border:1px solid var(--border);padding:8px;'>Always acts 90 degrees to the surface.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>I-R-A</strong>: <b>I</b>nertia (1st), <b>R</b>ate of change/Force (2nd), <b>A</b>ction-Reaction (3rd).</li><li><strong>M-A-F</strong>: <b>M</b>ass times <b>A</b>cceleration equals <b>F</b>orce.</li><li><strong>P-M-V</strong>: <b>P</b>ressure/Momentum is <b>M</b>ass times <b>V</b>elocity.</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. Newton's First Law is qualitatively known as the Law of Inertia.</li><li><span style='color:var(--warning)'>2</span>. Force is a vector quantity measured in Newtons (1 N = 1 kg·m/s²).</li><li><span style='color:var(--warning)'>3</span>. The Second Law is the 'real' law of motion as the first and third can be derived from it.</li><li><span style='color:var(--warning)'>4</span>. Momentum is conserved in an isolated system (Law of Conservation of Momentum).</li><li><span style='color:var(--warning)'>5</span>. Action and reaction forces always act on <b>different</b> bodies, never on the same body.</li><li><span style='color:var(--warning)'>6</span>. Inertia depends solely on the mass of the object, not its velocity.</li><li><span style='color:var(--warning)'>7</span>. A body in equilibrium has a net force of zero, but may still be moving at constant velocity.</li><li><span style='color:var(--warning)'>8</span>. Apparent weight in a lift increases during upward acceleration and decreases during downward acceleration.</li><li><span style='color:var(--warning)'>9</span>. The unit of Impulse is Newton-second (N·s) or kg·m/s.</li><li><span style='color:var(--warning)'>10</span>. Friction is a self-adjusting force up to the limit of limiting friction.</li><li><span style='color:var(--warning)'>11</span>. Centripetal force is not a new force but a requirement for circular motion provided by other forces.</li><li><span style='color:var(--warning)'>12</span>. Newton's laws fail at relativistic speeds (near speed of light) and quantum scales.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["syl-exercises"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Work, Power, Energy & Gravitation
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Work</b> is defined as the product of force and displacement in the direction of the force, while <b>Energy</b> is the capacity to do work. In the context of Indian defence exams, understanding the <b>Work-Energy Theorem</b> is crucial, as it links the net work done on an object to its change in <b>Kinetic Energy</b>. Energy exists in various forms, primarily <b>Potential Energy</b> (stored energy due to position) and Kinetic Energy (energy of motion). The <b>Law of Conservation of Energy</b> states that energy cannot be created or destroyed, only transformed from one form to another, a principle fundamental to ballistics and aerospace engineering.</p><p><b>Power</b> is the rate at which work is performed, measured in Watts (W). Moving to <b>Gravitation</b>, [[Isaac Newton]] formulated the <b>Universal Law of Gravitation</b>, stating that every mass attracts every other mass with a force proportional to the product of their masses and inversely proportional to the square of the distance between them. This governs the motion of satellites and planetary bodies. Key concepts include <b>Escape Velocity</b> (the minimum speed needed to break free from a gravitational field) and <b>Orbital Velocity</b>, which are critical for understanding missile trajectories and satellite deployment by organizations like [[ISRO]].</p><p>The synergy between these concepts allows for the calculation of <b>Mechanical Energy</b> in complex systems. For NDA/CDS aspirants, mastering the relationship between <b>Gravitational Potential Energy</b> and the <b>Inverse Square Law</b> is essential. These principles explain everything from the falling of an apple to the orbits of the Moon and artificial satellites, forming the bedrock of classical mechanics and strategic military calculations involving altitude and velocity.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Work (W)</td><td style='border:1px solid var(--border);padding:8px;'>W = Fd cosθ; Unit: Joule (J)</td><td style='border:1px solid var(--border);padding:8px;'>Work is zero if force is perpendicular to displacement.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Kinetic Energy</td><td style='border:1px solid var(--border);padding:8px;'>KE = 1/2 mv²</td><td style='border:1px solid var(--border);padding:8px;'>KE depends on the square of velocity; doubling v quadruples KE.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Potential Energy</td><td style='border:1px solid var(--border);padding:8px;'>PE = mgh (Gravitational)</td><td style='border:1px solid var(--border);padding:8px;'>PE is relative to a chosen reference level (datum).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Power (P)</td><td style='border:1px solid var(--border);padding:8px;'>P = W/t or P = Fv</td><td style='border:1px solid var(--border);padding:8px;'>1 Horsepower (hp) = 746 Watts.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Gravitational Constant</td><td style='border:1px solid var(--border);padding:8px;'>G = 6.674 × 10⁻¹¹ N m²/kg²</td><td style='border:1px solid var(--border);padding:8px;'>G is universal; 'g' (acceleration) varies by location.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Escape Velocity</td><td style='border:1px solid var(--border);padding:8px;'>Ve = √(2GM/R)</td><td style='border:1px solid var(--border);padding:8px;'>For Earth, Ve is approx 11.2 km/s.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Orbital Velocity</td><td style='border:1px solid var(--border);padding:8px;'>Vo = √(GM/R)</td><td style='border:1px solid var(--border);padding:8px;'>Vo = Ve / √2.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Kepler's 3rd Law</td><td style='border:1px solid var(--border);padding:8px;'>T² ∝ r³</td><td style='border:1px solid var(--border);padding:8px;'>Square of period is proportional to cube of semi-major axis.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>W-F-D</strong>: <b>W</b>ork is <b>F</b>orce <b>D</b>isplaced (W=Fd).</li><li><strong>P-W-T</strong>: <b>P</b>ower is <b>W</b>ork over <b>T</b>ime (P=W/t).</li><li><strong>G-M-R</strong>: <b>G</b>ravitation depends on <b>M</b>ass and <b>R</b>adius (Inverse Square Law).</li><li><strong>K-V-S</strong>: <b>K</b>inetic energy is <b>V</b>elocity <b>S</b>quared (KE ∝ v²).</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. Work done by a centripetal force is always zero because force is perpendicular to motion.</li><li><span style='color:var(--warning)'>2</span>. The value of 'g' decreases as we go higher above the Earth's surface or deeper into the Earth.</li><li><span style='color:var(--warning)'>3</span>. A geostationary satellite has an orbital period of 24 hours and orbits in the equatorial plane.</li><li><span style='color:var(--warning)'>4</span>. Energy is a scalar quantity, whereas force and displacement are vectors.</li><li><span style='color:var(--warning)'>5</span>. The weight of an object is maximum at the poles and minimum at the equator.</li><li><span style='color:var(--warning)'>6</span>. Conservation of Mechanical Energy: Total Energy = KE + PE = Constant (in absence of friction).</li><li><span style='color:var(--warning)'>7</span>. Escape velocity does not depend on the mass of the escaping object.</li><li><span style='color:var(--warning)'>8</span>. 1 Joule is equal to 1 Newton-meter (N·m).</li><li><span style='color:var(--warning)'>9</span>. The gravitational force between two objects is always attractive, never repulsive.</li><li><span style='color:var(--warning)'>10</span>. Power is the dot product of Force and Velocity vectors (P = F · v).</li><li><span style='color:var(--warning)'>11</span>. At the center of the Earth, the value of acceleration due to gravity (g) is zero.</li><li><span style='color:var(--warning)'>12</span>. The work done by friction is generally negative as it opposes the direction of motion.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-sound"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Sound Waves & Acoustics
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Sound waves</b> are longitudinal mechanical waves that require a medium (solid, liquid, or gas) for propagation, meaning they cannot travel through a vacuum. They consist of <b>compressions</b> (high pressure) and <b>rarefactions</b> (low pressure). The speed of sound depends heavily on the elasticity and density of the medium, typically traveling fastest in solids and slowest in gases. Key concepts include <b>Frequency</b> (pitch), <b>Amplitude</b> (loudness), and <b>Wavelength</b>. The study of sound is governed by the laws of acoustics, often involving [[Newton]] and [[Laplace]] in the derivation of sound speed in air.</p><p>The mechanism of sound involves the <b>Doppler Effect</b>, where the observed frequency changes as the source or observer moves. Another critical phenomenon is <b>Resonance</b>, occurring when a system is driven at its natural frequency, leading to large amplitude oscillations. Sound also exhibits <b>Reflection</b> (echoes), <b>Refraction</b> (bending due to temperature gradients), and <b>Diffraction</b> (bending around corners). In underwater acoustics, <b>SONAR</b> (Sound Navigation and Ranging) utilizes ultrasonic waves to detect submerged objects by measuring the time delay of reflected pulses.</p><p>For defence aspirants, understanding acoustics is vital for mastering <b>Radar/Sonar</b> technology and communication systems. The distinction between <b>Infrasonic</b> (<20Hz), <b>Audible</b> (20Hz-20kHz), and <b>Ultrasonic</b> (>20kHz) ranges is a frequent exam theme. Mastery of these concepts explains how sound behaves in different atmospheric layers, affecting long-range acoustic communication and stealth technologies used in naval warfare.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Longitudinal Wave</td><td style='border:1px solid var(--border);padding:8px;'>Particles move parallel to wave direction.</td><td style='border:1px solid var(--border);padding:8px;'>Contrast with Transverse waves (perpendicular).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Speed of Sound</td><td style='border:1px solid var(--border);padding:8px;'>V = sqrt(B/rho) where B is bulk modulus.</td><td style='border:1px solid var(--border);padding:8px;'>Increases with Temperature and Elasticity.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Doppler Effect</td><td style='border:1px solid var(--border);padding:8px;'>Apparent change in frequency due to relative motion.</td><td style='border:1px solid var(--border);padding:8px;'>Frequency increases as source approaches.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Mach Number</td><td style='border:1px solid var(--border);padding:8px;'>Ratio of object speed to speed of sound.</td><td style='border:1px solid var(--border);padding:8px;'>Mach > 1 is Supersonic; Mach > 5 is Hypersonic.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Echo</td><td style='border:1px solid var(--border);padding:8px;'>Reflection of sound from a distant surface.</td><td style='border:1px solid var(--border);padding:8px;'>Min distance for echo is approx 17.2m.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Ultrasonics</td><td style='border:1px solid var(--border);padding:8px;'>Frequencies above 20,000 Hz.</td><td style='border:1px solid var(--border);padding:8px;'>Used in SONAR and medical imaging.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Resonance</td><td style='border:1px solid var(--border);padding:8px;'>Matching external frequency with natural frequency.</td><td style='border:1px solid var(--border);padding:8px;'>Leads to maximum amplitude of vibration.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>S-L-G</strong>: <strong>S</strong>olids > <strong>L</strong>iquids > <strong>G</strong>ases (Order of sound speed).</li><li><strong>F-A-W</strong>: <strong>F</strong>requency is Pitch, <strong>A</strong>mplitude is Loudness, <strong>W</strong>avelength is Distance.</li><li><strong>D-O-P-P-L-E-R</strong>: <strong>D</strong>irection <strong>O</strong>f <strong>P</strong>article <strong>P</strong>ushes <strong>L</strong>istener's <strong>E</strong>ar <strong>R</strong>esponse.</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. Sound cannot travel through a vacuum; it is a mechanical wave.</li><li><span style='color:var(--warning)'>2</span>. Speed of sound in air at 0°C is approximately 331 m/s.</li><li><span style='color:var(--warning)'>3</span>. Speed of sound increases by 0.61 m/s for every 1°C rise in temperature.</li><li><span style='color:var(--warning)'>4</span>. Humidity increases the speed of sound because moist air is less dense than dry air.</li><li><span style='color:var(--warning)'>5</span>. The human audible range is 20 Hz to 20,000 Hz.</li><li><span style='color:var(--warning)'>6</span>. Intensity of sound is measured in Decibels (dB), a logarithmic scale.</li><li><span style='color:var(--warning)'>7</span>. SONAR uses ultrasonic waves to map the ocean floor or detect submarines.</li><li><span style='color:var(--warning)'>8</span>. A sonic boom occurs when an object breaks the sound barrier (Mach 1).</li><li><span style='color:var(--warning)'>9</span>. Sound waves are longitudinal, while light waves are transverse.</li><li><span style='color:var(--warning)'>10</span>. The pitch of a sound is directly proportional to its frequency.</li><li><span style='color:var(--warning)'>11</span>. Quality or Timbre allows us to distinguish between two sounds of the same pitch and loudness.</li><li><span style='color:var(--warning)'>12</span>. Sound travels fastest in steel/iron compared to water or air.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-em-waves"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Electromagnetic Waves & Spectrum
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Electromagnetic (EM) Waves</b> are synchronized oscillations of <b>electric and magnetic fields</b> that propagate through a vacuum at the speed of light (approximately 3 x 10<sup>8</sup> m/s). Unlike mechanical waves, they require no medium for transmission. These waves are <b>transverse</b> in nature, meaning the oscillations are perpendicular to the direction of energy transfer. The EM spectrum is a continuous range of all possible frequencies, categorized by wavelength and energy, ranging from low-frequency <b>Radio waves</b> to high-energy <b>Gamma rays</b>. [[James Clerk Maxwell]] formulated the mathematical theory that unified electricity and magnetism.</p><p>The mechanism of EM waves involves the <b>mutual induction</b> of electric and magnetic fields; a changing electric field creates a magnetic field, and vice versa. The spectrum is divided into several bands: <b>Radio, Microwave, Infrared, Visible Light, Ultraviolet, X-rays, and Gamma rays</b>. As frequency increases, the wavelength decreases, and the energy of the photons increases according to the formula <b>E = hf</b>. This relationship is critical for understanding how different waves interact with matter, such as how X-rays penetrate soft tissue but are stopped by bone.</p><p>For defence aspirants, understanding the EM spectrum is vital for grasping <b>Radar (Radio Detection and Ranging)</b>, satellite communication, and night-vision technology. The ability to manipulate specific frequencies allows for stealth technology and secure encrypted communications. Mastery of these concepts is essential for the Physics section of <b>NDA, CDS, and AFCAT</b>, particularly regarding wave properties and their practical applications in modern warfare.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Radio Waves</td><td style='border:1px solid var(--border);padding:8px;'>Longest wavelength, lowest frequency; used in AM/FM and TV.</td><td style='border:1px solid var(--border);padding:8px;'>Remember: Lowest energy in spectrum.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>Microwaves</td><td style='border:1px solid var(--border);padding:8px;'>Used in Radar and satellite communication (point-to-point).</td><td style='border:1px solid var(--border);padding:8px;'>Key for Radar-related questions.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>Infrared (IR)</td><td style='border:1px solid var(--border);padding:8px;'>Associated with heat; used in night vision and remote controls.</td><td style='border:1px solid var(--border);padding:8px;'>Known as 'Heat Waves'.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>Visible Light</td><td style='border:1px solid var(--border);padding:8px;'>Smallest band; ranges from Violet (shortest) to Red (longest).</td><td style='border:1px solid var(--border);padding:8px;'>VIBGYOR sequence is essential.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>Ultraviolet (UV)</td><td style='border:1px solid var(--border);padding:8px;'>Higher energy than visible; causes tanning and sterilization.</td><td style='border:1px solid var(--border);padding:8px;'>Blocked by the Ozone layer.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>X-Rays</td><td style='border:1px solid var(--border);padding:8px;'>High penetration; used in medical imaging and security scans.</td><td style='border:1px solid var(--border);padding:8px;'>Discovered by Roentgen.</td></tr><tr style='border:1px solid var(--border);padding:8px;'><td style='border:1px solid var(--border);padding:8px;'>Gamma Rays</td><td style='border:1px solid var(--border);padding:8px;'>Shortest wavelength, highest energy; emitted by nuclei.</td><td style='border:1px solid var(--border);padding:8px;'>Most penetrating EM radiation.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>Raging Martians Invaded Venus Using X-ray Guns</strong>: Radio, Microwave, Infrared, Visible, Ultraviolet, X-ray, Gamma (Order of increasing frequency).</li><li><strong>VIBGYOR</strong>: Violet, Indigo, Blue, Green, Yellow, Orange, Red (Order of decreasing frequency/increasing wavelength).</li><li><strong>E = hf</strong>: Energy equals Planck's constant times frequency (Direct proportionality).</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. All EM waves travel at the speed of light (c = 3 x 10<sup>8</sup> m/s) in a vacuum.</li><li><span style='color:var(--warning)'>2</span>. The relationship between speed, frequency, and wavelength is c = λf.</li><li><span style='color:var(--warning)'>3</span>. EM waves are transverse waves; they do not require a medium to propagate.</li><li><span style='color:var(--warning)'>4</span>. Gamma rays have the highest frequency and the shortest wavelength.</li><li><span style='color:var(--warning)'>5</span>. Radio waves have the lowest frequency and the longest wavelength.</li><li><span style='color:var(--warning)'>6</span>. The energy of an EM wave is directly proportional to its frequency.</li><li><span style='color:var(--warning)'>7</span>. Visible light is a very narrow band of the EM spectrum (approx. 400nm to 700nm).</li><li><span style='color:var(--warning)'>8</span>. Radar operates primarily using Microwaves due to their ability to reflect off metallic objects.</li><li><span style='color:var(--warning)'>9</span>. Infrared radiation is primarily sensed by thermal imaging cameras used in defence.</li><li><span style='color:var(--warning)'>10</span>. X-rays and Gamma rays are ionizing radiations, meaning they can remove electrons from atoms.</li><li><span style='color:var(--warning)'>11</span>. The speed of EM waves decreases when they enter a denser medium (like glass or water).</li><li><span style='color:var(--warning)'>12</span>. Polarization is a property exclusive to transverse waves, including all EM waves.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-heat"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Thermodynamics & Heat Transfer
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Thermodynamics</b> is the branch of physics dealing with the relationships between heat, work, temperature, and energy. It is governed by fundamental laws that dictate how energy transforms from one form to another. The <b>Zeroth Law</b> establishes the concept of temperature, while the <b>First Law</b> is a statement of the [[Law of Conservation of Energy]], asserting that energy cannot be created or destroyed. Key concepts include <b>Internal Energy</b>, <b>Enthalpy</b>, and <b>Entropy</b>, which are critical for understanding the efficiency of heat engines and refrigerators used in military aviation and naval propulsion.</p><p>Heat transfer occurs via three primary mechanisms: <b>Conduction</b> (direct contact in solids), <b>Convection</b> (fluid movement), and <b>Radiation</b> (electromagnetic waves). The <b>Second Law of Thermodynamics</b> introduces the concept of <b>Entropy</b>, stating that the total entropy of an isolated system always increases over time, implying that heat naturally flows from a hotter body to a colder one. The <b>Carnot Cycle</b> represents the theoretical maximum efficiency any heat engine can achieve, serving as a benchmark for real-world internal combustion engines and turbines.</p><p>For defence aspirants, mastering these concepts is vital for understanding <b>Aerodynamics</b>, jet engine thrust, and thermal shielding for missiles. The ability to calculate <b>Heat Flux</b> and understand <b>Thermal Conductivity</b> is essential for designing cooling systems in high-performance aircraft and submarines, ensuring structural integrity under extreme thermal stress during supersonic flight or deep-sea operations.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Isothermal Process</td><td style='border:1px solid var(--border);padding:8px;'>Process occurring at constant temperature; ΔT = 0.</td><td style='border:1px solid var(--border);padding:8px;'>Work done is maximum in this process.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Adiabatic Process</td><td style='border:1px solid var(--border);padding:8px;'>No heat exchange between system and surroundings (Q = 0).</td><td style='border:1px solid var(--border);padding:8px;'>Common in rapid compression/expansion (e.g., diesel engines).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Isobaric Process</td><td style='border:1px solid var(--border);padding:8px;'>Process occurring at constant pressure.</td><td style='border:1px solid var(--border);padding:8px;'>Work done = P(V2 - V1).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Isochoric Process</td><td style='border:1px solid var(--border);padding:8px;'>Process occurring at constant volume; Work done = 0.</td><td style='border:1px solid var(--border);padding:8px;'>All heat added increases internal energy.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Stefan-Boltzmann Law</td><td style='border:1px solid var(--border);padding:8px;'>Total energy radiated per unit area is proportional to T^4.</td><td style='border:1px solid var(--border);padding:8px;'>Crucial for calculating blackbody radiation.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Specific Heat Capacity</td><td style='border:1px solid var(--border);padding:8px;'>Heat required to raise 1kg of substance by 1 Kelvin.</td><td style='border:1px solid var(--border);padding:8px;'>Water has a very high specific heat capacity.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Entropy</td><td style='border:1px solid var(--border);padding:8px;'>Measure of disorder or randomness in a system.</td><td style='border:1px solid var(--border);padding:8px;'>Always increases in spontaneous processes.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>C-C-R</strong>: <b>C</b>onduction (Contact), <b>C</b>onvection (Currents/Fluids), <b>R</b>adiation (Rays/Vacuum).</li><li><strong>I-A-I-I</strong>: Isothermal (Temp), Adiabatic (Heat), Isobaric (Pressure), Isochoric (Volume) - The 'Iso' family of processes.</li><li><strong>S-B-L</strong>: <b>S</b>tefan-<b>B</b>oltzmann <b>L</b>aw relates Energy to Temperature to the power of 4 (T^4).</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. The First Law of Thermodynamics is expressed as ΔU = Q - W.</li><li><span style='color:var(--warning)'>2</span>. Absolute Zero (0 Kelvin) is the temperature at which molecular motion ceases.</li><li><span style='color:var(--warning)'>3</span>. Thermal conductivity is highest in metals (e.g., Silver, Copper) and lowest in gases.</li><li><span style='color:var(--warning)'>4</span>. A Carnot engine is a theoretical ideal engine with no friction or heat loss.</li><li><span style='color:var(--warning)'>5</span>. In an adiabatic process, the relation is PV^γ = constant, where γ is the adiabatic index.</li><li><span style='color:var(--warning)'>6</span>. Wien's Displacement Law states that λmaxT = constant (peak wavelength shifts with temperature).</li><li><span style='color:var(--warning)'>7</span>. Heat transfer by radiation does not require a medium and travels at the speed of light.</li><li><span style='color:var(--warning)'>8</span>. The efficiency of a heat engine is given by η = 1 - (T_cold / T_hot).</li><li><span style='color:var(--warning)'>9</span>. Specific heat of water is 4186 J/kg·K, making it an excellent coolant.</li><li><span style='color:var(--warning)'>10</span>. Latent heat is the energy absorbed/released during a phase change without changing temperature.</li><li><span style='color:var(--warning)'>11</span>. The Zeroth Law provides the basis for the thermometer.</li><li><span style='color:var(--warning)'>12</span>. Entropy of the universe is constantly increasing according to the 2nd Law.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-electricity-magnetism"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Electricity, Circuits & Magnetism
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Electricity</b> is the flow of electric charge, primarily electrons, through a conductor. In the context of defence exams, understanding <b>Ohm's Law</b> (V=IR) and the distinction between <b>Direct Current (DC)</b> and <b>Alternating Current (AC)</b> is fundamental. The study of circuits involves analyzing <b>Series</b> and <b>Parallel</b> connections, where resistance behaves differently. Key concepts include <b>Electromotive Force (EMF)</b>, the potential difference provided by a source like a battery, and the role of [[Alessandro Volta]] in developing the first chemical battery, which paved the way for modern electronics.</p><p><b>Magnetism</b> and electricity are intrinsically linked through <b>Electromagnetism</b>. [[Hans Christian Ørsted]] discovered that an electric current creates a magnetic field, while [[Michael Faraday]] demonstrated <b>Electromagnetic Induction</b>, showing that a changing magnetic field induces an electric current. This mechanism is the basis for <b>Electric Generators</b> and <b>Transformers</b>. The <b>Right-Hand Thumb Rule</b> and <b>Fleming's Left-Hand Rule</b> are critical for determining the direction of force and current in motors, which are essential for radar and communication systems used by the Armed Forces.</p><p>The significance of these principles lies in their application to <b>Avionics</b>, <b>Sonar</b>, and <b>Weaponry</b>. From the simple operation of a fuse to the complex circuitry of a fighter jet's fly-by-wire system, these physics laws ensure operational efficiency. For NDA/CDS candidates, mastering the relationship between <b>Magnetic Flux</b> and <b>Inductance</b> is vital for solving numerical problems related to power transmission and electromagnetic waves.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Ohm's Law</td><td style='border:1px solid var(--border);padding:8px;'>V = IR; Current is proportional to voltage at constant temperature.</td><td style='border:1px solid var(--border);padding:8px;'>Check units: V (Volts), I (Amperes), R (Ohms).</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Kirchhoff's Laws</td><td style='border:1px solid var(--border);padding:8px;'>KCL (Charge conservation) and KVL (Energy conservation).</td><td style='border:1px solid var(--border);padding:8px;'>KCL applies to junctions; KVL to closed loops.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Resistors in Series</td><td style='border:1px solid var(--border);padding:8px;'>Req = R1 + R2 + ...; Current remains constant.</td><td style='border:1px solid var(--border);padding:8px;'>Total resistance always increases.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Resistors in Parallel</td><td style='border:1px solid var(--border);padding:8px;'>1/Req = 1/R1 + 1/R2 + ...; Voltage remains constant.</td><td style='border:1px solid var(--border);padding:8px;'>Total resistance is less than the smallest resistor.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Faraday's Law</td><td style='border:1px solid var(--border);padding:8px;'>Induced EMF is proportional to the rate of change of magnetic flux.</td><td style='border:1px solid var(--border);padding:8px;'>Crucial for Generator/Transformer questions.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Lenz's Law</td><td style='border:1px solid var(--border);padding:8px;'>Induced current opposes the change that produced it.</td><td style='border:1px solid var(--border);padding:8px;'>Based on the Law of Conservation of Energy.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Magnetic Flux</td><td style='border:1px solid var(--border);padding:8px;'>Φ = B * A * cos(θ); Unit: Weber (Wb).</td><td style='border:1px solid var(--border);padding:8px;'>Max flux when field is perpendicular to area.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Transformer</td><td style='border:1px solid var(--border);padding:8px;'>Changes AC voltage via mutual induction (Vs/Vp = Ns/Np).</td><td style='border:1px solid var(--border);padding:8px;'>Does NOT work with DC current.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>V-I-R Triangle</strong>: Imagine a triangle with V on top and I, R at bottom. To find V, multiply I*R; to find I, divide V/R.</li><li><strong>Lenz's 'L' for 'Limit'</strong>: Lenz's law acts to 'limit' or oppose the change in flux.</li><li><strong>Right-Hand Rule (Thumb)</strong>: Thumb = Current, Fingers = Magnetic Field (Curl).</li><li><strong>Parallel = Path</strong>: Parallel circuits provide multiple 'paths' for current, reducing overall resistance.</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. The resistivity of a conductor increases with an increase in temperature (for metals).</li><li><span style='color:var(--warning)'>2</span>. Superconductors have zero electrical resistance at very low critical temperatures.</li><li><span style='color:var(--warning)'>3</span>. An Ammeter is always connected in series (low resistance), while a Voltmeter is in parallel (high resistance).</li><li><span style='color:var(--warning)'>4</span>. The unit of Magnetic Field Strength (B) is Tesla (T) or Gauss (1 T = 10^4 G).</li><li><span style='color:var(--warning)'>5</span>. Electric power is calculated as P = VI = I²R = V²/R.</li><li><span style='color:var(--warning)'>6</span>. A fuse wire must have a high resistance and a low melting point.</li><li><span style='color:var(--warning)'>7</span>. The force on a current-carrying conductor in a magnetic field is F = BIL sin(θ).</li><li><span style='color:var(--warning)'>8</span>. AC is preferred for long-distance transmission to reduce I²R power loss using step-up transformers.</li><li><span style='color:var(--warning)'>9</span>. The capacitance of a parallel plate capacitor is C = ε₀A/d.</li><li><span style='color:var(--warning)'>10</span>. A galvanometer can be converted into an ammeter by adding a low-resistance shunt in parallel.</li><li><span style='color:var(--warning)'>11</span>. Magnetic field lines always form closed loops, entering South and leaving North poles.</li><li><span style='color:var(--warning)'>12</span>. The energy stored in an inductor is given by U = 1/2 LI².</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-nuclear-basics"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    Nuclear Physics & Radioactivity
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p><b>Nuclear Physics</b> focuses on the constituents and interactions of the atomic nucleus. The nucleus consists of <b>nucleons</b> (protons and neutrons) held together by the <b>Strong Nuclear Force</b>, which overcomes the electrostatic repulsion between protons. Key concepts include <b>Binding Energy</b>, which is the energy required to disassemble a nucleus, and <b>Mass Defect</b>, the difference between the mass of the nucleus and the sum of its individual nucleons. [[Ernest Rutherford]] first discovered the nucleus through the gold foil experiment, establishing the planetary model of the atom.</p><p><b>Radioactivity</b> is the spontaneous disintegration of unstable nuclei, emitting radiation to reach a stable state. There are three primary types: <b>Alpha decay</b> (emission of a Helium nucleus), <b>Beta decay</b> (conversion of neutron to proton or vice versa), and <b>Gamma decay</b> (high-energy electromagnetic radiation). The rate of decay is governed by the <b>Half-Life</b> formula, where the activity is proportional to the number of undecayed nuclei. [[Marie Curie]] and [[Henri Becquerel]] were pioneers in identifying these radioactive elements and their properties.</p><p>The significance of these processes is seen in <b>Nuclear Fission</b> (splitting heavy nuclei) and <b>Nuclear Fusion</b> (combining light nuclei), which power nuclear reactors and stars respectively. For defence aspirants, understanding <b>Isotopes</b> and <b>Isobars</b> is crucial for questions on carbon dating and medical imaging. The immense energy released during these reactions follows Einstein's mass-energy equivalence principle, <b>E=mc²</b>.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Strong Nuclear Force</td><td style='border:1px solid var(--border);padding:8px;'>Short-range, strongest force; attractive for N-N, P-P, and P-N pairs.</td><td style='border:1px solid var(--border);padding:8px;'>Remember it is charge-independent.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Binding Energy</td><td style='border:1px solid var(--border);padding:8px;'>Energy released when nucleons combine to form a nucleus.</td><td style='border:1px solid var(--border);padding:8px;'>Higher B.E. per nucleon = Higher stability.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Alpha Particle</td><td style='border:1px solid var(--border);padding:8px;'>Helium nucleus (2p, 2n); charge +2e; mass 4u.</td><td style='border:1px solid var(--border);padding:8px;'>Atomic number decreases by 2, Mass by 4.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Beta Particle</td><td style='border:1px solid var(--border);padding:8px;'>High-speed electron or positron emitted from nucleus.</td><td style='border:1px solid var(--border);padding:8px;'>Atomic number changes by 1, Mass remains same.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Gamma Rays</td><td style='border:1px solid var(--border);padding:8px;'>High-frequency EM waves; no charge; no mass.</td><td style='border:1px solid var(--border);padding:8px;'>Highest penetrating power among radiations.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Nuclear Fission</td><td style='border:1px solid var(--border);padding:8px;'>Splitting of heavy nucleus (e.g., U-235) into lighter nuclei.</td><td style='border:1px solid var(--border);padding:8px;'>Used in Nuclear Power Plants and Atomic Bombs.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Nuclear Fusion</td><td style='border:1px solid var(--border);padding:8px;'>Combining light nuclei (e.g., Hydrogen) to form heavier ones.</td><td style='border:1px solid var(--border);padding:8px;'>Requires extreme temperature (Thermonuclear).</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>A-B-G (Penetration)</strong>: Alpha (Low), Beta (Medium), Gamma (High) - think of 'A' as a slow arrow, 'B' as a bullet, 'G' as a ghost passing through walls.</li><li><strong>Fission vs Fusion</strong>: 'Fission' sounds like 'Division' (splitting); 'Fusion' sounds like 'Union' (joining).</li><li><strong>Isotope/Isobar/Isotone</strong>: IsotoPE (same Protons), Isobar (same mass BAR), IsotoNE (same Neutrons).</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. The most stable nucleus is Iron-56 (Fe-56) due to maximum binding energy per nucleon.</li><li><span style='color:var(--warning)'>2</span>. Alpha particles are deflected by positive charges, proving the nucleus is positively charged.</li><li><span style='color:var(--warning)'>3</span>. Carbon-14 is used for dating organic materials (Radiocarbon dating).</li><li><span style='color:var(--warning)'>4</span>. Cobalt-60 is widely used in cancer radiotherapy.</li><li><span style='color:var(--warning)'>5</span>. In a nuclear reactor, Graphite or Heavy Water (D2O) acts as a moderator to slow down neutrons.</li><li><span style='color:var(--warning)'>6</span>. Control rods (Cadmium or Boron) are used to absorb excess neutrons in reactors.</li><li><span style='color:var(--warning)'>7</span>. Fusion occurs in the Sun via the Proton-Proton chain or CNO cycle.</li><li><span style='color:var(--warning)'>8</span>. The mass of a nucleus is always slightly less than the sum of its individual nucleons (Mass Defect).</li><li><span style='color:var(--warning)'>9</span>. Gamma radiation does not change the atomic number or mass number of the element.</li><li><span style='color:var(--warning)'>10</span>. Half-life (T1/2) is the time taken for half of the radioactive nuclei to decay.</li>
  </ul>
</div>
`;

window.EXPANDED_NOTES_DATA["physics-units-everyday"] = `

<div class="revision-card" style="background: rgba(20,20,30,0.4); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.25);">
  <h3 style="color: var(--accent); margin-bottom: 16px; border-bottom: 1px solid var(--border); padding-bottom: 8px; display: flex; align-items: center; gap: 8px; font-weight: 600;">
    SI Units & Everyday Physics
  </h3>

  <!-- SECTION 1: DEEP CONCEPTUAL EXPLANATION -->
  <section>
    <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Deep Conceptual Explanation</h4>
    <p>The <b>International System of Units (SI)</b> is the modern form of the metric system and the most widely used system of measurement globally. It is based on <b>seven base units</b>—the meter, kilogram, second, ampere, kelvin, mole, and candela—from which all other <b>derived units</b> are formed. For defence aspirants, understanding these is crucial as they form the foundation of <b>Classical Mechanics</b> and <b>Electromagnetism</b>. The system ensures uniformity in scientific communication, which is vital for precision in ballistics, navigation, and aerospace engineering [[BIPM]].</p><p>The mechanism of SI units relies on <b>universal physical constants</b> rather than physical artifacts. For example, the <b>kilogram</b> is no longer defined by a platinum-iridium cylinder but by the <b>Planck constant</b>. Derived units, such as the <b>Newton (N)</b> for force and <b>Pascal (Pa)</b> for pressure, are combinations of base units. In everyday physics, concepts like <b>viscosity</b>, <b>surface tension</b>, and <b>atmospheric pressure</b> are measured using these standards to ensure accuracy in military hardware and environmental monitoring.</p><p>The significance of SI units lies in their <b>decimal nature</b> and global standardization, reducing errors in international collaborations. For NDA/CDS exams, mastering <b>dimensional analysis</b> allows candidates to verify the correctness of physical equations and convert units rapidly, which is a high-scoring area in the General Ability Test (GAT) physics section.</p>
  </section>

  <!-- SECTION 2: QUICK REVISION TABLE -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Quick Revision Table</h4>
  <table style="border-collapse:collapse;width:100%;">
    <tr>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Key Term / Event</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Details / Date</th>
      <th style="border:1px solid var(--border);padding:10px;background:rgba(255,255,255,0.05);">Exam Significance</th>
    </tr>
    <tr><td style='border:1px solid var(--border);padding:8px;'>Luminous Intensity</td><td style='border:1px solid var(--border);padding:8px;'>Measured in <b>Candela (cd)</b>; defines the power emitted by a light source.</td><td style='border:1px solid var(--border);padding:8px;'>Often ignored; remember it as a base unit.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Amount of Substance</td><td style='border:1px solid var(--border);padding:8px;'>Measured in <b>Mole (mol)</b>; 6.022 x 10^23 particles.</td><td style='border:1px solid var(--border);padding:8px;'>Crucial for chemistry-physics overlap questions.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Force</td><td style='border:1px solid var(--border);padding:8px;'><b>Newton (N)</b> = kg·m/s²; derived from F=ma.</td><td style='border:1px solid var(--border);padding:8px;'>Check dimensions [MLT⁻²].</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Pressure</td><td style='border:1px solid var(--border);padding:8px;'><b>Pascal (Pa)</b> = N/m²; force per unit area.</td><td style='border:1px solid var(--border);padding:8px;'>1 atm = 1.013 x 10^5 Pa.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Electric Current</td><td style='border:1px solid var(--border);padding:8px;'><b>Ampere (A)</b>; flow of electric charge per unit time.</td><td style='border:1px solid var(--border);padding:8px;'>Base unit, not derived from Volt/Ohm.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Thermodynamic Temp</td><td style='border:1px solid var(--border);padding:8px;'><b>Kelvin (K)</b>; absolute scale where 0K is absolute zero.</td><td style='border:1px solid var(--border);padding:8px;'>T(K) = t(°C) + 273.15.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Power</td><td style='border:1px solid var(--border);padding:8px;'><b>Watt (W)</b> = Joule/second; rate of doing work.</td><td style='border:1px solid var(--border);padding:8px;'>Distinguish between Power and Energy.</td></tr><tr><td style='border:1px solid var(--border);padding:8px;'>Frequency</td><td style='border:1px solid var(--border);padding:8px;'><b>Hertz (Hz)</b> = 1/second; cycles per second.</td><td style='border:1px solid var(--border);padding:8px;'>Essential for wave and sound questions.</td></tr>
  </table>

  <!-- SECTION 3: MNEMONICS & MEMORY AIDS -->
  <h4 style="border-left: 3px solid var(--success); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">Mnemonics &amp; Memory Aids</h4>
  <ul style="margin-left:20px;">
    <li><strong>K-M-S-A-K-M-C</strong>: <b>K</b>ing <b>M</b>akes <b>S</b>ure <b>A</b>ll <b>K</b>nights <b>M</b>ove <b>C</b>arefully (Kelvin, Meter, Second, Ampere, Kilogram, Mole, Candela).</li><li><strong>N-P-J-W</strong>: <b>N</b>ewtons <b>P</b>ush <b>J</b>ust <b>W</b>ork (Force, Pressure, Energy, Power sequence).</li><li><strong>V-I-R</strong>: <b>V</b>ery <b>I</b>mportant <b>R</b>elation (Voltage = Current x Resistance).</li>
  </ul>

  <!-- SECTION 4: HIGH-YIELD RULES & FACTS -->
  <h4 style="border-left: 3px solid var(--info); padding-left: 8px; margin-top: 24px; margin-bottom: 10px; color: var(--text-primary); font-weight: 600;">High-Yield Facts</h4>
  <ul style="margin-left:20px;">
    <li><span style='color:var(--warning)'>1</span>. There are 7 base SI units and all others are derived.</li><li><span style='color:var(--warning)'>2</span>. The <b>Planck constant</b> is now used to define the kilogram.</li><li><span style='color:var(--warning)'>3</span>. 1 Joule is equivalent to 1 Newton-meter (N·m).</li><li><span style='color:var(--warning)'>4</span>. The <b>Tesla (T)</b> is the SI unit of magnetic flux density.</li><li><span style='color:var(--warning)'>5</span>. <b>Weber (Wb)</b> is the unit for magnetic flux.</li><li><span style='color:var(--warning)'>6</span>. 1 Horsepower (hp) is approximately 746 Watts.</li><li><span style='color:var(--warning)'>7</span>. The unit of electric conductance is <b>Siemens (S)</b>.</li><li><span style='color:var(--warning)'>8</span>. <b>Lumen</b> is the unit of luminous flux, while Candela is luminous intensity.</li><li><span style='color:var(--warning)'>9</span>. Dimensional formula for Work and Energy is [ML²T⁻²].</li><li><span style='color:var(--warning)'>10</span>. The <b>Dioptre (D)</b> is the SI unit of power of a lens.</li><li><span style='color:var(--warning)'>11</span>. 1 Bar = 10^5 Pascals.</li><li><span style='color:var(--warning)'>12</span>. The <b>Henry (H)</b> is the SI unit of inductance.</li>
  </ul>
</div>
`;

