const fs = require('fs');
const path = require('path');

const metadataPath = path.join(__dirname, 'Pathfinder_Elite', 'metadata.json');
const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));

const aiNotes = [];

metadata.forEach(m => {
    const mdPath = path.join(__dirname, m.file_path);
    if (fs.existsSync(mdPath)) {
        const content = fs.readFileSync(mdPath, 'utf8');
        aiNotes.push({
            id: m.target_id,
            title: m.topic_name,
            subject: m.subject,
            // We'll wrap notes in template literals when injecting. In JSON we just store the string.
            notes: content
        });
    }
});

let outputJs = `// This file is auto-generated by package_ai_notes.js\n`;
outputJs += `const AI_GENERATED_NOTES = ${JSON.stringify(aiNotes, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, 'ai_generated_notes.js'), outputJs);
console.log(`Packaged ${aiNotes.length} topics into ai_generated_notes.js`);
