graph TD
    AM[Air Masses]
    AM --> T[Tropical (T)]
    AM --> P[Polar (P)]
    AM --> A[Arctic/Antarctic (A)]
    T --> Tc[Continental (c)]
    T --> Tm[Maritime (m)]
    P --> Pc[Continental (c)]
    P --> Pm[Maritime (m)]
    A --> Ac[Continental (c)]
    A --> Am[Maritime (m)]