graph TD
A[Igneous Rocks] --> B[Classification by Formation]
A --> C[Classification by Silica Content]
B --> B1[Intrusive (Plutonic)]
B --> B2[Extrusive (Volcanic)]
B1 --> B1a[Slow cooling, Coarse-grained]
B1a --> B1b[e.g., Granite, Diorite, Gabbro]
B2 --> B2a[Rapid cooling, Fine-grained/Glassy]
B2a --> B2b[e.g., Basalt, Andesite, Rhyolite, Obsidian, Pumice]
C --> C1[Felsic (Acidic) >65% SiO2]
C --> C2[Mafic (Basic) 45-55% SiO2]
C --> C3[Intermediate 55-65% SiO2]
C --> C4[Ultrabasic <45% SiO2]
C1 --> C1a[Light colour, e.g., Granite, Rhyolite]
C2 --> C2a[Dark colour, e.g., Basalt, Gabbro]
C3 --> C3a[e.g., Diorite, Andesite]