mindmap
  root((Budget & Fiscal))
    Revenue Budget
      ::icon(fas fa-check)
      Tax Revenue
      ::icon(fas fa-check)
      Non-Tax Revenue
      ::icon(fas fa-check)
      Revenue Expenditure
    Capital Budget
      ::icon(fas fa-check)
      Borrowings
      ::icon(fas fa-check)
      Capital Expenditure
    GST
      ::icon(fas fa-check)
      CGST+SGST
      ::icon(fas fa-check)
      IGST
      ::icon(fas fa-check)
      Council  Art 279A
    Deficits
      ::icon(fas fa-check)
      Fiscal
      ::icon(fas fa-check)
      Revenue
      ::icon(fas fa-check)
      Primary