mindmap
  root((Geomorphology & Rocks))
    Seismic Waves
      ::icon(fas fa-check)
      P-waves  fastest, all media
      ::icon(fas fa-check)
      S-waves  solid only
      ::icon(fas fa-check)
      L-waves  surface, most damage
      ::icon(fas fa-check)
      Shadow zones
    Rock Types
      ::icon(fas fa-check)
      Igneous: Granite, Basalt
      ::icon(fas fa-check)
      Sedimentary: Sandstone, Coal
      ::icon(fas fa-check)
      Metamorphic: Marble, Quartzite
    Plate Tectonics
      ::icon(fas fa-check)
      Convergent: mountains
      ::icon(fas fa-check)
      Divergent: ridges
      ::icon(fas fa-check)
      Transform: earthquakes
    Landforms
      ::icon(fas fa-check)
      Fluvial: V-valley, delta
      ::icon(fas fa-check)
      Glacial: U-valley, fjord
      ::icon(fas fa-check)
      Karst: caves, stalagmites
      ::icon(fas fa-check)
      Aeolian: dunes
    Tectonic Plates
      ::icon(fas fa-check)
      Major plates
      ::icon(fas fa-check)
      Minor plates
      ::icon(fas fa-check)
      Boundaries
    Activity
      ::icon(fas fa-check)
      Volcanism
      ::icon(fas fa-check)
      Earthquakes  Shadow zones