mindmap
  root((Indian Geography))
    Himalayan Rivers
      ::icon(fas fa-check)
      Ganga
      ::icon(fas fa-check)
      Indus
      ::icon(fas fa-check)
      Brahmaputra
    Peninsular Rivers
      ::icon(fas fa-check)
      Godavari
      ::icon(fas fa-check)
      Krishna
      ::icon(fas fa-check)
      Narmada
    Soils
      ::icon(fas fa-check)
      Alluvial
      ::icon(fas fa-check)
      Black  Regur
      ::icon(fas fa-check)
      Laterite