mindmap
  root((Govt Schemes))
    Financial Inclusion
      ::icon(fas fa-check)
      PM Jan Dhan Yojana  PMJDY
      ::icon(fas fa-check)
      PM MUDRA Yojana
      ::icon(fas fa-check)
      Atal Pension Yojana  APY
    Social Security
      ::icon(fas fa-check)
      PM Jeevan Jyoti Bima  PMJJBY
      ::icon(fas fa-check)
      PM Suraksha Bima  PMSBY
      ::icon(fas fa-check)
      MGNREGA  100 days job
    Agriculture & Rural
      ::icon(fas fa-check)
      PM-KISAN  6000/yr
      ::icon(fas fa-check)
      PM Fasal Bima  PMFBY
      ::icon(fas fa-check)
      PMAY  Housing