mindmap
  root((Metals & Alloys))
    Ores
      ::icon(fas fa-check)
      Bauxite: Al
      ::icon(fas fa-check)
      Hematite: Fe
      ::icon(fas fa-check)
      Cinnabar: Hg
      ::icon(fas fa-check)
      Galena: Pb
    Alloys
      ::icon(fas fa-check)
      Brass: Cu+Zn
      ::icon(fas fa-check)
      Bronze: Cu+Sn
      ::icon(fas fa-check)
      Solder: Pb+Sn
      ::icon(fas fa-check)
      Duralumin: Al+Cu+Mn+Mg
    Metallurgy
      ::icon(fas fa-check)
      Froth flotation
      ::icon(fas fa-check)
      Calcination  no air
      ::icon(fas fa-check)
      Roasting  air
      ::icon(fas fa-check)
      Electrolysis: highly reactive