mindmap
  root((Citizenship))
    Constitutional
      ::icon(fas fa-check)
      Part II
      ::icon(fas fa-check)
      Articles 5-11
      ::icon(fas fa-check)
      Parliament authority  Art 11
    Acquisition  5
      ::icon(fas fa-check)
      Birth
      ::icon(fas fa-check)
      Descent
      ::icon(fas fa-check)
      Registration
      ::icon(fas fa-check)
      Naturalization
      ::icon(fas fa-check)
      Incorporation
    Loss  3
      ::icon(fas fa-check)
      Renunciation
      ::icon(fas fa-check)
      Termination
      ::icon(fas fa-check)
      Deprivation