mindmap
  root((Bilateral Drills))
    US & UK
      ::icon(fas fa-check)
      US: Yudh Abhyas, Vajra
      ::icon(fas fa-check)
      UK: Ajeya Warrior, Konkan
    France & Russia
      ::icon(fas fa-check)
      FR: Shakti  Army
      ::icon(fas fa-check)
      FR: Varuna  Navy , Garuda  Air
      ::icon(fas fa-check)
      RU: Indra Tri-services
    Subcontinent
      ::icon(fas fa-check)
      Nepal: Surya Kiran
      ::icon(fas fa-check)
      Bangladesh: Sampriti
      ::icon(fas fa-check)
      Sri Lanka: Mitra Shakti
    East Asia
      ::icon(fas fa-check)
      Japan: Dharma Guardian
      ::icon(fas fa-check)
      Mongolia: Nomadic Elephant
      ::icon(fas fa-check)
      Singapore: Simbex