mindmap
  root((Ordering))
    Ordering Words
      ::icon(fas fa-check)
      Identify Subject-Verb-Object
      ::icon(fas fa-check)
      Look for capital letters & full stops
      ::icon(fas fa-check)
      Prepositional & relative phrases
    Ordering Sentences
      ::icon(fas fa-check)
      Find opening sentence  introduces topic
      ::icon(fas fa-check)
      Mandatory pairs  pronoun reference, article order
      ::icon(fas fa-check)
      Transitions  However, Therefore