mindmap
  root((Animal Kingdom))
    Invertebrates I
      ::icon(fas fa-check)
      Porifera: Sponges
      ::icon(fas fa-check)
      Coelenterata: Cnidoblasts
      ::icon(fas fa-check)
      Platyhelminthes: Flatworms
      ::icon(fas fa-check)
      Aschelminthes: Roundworms
    Invertebrates II
      ::icon(fas fa-check)
      Annelida: Segmented
      ::icon(fas fa-check)
      Arthropoda: Jointed, largest
      ::icon(fas fa-check)
      Mollusca: Soft
      ::icon(fas fa-check)
      Echinodermata: Spiny, water-vascular
    Vertebrates  Chordata
      ::icon(fas fa-check)
      Pisces: 2-chambered, gills
      ::icon(fas fa-check)
      Amphibia: 3-chambered
      ::icon(fas fa-check)
      Reptilia: 3-chambered  Crocodile 4
      ::icon(fas fa-check)
      Aves: 4-chambered, warm
      ::icon(fas fa-check)
      Mammalia: Milk glands