graph LR
Intrusive_Forms --> Batholiths
Intrusive_Forms --> Laccoliths
Intrusive_Forms --> Lopoliths
Intrusive_Forms --> Phacoliths
Intrusive_Forms --> Sills
Intrusive_Forms --> Dykes
Extrusive_Forms --> Cinder_Cones
Extrusive_Forms --> Composite_Cones
Extrusive_Forms --> Shield_Cones
Extrusive_Forms --> Craters
Extrusive_Forms --> Calderas
Extrusive_Forms --> Lava_Plateaus
Extrusive_Forms --> Hot_Springs
Extrusive_Forms --> Geysers