mindmap
    root((Universe Components))
        Galaxies
        Stars
        Planets
        Nebulae
        Asteroids
        Comets
        Interstellar Dust
        Dark Matter
        Dark Energy