mindmap
  root((RPA & Elections))
    RPA 1950
      ::icon(fas fa-check)
      Electoral rolls
      ::icon(fas fa-check)
      Delimitation
    RPA 1951
      ::icon(fas fa-check)
      Corrupt practices
      ::icon(fas fa-check)
      Disqualification
    Anti-Defection
      ::icon(fas fa-check)
      52nd Amendment
      ::icon(fas fa-check)
      10th Schedule
    ECI
      ::icon(fas fa-check)
      Art 324
      ::icon(fas fa-check)
      MCC
      ::icon(fas fa-check)
      NOTA
      ::icon(fas fa-check)
      VVPAT