graph TD
    SR[Sedimentary Rocks]
    SR --> C[Clastic (Detrital)]
    SR --> O[Organic]
    SR --> CH[Chemical]
    C --> G[Grain Size]
    G --> S[Sandstone]
    G --> Sh[Shale]
    G --> Co[Conglomerate]
    O --> Coa[Coal]
    O --> Li[Limestone]
    CH --> RS[Rock Salt]
    CH --> Gy[Gypsum]
    CH --> Ch[Chert]