graph LR
EarlyTheories --> ContinentalDrift[Continental Drift (1912)]
EarlyTheories --> ConvectionCurrent[Convectional Current Theory (1930s)]
EarlyTheories --> SeafloorSpreading[Seafloor Spreading (1960s)]
EarlyTheories --> ModernTheory[Modern Theory (Plate Tectonics)]