mindmap
  root((One Word))
    Governments
      ::icon(fas fa-check)
      Anarchy
      ::icon(fas fa-check)
      Oligarchy
      ::icon(fas fa-check)
      Democracy
      ::icon(fas fa-check)
      Monarchy
    Personalities
      ::icon(fas fa-check)
      Altruist
      ::icon(fas fa-check)
      Egotist
      ::icon(fas fa-check)
      Ascetic
      ::icon(fas fa-check)
      Incorrigible
      ::icon(fas fa-check)
      Optimist