mindmap
  root((Phrasal Verbs))
    Break & Call
      ::icon(fas fa-check)
      Break down  collapse
      ::icon(fas fa-check)
      Break out  start war
      ::icon(fas fa-check)
      Call off  cancel
    Look & Put
      ::icon(fas fa-check)
      Look into  investigate
      ::icon(fas fa-check)
      Put off  postpone
      ::icon(fas fa-check)
      Put up with  tolerate
    Others
      ::icon(fas fa-check)
      Come across  find by chance
      ::icon(fas fa-check)
      Turn down  reject
      ::icon(fas fa-check)
      Run out of  exhaust