mindmap
  root((Parts of Speech))
    Nouns & Pronouns
      ::icon(fas fa-check)
      Countable vs Uncountable
      ::icon(fas fa-check)
      Relative Pronouns
      ::icon(fas fa-check)
      Reflexive Pronouns
    Verbs & Adverbs
      ::icon(fas fa-check)
      Transitive/Intransitive
      ::icon(fas fa-check)
      Modal Verbs
      ::icon(fas fa-check)
      Adverb Position/Enough
    Modifiers & Connectors
      ::icon(fas fa-check)
      Adjective Order  OSASCOMP
      ::icon(fas fa-check)
      Preposition errors
      ::icon(fas fa-check)
      Coordinating/Correlative Conjunctions