mindmap
  root((Time, Speed & Distance))
    Basic
      ::icon(fas fa-check)
      S = D/T
      ::icon(fas fa-check)
      km/hr × 5/18 = m/s
      ::icon(fas fa-check)
      Avg speed = 2s₁s₂/ s₁+s₂
    Relative Speed
      ::icon(fas fa-check)
      Same dir: |s₁-s₂|
      ::icon(fas fa-check)
      Opp dir: s₁+s₂
      ::icon(fas fa-check)
      Train problems
    Boats & Streams
      ::icon(fas fa-check)
      Downstream = B+S
      ::icon(fas fa-check)
      Upstream = B-S
      ::icon(fas fa-check)
      Still water = ½ D+U
    Work & Time
      ::icon(fas fa-check)
      Together = ab/ a+b
      ::icon(fas fa-check)
      Efficiency ∝ 1/time
      ::icon(fas fa-check)
      Pipes and cisterns
    Time & Work
      ::icon(fas fa-check)
      Efficiency
      ::icon(fas fa-check)
      Pipes & Cisterns