import os
import glob

def compile_notes():
    output_dir = "output/modules"
    # Write to root directory so it can be committed. build_www.js will copy it to www/
    out_js_path = "notes_generated.js"
    
    import json
    
    # Load taxonomy to get nice titles
    taxonomy_titles = {}
    try:
        with open("scripts/taxonomy_map.json", "r") as f:
            tax = json.load(f)
            for subj, s_data in tax.get("subjects", {}).items():
                for t in s_data.get("topics", []):
                    taxonomy_titles[t["id"]] = t.get("title", t["id"])
    except Exception as e:
        print("Could not load taxonomy:", e)
        
    md_files = glob.glob(os.path.join(output_dir, "**/*.md"), recursive=True)
    
    # Track which topics we found so we can add them to the UI, grouped by subject
    found_topics = {}
    
    with open(out_js_path, "w", encoding="utf-8") as out_js:
        out_js.write("window.EXPANDED_NOTES_DATA = window.EXPANDED_NOTES_DATA || {};\n\n")
        
        for md_file in md_files:
            basename = os.path.basename(md_file)
            topic_id, _ = os.path.splitext(basename)
            
            # The directory containing the file is the Subject name
            subject_name = os.path.basename(os.path.dirname(md_file))
            if subject_name not in found_topics:
                found_topics[subject_name] = []
            
            # Record it for the UI menu
            title = taxonomy_titles.get(topic_id, topic_id.replace("_", " "))
            found_topics[subject_name].append({"id": topic_id, "title": title})
            
            with open(md_file, "r", encoding="utf-8") as f:
                content = f.read()
                
            import markdown
            html_content = markdown.markdown(content, extensions=['fenced_code', 'tables'])
            content_escaped = html_content.replace("`", "\\`").replace("${", "\\${")
            
            out_js.write(f'window.EXPANDED_NOTES_DATA["{topic_id}"] = `\n')
            out_js.write(content_escaped)
            out_js.write('\n`;\n\n')
            
        # Now inject the UI menu logic
        out_js.write("// Dynamically inject AI generated notes into the app's side menu\n")
        out_js.write("if (typeof NOTES_DATABASE !== 'undefined') {\n")
        
        for subj, topics in found_topics.items():
            db_key = subj.lower()
            if db_key == "general_knowledge":
                db_key = "general_knowledge" # Just in case it needs mapping
            
            out_js.write(f"  if (NOTES_DATABASE['{db_key}']) {{\n")
            out_js.write(f"    let aiChapter = NOTES_DATABASE['{db_key}'].chapters.find(c => c.id === 'ai-generated-{db_key}');\n")
            out_js.write(f"    if (!aiChapter) {{\n")
            out_js.write(f"      aiChapter = {{ id: 'ai-generated-{db_key}', title: 'AI Synthesized Chapters', topics: [] }};\n")
            out_js.write(f"      NOTES_DATABASE['{db_key}'].chapters.push(aiChapter);\n")
            out_js.write(f"    }}\n")
            out_js.write(f"    aiChapter.topics = [];\n")
            
            for t in topics:
                t_id = t["id"].replace('"', '\\"')
                t_title = t["title"].replace('"', '\\"')
                out_js.write(f'    aiChapter.topics.push({{ id: "{t_id}", title: "{t_title}", notes: "Generated by AI Synthesis Engine" }});\n')
                
            out_js.write(f"  }}\n")
            
        out_js.write("}\n")
        
    print(f"Compiled {len(md_files)} notes into {out_js_path}")

if __name__ == "__main__":
    compile_notes()
