const fs = require('fs');
const path = require('path');

const DIAGRAMS_DIR = path.join(__dirname, '..', 'assets', 'diagrams');
const TOPICS_FILE = path.join(__dirname, '..', 'all_topics_mapping.json');
const OUTPUT_FILE = path.join(__dirname, '..', 'js', 'diagram_map.js');

const allTopics = JSON.parse(fs.readFileSync(TOPICS_FILE, 'utf8'));

function getAllImages(dir, fileList = []) {
  if (!fs.existsSync(dir)) return fileList;
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      getAllImages(fullPath, fileList);
    } else if (fullPath.match(/\.(png|jpg|jpeg|svg|webp)$/i)) {
      fileList.push(fullPath);
    }
  }
  return fileList;
}

const images = getAllImages(DIAGRAMS_DIR);
const diagramMap = {};

let unmappedCount = 0;

for (const imgPath of images) {
  // Convert absolute path to a relative URL-friendly path
  let relativeUrl = path.relative(path.join(__dirname, '..'), imgPath).replace(/\\/g, '/');
  // It should be something like 'assets/diagrams/Geography/...'
  
  const basename = path.basename(imgPath, path.extname(imgPath));
  
  const pathParts = relativeUrl.split('/');
  // Usually pathParts[2] is the subject folder like "Geography"
  const folderSubject = pathParts.length > 2 ? pathParts[2].toLowerCase() : "";
  
  // Clean up the basename to use as search string
  const searchStr = basename.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  
  // Filter topics by subject folder match first
  let candidateTopics = allTopics.filter(t => {
      const topicSubj = (t.subject || "").toLowerCase();
      // Only keep topics where subject matches the folder name
      // e.g., "Geography" folder -> "geography" subject
      if (folderSubject && topicSubj && (folderSubject.includes(topicSubj) || topicSubj.includes(folderSubject))) {
          return true;
      }
      return false;
  });
  
  // Fallback to all topics if subject didn't match cleanly (e.g. legacy folder)
  if (candidateTopics.length === 0) {
      candidateTopics = allTopics;
  }
  
  let bestTopic = null;
  let bestScore = -1;
  
  for (const topic of candidateTopics) {
      let score = 0;
      const topicTitle = topic.title.toLowerCase();
      const topicId = topic.id.toLowerCase();
      
      // Exact match on ID or exact match on Title
      if (topicId === searchStr.replace(/ /g, '-')) score += 100;
      if (topicTitle === searchStr) score += 100;
      if (basename.toLowerCase() === topicTitle) score += 100;
      
      // Partial match
      const searchWords = searchStr.split(' ').filter(w => w.length > 3); // Skip small words like "and", "the"
      let wordMatches = 0;
      for (const word of searchWords) {
          if (topicTitle.includes(word) || topicId.includes(word)) {
              wordMatches++;
          }
      }
      if (wordMatches > 0) {
          score += (wordMatches / searchWords.length) * 50; // Max 50 points for partial
      }
      
      // Filename contains topic ID (e.g. topicId="universe-solar-system", filename="..._universe_solar_system_...")
      const topicIdNormalized = topicId.replace(/-/g, '_');
      if (searchStr.includes(topicIdNormalized.replace(/_/g, ' '))) {
          score += 200;
      }
      const topicTitleNormalized = topicTitle.toLowerCase().replace(/[^a-z0-9]+/g, ' ');
      if (searchStr.includes(topicTitleNormalized)) {
          score += 150;
      }
      
      // Sub-chapter folder match
      // e.g. pathParts[3] = "Earth basics", topic.chapter = "Physical & World Geography"
      const subFolder = pathParts.length > 3 ? pathParts[3].toLowerCase() : "";
      if (subFolder && (topic.chapter.toLowerCase().includes(subFolder) || subFolder.includes(topic.chapter.toLowerCase().split(' ')[0]))) {
          score += 10;
      }
      
      if (score > bestScore && score > 0) {
          bestScore = score;
          bestTopic = topic;
      }
  }
  
  if (bestTopic) {
      if (!diagramMap[bestTopic.id]) {
          diagramMap[bestTopic.id] = [];
      }
      diagramMap[bestTopic.id].push({
          src: relativeUrl,
          title: basename
      });
  } else {
      unmappedCount++;
      console.log(`Unmapped: ${relativeUrl}`);
  }
}

// Generate the output JS file
const fileContent = `// Automatically generated by scripts/generate_diagram_map.js
window.DIAGRAM_MAP = ${JSON.stringify(diagramMap, null, 2)};
`;

fs.writeFileSync(OUTPUT_FILE, fileContent, 'utf8');

console.log(`Successfully mapped ${images.length - unmappedCount} of ${images.length} diagrams.`);
if (unmappedCount > 0) {
    console.log(`Failed to map ${unmappedCount} diagrams.`);
}
