mindmap
  root((Climatology & Clouds))
    Cloud Types
      ::icon(fas fa-check)
      High: Cirrus, Cirrostratus
      ::icon(fas fa-check)
      Middle: Alto-cumulus/stratus
      ::icon(fas fa-check)
      Low: Stratus, Nimbostratus
      ::icon(fas fa-check)
      Vertical: Cumulonimbus
    Rainfall Types
      ::icon(fas fa-check)
      Conventional  Equatorial
      ::icon(fas fa-check)
      Orographic  Mountain
      ::icon(fas fa-check)
      Cyclonic/Frontal  Temperate
    Koppen Zones
      ::icon(fas fa-check)
      A: Tropical
      ::icon(fas fa-check)
      B: Arid  Desert
      ::icon(fas fa-check)
      C: Temperate
      ::icon(fas fa-check)
      D: Continental, E: Polar
    India Seasons
      ::icon(fas fa-check)
      SW Monsoon: Jun-Sep
      ::icon(fas fa-check)
      NE Monsoon: Oct-Dec
      ::icon(fas fa-check)
      Western Disturbances: Dec-Feb
    Clouds
      ::icon(fas fa-check)
      Cirrus
      ::icon(fas fa-check)
      Altocumulus
      ::icon(fas fa-check)
      Stratus
      ::icon(fas fa-check)
      Cumulonimbus