mindmap
  root((World Mountains))
    Major Ranges
      ::icon(fas fa-check)
      Himalayas  Asia
      ::icon(fas fa-check)
      Andes  S. America
      ::icon(fas fa-check)
      Rockies  N. America
      ::icon(fas fa-check)
      Alps  Europe
    Highest Peaks
      ::icon(fas fa-check)
      Everest  8849m
      ::icon(fas fa-check)
      Aconcagua  6961m
      ::icon(fas fa-check)
      Kilimanjaro  5895m
      ::icon(fas fa-check)
      Denali  6190m
    India - Himalayas
      ::icon(fas fa-check)
      Himadri  Great
      ::icon(fas fa-check)
      Himachal  Middle
      ::icon(fas fa-check)
      Shiwalik  Outer
      ::icon(fas fa-check)
      Karakoram & Ladakh
    Peninsular India
      ::icon(fas fa-check)
      Aravalli  Oldest
      ::icon(fas fa-check)
      Western Ghats
      ::icon(fas fa-check)
      Eastern Ghats
      ::icon(fas fa-check)
      Vindhya & Satpura
    Major Ranges
      ::icon(fas fa-check)
      Himalayas  Asia
      ::icon(fas fa-check)
      Andes  South America
      ::icon(fas fa-check)
      Alps  Europe
      ::icon(fas fa-check)
      Rockies  North America
    India - Himalayas
      ::icon(fas fa-check)
      Himadri  Great Himalayas
      ::icon(fas fa-check)
      Himachal  Middle
      ::icon(fas fa-check)
      Shiwalik  Outer
      ::icon(fas fa-check)
      Karakoram & Ladakh
    India - Peninsular
      ::icon(fas fa-check)
      Aravalli  oldest
      ::icon(fas fa-check)
      Vindhya & Satpura
      ::icon(fas fa-check)
      Western Ghats  Sahyadri
      ::icon(fas fa-check)
      Eastern Ghats  discontinuous
    Forests
      ::icon(fas fa-check)
      Evergreen
      ::icon(fas fa-check)
      Deciduous
      ::icon(fas fa-check)
      Coniferous
    Rivers
      ::icon(fas fa-check)
      Nile
      ::icon(fas fa-check)
      Amazon
      ::icon(fas fa-check)
      Yangtze
      ::icon(fas fa-check)
      Mississippi