mindmap
  root((DPSP & Duties))
    DPSP  Part IV
      ::icon(fas fa-check)
      Socialistic: Equal pay
      ::icon(fas fa-check)
      Gandhian: Panchayats  40
      ::icon(fas fa-check)
      Liberal: UCC  44 , Peace  51
    Duties  Part IV-A
      ::icon(fas fa-check)
      Swaran Singh Comm
      ::icon(fas fa-check)
      42nd Amend  10 duties
      ::icon(fas fa-check)
      86th Amend  11th duty