graph TD
    C[Cloud Classification]
    C --> H[High Clouds (>6 000 m)]
    H --> Ci[Cirrus (Ci)]
    H --> Cc[Cirrocumulus (Cc)]
    H --> Cs[Cirrostratus (Cs)]
    C --> M[Middle Clouds (2 000‑6 000 m)]
    M --> Ac[Altocumulus (Ac)]
    M --> As[Altostratus (As)]
    C --> L[Low Clouds (<2 000 m)]
    L --> St[Stratus (St)]
    L --> Cu[Cumulus (Cu)]
    L --> Sc[Stratocumulus (Sc)]
    L --> Ns[Nimbostratus (Ns)]
    C --> V[Vertically Developed]
    V --> Cb[Cumulonimbus (Cb)]
    V --> Ccng[Cumulus Congestus]