mindmap
    root((Influential Geographers))
        Alexander von Humboldt
            Pioneer of biogeography
            Physical geography
        Carl Ritter
            Founder of comparative geography
            Geographic determinism
        Paul Vidal de la Blache
            Father of regional geography
            Human-environment interaction studies