graph TB
subgraph Major Plates
Pacific
North_American
South_American
Eurasian
African
Indo_Australian
Antarctic
end
subgraph Minor Plates
Nazca
Cocos
Caribbean
Philippine_Sea
Arabian
Juan_de_Fuca
Scotia
end