// Script to strip raw MCQ content from English notes in ai_generated_notes.js
// and produce a clean version

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'ai_generated_notes.js');
let content = fs.readFileSync(filePath, 'utf8');

// The file starts with: const AI_GENERATED_NOTES = [...]
// We need to eval it carefully - instead parse by modifying the notes fields

// Parse the JS by requiring it (it exports a const, so wrap it)
const tempFile = path.join(__dirname, 'temp_ai_notes.cjs');
const wrappedContent = content.replace('const AI_GENERATED_NOTES = ', 'module.exports = ');
fs.writeFileSync(tempFile, wrappedContent);

const notes = require(tempFile);

let synonymsFixed = false, antonymsFixed = false;

notes.forEach(topic => {
  if (topic.id === 'synonyms') {
    // Keep only up to CHECK YOUR VOCABULARY / MCQ list
    const cutoff = topic.notes.indexOf('CHECK YOUR VOCABULARY');
    if (cutoff > -1) {
      // Keep everything before MCQ list; close the div properly
      let cleanNotes = topic.notes.substring(0, cutoff);
      // Add a proper closing structure
      cleanNotes += `
        <div style="margin-top: 20px; padding: 15px; background: rgba(56,189,248,0.08); border-radius: 6px; border: 1px solid rgba(56,189,248,0.25);">
          <strong style="color: #38bdf8;">Exam Strategy:</strong> For synonyms, always check the <em>context</em> of the sentence. The correct answer must be semantically equivalent in the given context, not just in isolation. Prioritize words from editorial sections of quality newspapers — UPSC repeatedly tests such vocabulary in NDA, CDS, and AFCAT.
        </div>
      </div>\r\n"`;
      topic.notes = cleanNotes;
      synonymsFixed = true;
      console.log('✅ Fixed SYNONYMS notes - removed MCQ list');
    }
  }
  
  if (topic.id === 'antonyms') {
    const cutoff = topic.notes.indexOf('CHECK YOUR VOCABULARY');
    if (cutoff > -1) {
      let cleanNotes = topic.notes.substring(0, cutoff);
      cleanNotes += `
        <div style="margin-top: 20px; padding: 15px; background: rgba(56,189,248,0.08); border-radius: 6px; border: 1px solid rgba(56,189,248,0.25);">
          <strong style="color: #38bdf8;">Exam Strategy:</strong> For antonyms, watch out for <em>near-antonyms</em> as traps. E.g., "COLD" — "Warm" is a near antonym but "Hot" is the true opposite. UPSC uses such traps extensively. Focus on the degree of opposition, not just the general concept.
        </div>
      </div>\r\n"`;
      topic.notes = cleanNotes;
      antonymsFixed = true;
      console.log('✅ Fixed ANTONYMS notes - removed MCQ list');
    }
  }
});

if (!synonymsFixed) console.warn('⚠️ SYNONYMS entry not found or already clean');
if (!antonymsFixed) console.warn('⚠️ ANTONYMS entry not found or already clean');

// Write back
const output = `// This file is auto-generated by package_ai_notes.js\nconst AI_GENERATED_NOTES = ${JSON.stringify(notes, null, 2)};\n`;
fs.writeFileSync(filePath, output, 'utf8');
fs.unlinkSync(tempFile);
console.log('✅ ai_generated_notes.js updated successfully');
console.log(`File size: ${(fs.statSync(filePath).size / 1024).toFixed(1)} KB`);
