mindmap
  root((Everyday Chem))
    Cleansing Agents
      ::icon(fas fa-check)
      Soaps  sodium salts
      ::icon(fas fa-check)
      Detergents  sulfonates
    Industrial
      ::icon(fas fa-check)
      Glass: supercooled liquid
      ::icon(fas fa-check)
      Cement: gypsum  CaSO4.2H2O
      ::icon(fas fa-check)
      Fertilisers  NPK
    Fuels
      ::icon(fas fa-check)
      LPG: butane, propane
      ::icon(fas fa-check)
      CNG: methane  CH4