mindmap
  root((Plant Kingdom))
    Cryptogams
      ::icon(fas fa-check)
      Thallophyta: Simple, algae
      ::icon(fas fa-check)
      Bryophyta: Amphibians, mosses
      ::icon(fas fa-check)
      Pteridophyta: Vascular, ferns
    Phanerogams
      ::icon(fas fa-check)
      Gymnosperms: Naked seeds
      ::icon(fas fa-check)
      Angiosperms: Flowering, enclosed
    Angiosperms
      ::icon(fas fa-check)
      Monocots: 1 cotyledon, parallel venation
      ::icon(fas fa-check)
      Dicots: 2 cotyledons, reticulate venation