mindmap
  root((Amendments & Parts))
    Schedules
      ::icon(fas fa-check)
      12 Schedules
      ::icon(fas fa-check)
      Mnemonic
    Parts
      ::icon(fas fa-check)
      Part I to XXII
    Amendments
      ::icon(fas fa-check)
      42nd, 44th, 86th, 101st