mindmap
  root((Planning & FYPs))
    Early Plans
      ::icon(fas fa-check)
      1st: Harrod-Domar
      ::icon(fas fa-check)
      2nd: Mahalanobis
      ::icon(fas fa-check)
      3rd: Gadgil
    Later Plans
      ::icon(fas fa-check)
      4th: Bank nationalization
      ::icon(fas fa-check)
      5th: Garibi Hatao
      ::icon(fas fa-check)
      12th: Final plan
    NITI Aayog
      ::icon(fas fa-check)
      Cooperative Federalism
      ::icon(fas fa-check)
      Bottom-up approach