mindmap
  root((Carbon Compounds))
    Allotropes
      ::icon(fas fa-check)
      Diamond: Hardest
      ::icon(fas fa-check)
      Graphite: Conductor
      ::icon(fas fa-check)
      Fullerene: C-60
      ::icon(fas fa-check)
      Graphene: 2D
    Hydrocarbons
      ::icon(fas fa-check)
      Alkanes: saturated
      ::icon(fas fa-check)
      Alkenes/Alkynes: unsaturated
    Reactions
      ::icon(fas fa-check)
      Combustion
      ::icon(fas fa-check)
      Esterification
      ::icon(fas fa-check)
      Saponification