mindmap
  root((Chemistry Numericals))
    Mole Concept
      ::icon(fas fa-check)
      n = given/molar mass
      ::icon(fas fa-check)
      STP volume: 22.4 L
      ::icon(fas fa-check)
      Avogadro's constant
    Concentration
      ::icon(fas fa-check)
      Molarity: mol/L
      ::icon(fas fa-check)
      Molality: mol/kg
      ::icon(fas fa-check)
      Normality: eq/L
      ::icon(fas fa-check)
      Mole Fraction
    Equivalent Mass
      ::icon(fas fa-check)
      Molar mass / n-factor
      ::icon(fas fa-check)
      Acids: basicity
      ::icon(fas fa-check)
      Bases: acidity